#%RAML 1.0 Library

annotationTypes:
  deprecated:
    properties:
      date: datetime
      deprecatedBy: string
      comment: nil | string
  monitoringInterval:
    type: integer
    description: interval in seconds
    example: 2
  info:
    properties:
      license:
        type: string
        enum: [ "MIT", "Apache 2.0" ]
    allowedTargets: API
  rediractable: boolean
  experimental: string | nil
