# .goreleaser.yml
# Build customization
builds:
  - main: main.go
    binary: rapid
    goos:
      - darwin
      - linux
      # - windows TODO enable windows after gracehttp solution
    goarch:
      - amd64
