# .goreleaser.yml
# Build customization
builds:
  - main: main.go
    binary: rapid
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
fpm:
  # Your app's vendor.
  # Default is empty.
  vendor: Delving B.V.
  # Your app's homepage.
  # Default is empty.
  homepage: https://www.delving.eu/rapid/

  # Your app's maintainer (probably you).
  # Default is empty.
  maintainer: info@delving.eu

  # Your app's description.
  # Default is empty.
  description: RAPID Linked Open Data platform

  # Your app's license.
  # Default is empty.
  license: Apache 2.0

  # Formats to be generated.
  formats:
    - deb
    - rpm

  # Packages your package depends on.
  # dependencies:
    # - git

  # Packages that conflict with your package.
  # conflicts:
    # - svn

  # Override default /usr/local/bin destination for binaries
  bindir: /opt/hub3/rapid

  # Files or directories to add to your package (beyond the binary).
  # Keys are source paths to get the files from.
  # Values are the destination locations of the files in the package.
  files:
    "deploy/systemd/": "/usr/lib/systemd/system "
    ".rapid.toml": "/opt/hub3/rapid"
    "public": "/opt/hub3/rapid"
