# .goreleaser.yml
# Build customization
builds:
  - main: main.go
    binary: rapid
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    # Custom ldflags
    ldflags: -s -w -X main.Version={{.Version}}  -X main.GitHash={{.Commit}} -X main.BuildStamp={{.Date}} -X main.BuildAgent="GoReleaser"

# fpm: 
nfpm: 
  # This is parsed with the Go template engine and the following variables
  # are available:
  # - ProjectName
  # - Tag
  # - Version (Git tag without `v` prefix)
  # - Os
  # - Arch
  # - Arm (ARM version)
  # - Env (environment variables)
  # Default: `{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}`
  # name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  # Your app's vendor.
  # Default is empty.
  vendor: Delving B.V.
  # Your app's homepage.
  # Default is empty.
  homepage: https://www.delving.eu/rapid/

  # Your app's maintainer (probably you).
  # Default is empty.
  maintainer: info@delving.eu

  # Your app's description.
  # Default is empty.
  description: RAPID Linked Open Data platform

  # Your app's license.
  # Default is empty.
  license: Apache 2.0

  # Formats to be generated.
  formats:
    - deb
    - rpm

  # Packages your package depends on.
  dependencies:
    - systemd

  # Packages that conflict with your package.
  # conflicts:
    # - svn

  # Override default /usr/local/bin destination for binaries
  bindir: /opt/hub3/rapid

  # Files or directories to add to your package (beyond the binary).
  # Keys are source paths to get the files from.
  # Values are the destination locations of the files in the package.
  files:
    "public": "/opt/hub3/rapid/"

  # Config files to add to your package. They are about the same as
  # the files keyword, except package managers treat them differently (while
  # uninstalling, mostly).
  # Keys are source paths to get the files from.
  # Values are the destination locations of the files in the package.
  config_files:
    "deploy/rapid.service": "/lib/systemd/system/rapid.service"
    "deploy/rapid-syslog.conf": "/etc/rsyslog.d/rapid-syslog.conf"
    "rapid.toml": "/etc/default/rapid.toml"

sign:
  # name of the signature file.
  # '${artifact}' is the path to the artifact that should be signed.
  #
  # signature: "${artifact}.sig"

  # path to the signature command
  #
  # cmd: gpg

  # command line arguments for the command
  #
  # to sign with a specific key use
  # args: ["-u", "<key id, fingerprint, email, ...>", "--output", "${signature}", "--detach-sign", "${artifact}"]
  #
  # args: ["--output", "${signature}", "--detach-sign", "${artifact}"]


  # which artifacts to sign
  #
  #   checksum: only checksum file(s)
  #   all:      all artifacts
  #   none:     no signing
  #
  # artifacts: none
