# The default orgId
orgId = "rapid"

[http]
# all the configuration for the http sub-command
# The port of the http server
port = 3001

[ElasticSearch]
urls = ["http://localhost:9200"]

[Logging]
devmode = true
sentrydsn = ""

[rdf]
# the fully qualified URL including the port
sparqlHost = "http://localhost:9999"
# the path to the SPARQL endpoint. A '%s' can be inserted in the path to be replaced with the orgId.
sparqlPath = "/bigdata/namespace/%s/sparql"
# A list of RDF entry points. 
routedEntryPoints = ["http://localhost:3000"]
# The base url used for minting RDF URI's
baseUrl = "http://data.rapid.org"


[oaipmh]
# options: no, transient, persistent
deletedRecords = "persistent"
# enable the oai-pmh endpoint at /api/oai-pmh
enabled = true 
# admin emails 
adminEmails = ["info@delving.eu",]
# repositoryName
repositoryName = "dev1"

[webresource]
# enabel the webresource endpoint /api/webresource
enabled = true
# webresource source dir
sourceDir = "/tmp/webresource"
# path to vips binary. When not found deepzoom is disabled
vipsBin = "/usr/bin/vips"


[imageproxy]
# enable the image proxy at /api/imageproxy
enabled = true
# cache dir (tiered approach with memory first)
# if empty it will be sourceDir + 'cache'
cacheDir = "/tmp/webresource/cache"
# a list of allowed referrers. If empty everything is allowed
referrer = []
# a list of allowed remote hosts. If empty everything is allowed
whitelist = []
# allow images to scale beyond their original dimensions
scaleUp = false
# time limit for request served by this proxy. 0 is no timeout
timeout = 0
# enable deepzoom of images
deepzoom = true



