# The default orgId
orgId = "rapid"

[http]
# all the configuration for the http sub-command
# The port of the http server
port = 3001

[ElasticSearch]
# enable the elasticsearch search api
enabled = true 
# the urls where we can find elasticsearch
urls = ["http://localhost:9200"]
# the name of the index. If empty it is the name of the OrgId
index = "rapid2"
# if _mapping and _search proxies should be enabled
proxy = true 

[logging]
devmode = true
sentrydsn = ""

[rdf]
# the fully qualified URL including the port
sparqlHost = "http://localhost:3030"
# the path to the SPARQL endpoint. A '%s' can be inserted in the path to be replaced with the orgId.
#sparqlPath = "/bigdata/namespace/%s/sparql"
sparqlPath = "/%s/sparql"
# sparqlUpdate path is the path to the write endpoint. A '%s' can be inserted in the path to be replaced with the orgId.
sparqlUpdatePath = "/%s/update"
# dataPath is the path to the GraphStore Protocol endpoint
dataPath = "/%s/data"
# A list of RDF entry points. 
routedEntryPoints = ["http://localhost:3000"]
# The base url used for minting RDF URI's
baseUrl = "http://data.rapid.org"
# Enable the sparql endpoint proxy (Read-Only)
sparqlEnabled = true 
# Enable storing of the RDF records in the triple store specified in sparqlUpdatePath (default: false)
rdfStoreEnabled = false

[oaipmh]
# options: no, transient, persistent
deletedRecords = "persistent"
# enable the oai-pmh endpoint at /api/oai-pmh
enabled = true
# admin emails
adminEmails = ["info@delving.eu",]
# repositoryName
repositoryName = "dev1"

[webresource]
# enabel the webresource endpoint /api/webresource
enabled = true
# webresource source dir
sourceDir = "/tmp/webresource"
# path to vips binary. When not found deepzoom is disabled
vipsBin = "/usr/bin/vips"


[imageproxy]
# enable the image proxy at /api/imageproxy
enabled = true
# cache dir (tiered approach with memory first)
# if empty it will be sourceDir + 'cache'
cacheDir = "/tmp/imageproxy"
# a list of allowed referrers. If empty everything is allowed
referrer = []

# a list of allowed remote hosts. If empty everything is allowed
whitelist = []
# allow images to scale beyond their original dimensions
scaleUp = false
# time limit for request served by this proxy. 0 is no timeout
timeout = 10
# enable deepzoom of images
deepzoom = true
# path where to mount the imageproxy. default: "imageproxy".
proxyPrefix = "imageproxy"

[lod]
# enable the lod routing point
enabled = true
## resource routing point
resource = "resource"
# html routing point
html = "page"
# rdf data routing point
rdf = "data"

[[namespaces]]
base = "http://purl.org/dc/elements/1.1/"
prefix = "dc"

[[namespaces]]
base = "http://purl.org/abm/sen"
prefix = "abm"

[[namespaces]]
base = "http://www.europeana.eu/schemas/ese/"
prefix = "europeana"

[[namespaces]]
base = "http://schemas.delving.eu/"
prefix = "delving"

[[namespaces]]
base = "http://purl.org/dc/terms/"
prefix = "dcterms"

[[namespaces]]
base = "http://www.delving.eu/namespaces/custom/"
prefix = "custom"

[[namespaces]]
base = "http://www.musip.nl/"
prefix = "musip"

[[namespaces]]
base = "http://www.itin.nl/namespace/"
prefix = "itin"

[[namespaces]]
base = "http://www.itin.nl/drupal/"
prefix = "drup"

[[namespaces]]
base = "http://www.ab-c.nl/"
prefix = "abc"

[[namespaces]]
base = "http://delving.eu/namespaces/raw/"
prefix = "raw"

[[namespaces]]
base = "http://www.icn.nl/schemas/icn/"
prefix = "icn"

[[namespaces]]
base = "http://schemas.delving.eu/aff/"
prefix = "aff"

[[namespaces]]
base = "http://www.w3.org/2004/02/skos/core#"
prefix = "skos"

[[namespaces]]
base = "http://dbpedia.org/ontology/"
prefix = "dbpedia-owl"

[[namespaces]]
base = "http://www.w3.org/2003/01/geo/wgs84_pos#"
prefix = "wgs84_pos"

[[namespaces]]
base = "http://xmlns.com/foaf/0.1/"
prefix = "foaf"

[[namespaces]]
base = "http://www.w3.org/2002/07/owl#"
prefix = "owl"

[[namespaces]]
base = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
prefix = "rdf"

[[namespaces]]
base = "http://www.w3.org/2000/01/rdf-schema#"
prefix = "rdfs"

[[namespaces]]
base = "http://www.europeana.eu/schemas/edm/"
prefix = "edm"

[[namespaces]]
base = "http://www.openarchives.org/ore/terms/"
prefix = "ore"

[[namespaces]]
base = "http://schemas.delving.eu/narthex/terms/"
prefix = "narthex"

[[namespaces]]
base = "http://schemas.delving.eu/nave/terms/"
prefix = "nave"

[[namespaces]]
base = "http://localhost:8000/resource/"
prefix = "devmode"

[[namespaces]]
base = "http://schemas.delving.eu/resource/ns/tib/"
prefix = "tib"

[[namespaces]]
base = "http://creativecommons.org/ns#"
prefix = "cc"

[[namespaces]]
base = "http://www.geonames.org/ontology#"
prefix = "gn"

[[namespaces]]
base = "http://rdvocab.info/ElementsGr2/"
prefix = "rda"

[rdftag]
label = [
    "http://www.w3.org/2004/02/skos/core#preflabel",
    "http://www.w3.org/2000/01/rdf-schema#label",
    "http://www.w3.org/2004/02/skos/core#altLabel",
    "http://xmlns.com/foaf/0.1/name",
    "http://www.geonames.org/ontology#name",
    "http://purl.org/dc/elements/1.1/title",
    "http://schemas.delving.eu/narthex/terms/proxyLiteralValue",
    "http://dbpedia.org/ontology/name",
]

thumbnail = [
    "http://xmlns.com/foaf/0.1/depiction",
    "http://schemas.delving.eu/nave/terms/thumbnail",
    "http://schemas.delving.eu/nave/terms/thumbSmall",
    "http://schemas.delving.eu/nave/terms/thumbLarge",
    "http://www.europeana.eu/schemas/edm/object",
    "http://www.europeana.eu/schemas/edm/isShownBy",
]

latLong = []
dateRange = []
date = []
