version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: elasticsearch7
    ports:
      - "9200:9200"
      #- "9300:9300"
    environment:
      - discovery.type=single-node 
      - cluster.name=hub3_cluster
      - xpack.security.enabled=false
      #- bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet

  fuseki:
    image: stain/jena-fuseki:latest
    container_name: fuseki-zvt
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=pw123
    command:
        ["/jena-fuseki/fuseki-server", "--set", "tdb:unionDefaultGraph=true"]
  nats:
    image: nats-streaming
    ports:
      - "8222:8222"
      - "4222:4222"
    command:
        - "--cluster_id"
        - "hub3-nats"
        - "--http_port"
        - "8222"
        - "--port"
        - "4222"
    networks:
      - esnet

networks:
  esnet:
