version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: elasticsearch7
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - cluster.name=hub3_cluster
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet

  fuseki:
    image: zacanbot/fuseki
    container_name: hub3-fuseki
    environment:
        JVM_ARGS: -Xmx1g
    ports:
      - "3033:3030"
    volumes:
        - ./docker-data/fuseki/data:/data/fuseki
    environment:
      - ADMIN_PASSWORD=pw123
    command:
        ["/jena-fuseki/fuseki-server", "--set", "tdb:unionDefaultGraph=true"]

  nats:
    image: nats-streaming
    ports:
      - "8222:8222"
      - "4222:4222"
    command:
        - "--cluster_id"
        - "hub3-nats"
        - "--http_port"
        - "8222"
        - "--port"
        - "4222"
        - "--max_bytes" 
        - "1GB"
        - "--max_msgs"
        - "1000000"
    networks:
      - esnet

  postgresql:
    image: postgis/postgis:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: pw123

  redis:
      image: "redis:alpine"

      command: redis-server --requirepass sOmE_sEcUrE_pAsS

      ports:
        - "6379:6379"

      volumes:
        - $PWD/docker-data/redis-data:/var/lib/redis
        - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

      environment:
        - REDIS_REPLICATION_MODE=master

      networks:
        node_net:
          ipv4_address: 172.28.1.4

  asynqmon:
      image: "hibiken/asynqmon"

      environment:
        - REDIS_URL=redis://:sOmE_sEcUrE_pAsS@redis:6379/0

      ports:
        - "8080:8080"

      networks:
        node_net:
    

# networking
networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
  esnet:
