version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.2
    container_name: elasticsearch6
    ports:
      - "9200:9200"
      #- "9300:9300"
    environment:
      - discovery.type=single-node 
      - cluster.name=hub3_cluster
      #- bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet
  fuseki:
    image: stain/jena-fuseki:latest
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=pw123
    command:
        ["/jena-fuseki/fuseki-server", "--set", "tdb:unionDefaultGraph=true"]
networks:
  esnet:
