version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: elasticsearch7
    ports:
      - "9200:9200"
      #- "9300:9300"
    environment:
      - discovery.type=single-node
      - cluster.name=hub3_cluster
      - xpack.security.enabled=false
      #- bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet

  minio:
    image: minio/minio
    ports:
      - "9010:9000"
      - "9001:9001"
    volumes:
      - ./docker-data/minio_storage:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: Strong#Pass#2023
      MINIO_ACCESS_KEY: "kPxADQXcHFbR9i1V"
      MINIO_SECRET_KEY: "LiwsjNxulYJVyey50U1ypTabt8BiMWiU"
    command: server --console-address ":9001" /data

  fuseki:
    image: zacanbot/fuseki
    container_name: hub3-fuseki
    environment:
      - JVM_ARGS=-Xmx1g
      - ADMIN_PASSWORD=pw123
    ports:
      - "3033:3030"
    volumes:
        - ./docker-data/fuseki/data:/data/fuseki
    command:
        ["/jena-fuseki/fuseki-server", "--set", "tdb:unionDefaultGraph=true"]

  nats:
    image: nats-streaming
    ports:
      - "8222:8222"
      - "4222:4222"
    command:
        - "--cluster_id"
        - "hub3-nats"
        - "--http_port"
        - "8222"
        - "--port"
        - "4222"
        - "--max_bytes" 
        - "1GB"
        - "--max_msgs"
        - "1000000"
    networks:
      - esnet

  postgresql:
    image: postgis/postgis:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: pw123

networks:
  esnet:
