// Copyright 2017 Delving B.V.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.1
// source: hub3/ead/eadpb/scan.proto

package eadpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ViewType int32

const (
	// Default type.
	ViewType_DOWNLOADONLY ViewType = 0
	// DZI tiles.
	ViewType_DZI ViewType = 1
	// JPEG files for thumbnails.
	ViewType_JPEG  ViewType = 2
	ViewType_PDF   ViewType = 3
	ViewType_AUDIO ViewType = 4
	ViewType_VIDEO ViewType = 5
)

// Enum value maps for ViewType.
var (
	ViewType_name = map[int32]string{
		0: "DOWNLOADONLY",
		1: "DZI",
		2: "JPEG",
		3: "PDF",
		4: "AUDIO",
		5: "VIDEO",
	}
	ViewType_value = map[string]int32{
		"DOWNLOADONLY": 0,
		"DZI":          1,
		"JPEG":         2,
		"PDF":          3,
		"AUDIO":        4,
		"VIDEO":        5,
	}
)

func (x ViewType) Enum() *ViewType {
	p := new(ViewType)
	*p = x
	return p
}

func (x ViewType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ViewType) Descriptor() protoreflect.EnumDescriptor {
	return file_hub3_ead_eadpb_scan_proto_enumTypes[0].Descriptor()
}

func (ViewType) Type() protoreflect.EnumType {
	return &file_hub3_ead_eadpb_scan_proto_enumTypes[0]
}

func (x ViewType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ViewType.Descriptor instead.
func (ViewType) EnumDescriptor() ([]byte, []int) {
	return file_hub3_ead_eadpb_scan_proto_rawDescGZIP(), []int{0}
}

type File struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	View  ViewType               `protobuf:"varint,1,opt,name=view,proto3,enum=eadpb.ViewType" json:"view,omitempty"`
	// For scans this is the NL-HaNA_1.01.02_11_P1 type filename.
	Filename string `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	// The file-uuid from GAF
	Fileuuid string `protobuf:"bytes,4,opt,name=fileuuid,proto3" json:"fileuuid,omitempty"`
	// The duuid is not needed for the frontend as of now I think, but could be useful.
	FileSize int32 `protobuf:"varint,6,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	// Absolute web accessible url to the file source so internet web clients can access them.
	// These urls are examples and not the real url patterns.
	// For DZI example: [https://test.nationaalarchief.nl/gaf/iip/1.04.02_1.dzi]
	// Or JPEG thumb example: [https://test.nationaalarchief.nl/gaf/iip/thumb-100x100.jpg]
	// Or PDF file example: [https://test.nationaalarchief.nl/gaf/file/1.04.02.pdf]
	ThumbnailURI string `protobuf:"bytes,2,opt,name=thumbnailURI,proto3" json:"thumbnailURI,omitempty"`
	// Optional uri for downloading the DZI XML description.
	DeepzoomURI string `protobuf:"bytes,7,opt,name=deepzoomURI,proto3" json:"deepzoomURI,omitempty"`
	// Optional uri for downloading the original.
	DownloadURI string `protobuf:"bytes,8,opt,name=downloadURI,proto3" json:"downloadURI,omitempty"`
	// Mime-Type of the file
	MimeType string `protobuf:"bytes,9,opt,name=mimeType,proto3" json:"mimeType,omitempty"`
	// The relative sort order of the File within the inventoryID
	SortKey int32 `protobuf:"varint,10,opt,name=sortKey,proto3" json:"sortKey,omitempty"`
	// Extra file metadata like collection, creator, date.
	MetaData      map[string]*Values `protobuf:"bytes,11,rep,name=metaData,proto3" json:"metaData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_hub3_ead_eadpb_scan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_hub3_ead_eadpb_scan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_hub3_ead_eadpb_scan_proto_rawDescGZIP(), []int{0}
}

func (x *File) GetView() ViewType {
	if x != nil {
		return x.View
	}
	return ViewType_DOWNLOADONLY
}

func (x *File) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *File) GetFileuuid() string {
	if x != nil {
		return x.Fileuuid
	}
	return ""
}

func (x *File) GetFileSize() int32 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *File) GetThumbnailURI() string {
	if x != nil {
		return x.ThumbnailURI
	}
	return ""
}

func (x *File) GetDeepzoomURI() string {
	if x != nil {
		return x.DeepzoomURI
	}
	return ""
}

func (x *File) GetDownloadURI() string {
	if x != nil {
		return x.DownloadURI
	}
	return ""
}

func (x *File) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *File) GetSortKey() int32 {
	if x != nil {
		return x.SortKey
	}
	return 0
}

func (x *File) GetMetaData() map[string]*Values {
	if x != nil {
		return x.MetaData
	}
	return nil
}

type Values struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The display label
	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	// List of metadata string values
	Text          []string `protobuf:"bytes,2,rep,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Values) Reset() {
	*x = Values{}
	mi := &file_hub3_ead_eadpb_scan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Values) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Values) ProtoMessage() {}

func (x *Values) ProtoReflect() protoreflect.Message {
	mi := &file_hub3_ead_eadpb_scan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Values.ProtoReflect.Descriptor instead.
func (*Values) Descriptor() ([]byte, []int) {
	return file_hub3_ead_eadpb_scan_proto_rawDescGZIP(), []int{1}
}

func (x *Values) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Values) GetText() []string {
	if x != nil {
		return x.Text
	}
	return nil
}

type Pager struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	HasNext      bool                   `protobuf:"varint,1,opt,name=hasNext,proto3" json:"hasNext,omitempty"`
	HasPrevious  bool                   `protobuf:"varint,2,opt,name=hasPrevious,proto3" json:"hasPrevious,omitempty"`
	TotalCount   int32                  `protobuf:"varint,3,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	NrPages      int32                  `protobuf:"varint,4,opt,name=nrPages,proto3" json:"nrPages,omitempty"`
	PageCurrent  int32                  `protobuf:"varint,5,opt,name=pageCurrent,proto3" json:"pageCurrent,omitempty"`
	PageNext     int32                  `protobuf:"varint,6,opt,name=pageNext,proto3" json:"pageNext,omitempty"`
	PagePrevious int32                  `protobuf:"varint,7,opt,name=pagePrevious,proto3" json:"pagePrevious,omitempty"`
	PageSize     int32                  `protobuf:"varint,8,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	// Optional property where the result is centered around.
	ActiveFilename string `protobuf:"bytes,9,opt,name=activeFilename,proto3" json:"activeFilename,omitempty"`
	// The index of the place of the active File in the Files array.
	ActiveSortKey int32 `protobuf:"varint,10,opt,name=activeSortKey,proto3" json:"activeSortKey,omitempty"`
	// Optional. When the request was a paging request, i.e. without the FindingAid block.
	Paging        bool `protobuf:"varint,11,opt,name=paging,proto3" json:"paging,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pager) Reset() {
	*x = Pager{}
	mi := &file_hub3_ead_eadpb_scan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pager) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pager) ProtoMessage() {}

func (x *Pager) ProtoReflect() protoreflect.Message {
	mi := &file_hub3_ead_eadpb_scan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pager.ProtoReflect.Descriptor instead.
func (*Pager) Descriptor() ([]byte, []int) {
	return file_hub3_ead_eadpb_scan_proto_rawDescGZIP(), []int{2}
}

func (x *Pager) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *Pager) GetHasPrevious() bool {
	if x != nil {
		return x.HasPrevious
	}
	return false
}

func (x *Pager) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *Pager) GetNrPages() int32 {
	if x != nil {
		return x.NrPages
	}
	return 0
}

func (x *Pager) GetPageCurrent() int32 {
	if x != nil {
		return x.PageCurrent
	}
	return 0
}

func (x *Pager) GetPageNext() int32 {
	if x != nil {
		return x.PageNext
	}
	return 0
}

func (x *Pager) GetPagePrevious() int32 {
	if x != nil {
		return x.PagePrevious
	}
	return 0
}

func (x *Pager) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Pager) GetActiveFilename() string {
	if x != nil {
		return x.ActiveFilename
	}
	return ""
}

func (x *Pager) GetActiveSortKey() int32 {
	if x != nil {
		return x.ActiveSortKey
	}
	return 0
}

func (x *Pager) GetPaging() bool {
	if x != nil {
		return x.Paging
	}
	return false
}

type FindingAid struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The dataset identifier and EAD identifier.
	ArchiveID string `protobuf:"bytes,1,opt,name=archiveID,proto3" json:"archiveID,omitempty"`
	// The long title for the Archive.
	ArchiveTitle string `protobuf:"bytes,2,opt,name=archiveTitle,proto3" json:"archiveTitle,omitempty"`
	// The unit idendifier for a given c-level.
	InventoryID string `protobuf:"bytes,3,opt,name=inventoryID,proto3" json:"inventoryID,omitempty"`
	// The tree-path under which the inventory is stored.
	InventoryPath string `protobuf:"bytes,4,opt,name=inventoryPath,proto3" json:"inventoryPath,omitempty"`
	// The unit-title of the inventory.
	InventoryTitle string `protobuf:"bytes,5,opt,name=inventoryTitle,proto3" json:"inventoryTitle,omitempty"`
	// The deliverable uuid of the METS file where all the Files are extracted from.
	Duuid string `protobuf:"bytes,6,opt,name=duuid,proto3" json:"duuid,omitempty"`
	// Return true if the files in the WHOLE (not just the current page) set are DZI tiles.
	HasOnlyTiles bool `protobuf:"varint,7,opt,name=hasOnlyTiles,proto3" json:"hasOnlyTiles,omitempty"`
	// Sorted array of mime-types for current deliverable-uuid
	MimeTypes map[string]int32 `protobuf:"bytes,8,rep,name=mimeTypes,proto3" json:"mimeTypes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// number of linked digital objects
	FileCount int32 `protobuf:"varint,9,opt,name=fileCount,proto3" json:"fileCount,omitempty"`
	// the linked Files to the FindingAid
	Files []*File `protobuf:"bytes,10,rep,name=files,proto3" json:"files,omitempty"`
	// filter keys
	FilterTypes []string `protobuf:"bytes,11,rep,name=filterTypes,proto3" json:"filterTypes,omitempty"`
	// scan navigation
	HasScanNavigation bool `protobuf:"varint,12,opt,name=hasScanNavigation,proto3" json:"hasScanNavigation,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FindingAid) Reset() {
	*x = FindingAid{}
	mi := &file_hub3_ead_eadpb_scan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindingAid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindingAid) ProtoMessage() {}

func (x *FindingAid) ProtoReflect() protoreflect.Message {
	mi := &file_hub3_ead_eadpb_scan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindingAid.ProtoReflect.Descriptor instead.
func (*FindingAid) Descriptor() ([]byte, []int) {
	return file_hub3_ead_eadpb_scan_proto_rawDescGZIP(), []int{3}
}

func (x *FindingAid) GetArchiveID() string {
	if x != nil {
		return x.ArchiveID
	}
	return ""
}

func (x *FindingAid) GetArchiveTitle() string {
	if x != nil {
		return x.ArchiveTitle
	}
	return ""
}

func (x *FindingAid) GetInventoryID() string {
	if x != nil {
		return x.InventoryID
	}
	return ""
}

func (x *FindingAid) GetInventoryPath() string {
	if x != nil {
		return x.InventoryPath
	}
	return ""
}

func (x *FindingAid) GetInventoryTitle() string {
	if x != nil {
		return x.InventoryTitle
	}
	return ""
}

func (x *FindingAid) GetDuuid() string {
	if x != nil {
		return x.Duuid
	}
	return ""
}

func (x *FindingAid) GetHasOnlyTiles() bool {
	if x != nil {
		return x.HasOnlyTiles
	}
	return false
}

func (x *FindingAid) GetMimeTypes() map[string]int32 {
	if x != nil {
		return x.MimeTypes
	}
	return nil
}

func (x *FindingAid) GetFileCount() int32 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

func (x *FindingAid) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *FindingAid) GetFilterTypes() []string {
	if x != nil {
		return x.FilterTypes
	}
	return nil
}

func (x *FindingAid) GetHasScanNavigation() bool {
	if x != nil {
		return x.HasScanNavigation
	}
	return false
}

type ViewResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The block with the page
	Pager *Pager `protobuf:"bytes,1,opt,name=pager,proto3" json:"pager,omitempty"`
	// Optional. The FindingAid is only shown on the first request and is empty for paging requests.
	FindingAid *FindingAid `protobuf:"bytes,2,opt,name=findingAid,proto3" json:"findingAid,omitempty"`
	// Sorted by filename.
	Files         []*File `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewResponse) Reset() {
	*x = ViewResponse{}
	mi := &file_hub3_ead_eadpb_scan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewResponse) ProtoMessage() {}

func (x *ViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub3_ead_eadpb_scan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewResponse.ProtoReflect.Descriptor instead.
func (*ViewResponse) Descriptor() ([]byte, []int) {
	return file_hub3_ead_eadpb_scan_proto_rawDescGZIP(), []int{4}
}

func (x *ViewResponse) GetPager() *Pager {
	if x != nil {
		return x.Pager
	}
	return nil
}

func (x *ViewResponse) GetFindingAid() *FindingAid {
	if x != nil {
		return x.FindingAid
	}
	return nil
}

func (x *ViewResponse) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

type ViewRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required; example 2.13.39
	ArchiveID string `protobuf:"bytes,1,opt,name=archiveID,proto3" json:"archiveID,omitempty"`
	// Either InventoryID or InventoryPath is Required; e.g. 3.1.
	InventoryID string `protobuf:"bytes,2,opt,name=inventoryID,proto3" json:"inventoryID,omitempty"`
	// Either InventoryID or InventoryPath is Required; e.g. @3~3.1.
	InvertoryPath string `protobuf:"bytes,3,opt,name=invertoryPath,proto3" json:"invertoryPath,omitempty"`
	// Optional, defaults to 50 tiledImages per set.
	PageSize int32 `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	// Optional, defaults to 1.
	Page int32 `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	// Optional to jump into a set with this file centered.
	Fileuuid string `protobuf:"bytes,6,opt,name=fileuuid,proto3" json:"fileuuid,omitempty"`
	// Optional to jump into a set with this file centered.
	Filename string `protobuf:"bytes,7,opt,name=filename,proto3" json:"filename,omitempty"`
	// Optional thumbnail configuration options.
	ThumbnailConf string `protobuf:"bytes,8,opt,name=thumbnailConf,proto3" json:"thumbnailConf,omitempty"`
	// Optional. When paging is true the FindingAid block is not included in the response.
	Paging bool `protobuf:"varint,9,opt,name=paging,proto3" json:"paging,omitempty"`
	// Optional. sortKey is an integer representing the order of the file in the files array.
	// Note: starts at 1, i.e. not zero-based.
	SortKey       int64 `protobuf:"varint,10,opt,name=sortKey,proto3" json:"sortKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewRequest) Reset() {
	*x = ViewRequest{}
	mi := &file_hub3_ead_eadpb_scan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewRequest) ProtoMessage() {}

func (x *ViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub3_ead_eadpb_scan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewRequest.ProtoReflect.Descriptor instead.
func (*ViewRequest) Descriptor() ([]byte, []int) {
	return file_hub3_ead_eadpb_scan_proto_rawDescGZIP(), []int{5}
}

func (x *ViewRequest) GetArchiveID() string {
	if x != nil {
		return x.ArchiveID
	}
	return ""
}

func (x *ViewRequest) GetInventoryID() string {
	if x != nil {
		return x.InventoryID
	}
	return ""
}

func (x *ViewRequest) GetInvertoryPath() string {
	if x != nil {
		return x.InvertoryPath
	}
	return ""
}

func (x *ViewRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ViewRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ViewRequest) GetFileuuid() string {
	if x != nil {
		return x.Fileuuid
	}
	return ""
}

func (x *ViewRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ViewRequest) GetThumbnailConf() string {
	if x != nil {
		return x.ThumbnailConf
	}
	return ""
}

func (x *ViewRequest) GetPaging() bool {
	if x != nil {
		return x.Paging
	}
	return false
}

func (x *ViewRequest) GetSortKey() int64 {
	if x != nil {
		return x.SortKey
	}
	return 0
}

var File_hub3_ead_eadpb_scan_proto protoreflect.FileDescriptor

const file_hub3_ead_eadpb_scan_proto_rawDesc = "" +
	"\n" +
	"\x19hub3/ead/eadpb/scan.proto\x12\x05eadpb\"\xa0\x03\n" +
	"\x04File\x12#\n" +
	"\x04view\x18\x01 \x01(\x0e2\x0f.eadpb.ViewTypeR\x04view\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x1a\n" +
	"\bfileuuid\x18\x04 \x01(\tR\bfileuuid\x12\x1a\n" +
	"\bfileSize\x18\x06 \x01(\x05R\bfileSize\x12\"\n" +
	"\fthumbnailURI\x18\x02 \x01(\tR\fthumbnailURI\x12 \n" +
	"\vdeepzoomURI\x18\a \x01(\tR\vdeepzoomURI\x12 \n" +
	"\vdownloadURI\x18\b \x01(\tR\vdownloadURI\x12\x1a\n" +
	"\bmimeType\x18\t \x01(\tR\bmimeType\x12\x18\n" +
	"\asortKey\x18\n" +
	" \x01(\x05R\asortKey\x125\n" +
	"\bmetaData\x18\v \x03(\v2\x19.eadpb.File.MetaDataEntryR\bmetaData\x1aJ\n" +
	"\rMetaDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.eadpb.ValuesR\x05value:\x028\x01\"2\n" +
	"\x06Values\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x12\n" +
	"\x04text\x18\x02 \x03(\tR\x04text\"\xe1\x02\n" +
	"\x05Pager\x12\x18\n" +
	"\ahasNext\x18\x01 \x01(\bR\ahasNext\x12 \n" +
	"\vhasPrevious\x18\x02 \x01(\bR\vhasPrevious\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x03 \x01(\x05R\n" +
	"totalCount\x12\x18\n" +
	"\anrPages\x18\x04 \x01(\x05R\anrPages\x12 \n" +
	"\vpageCurrent\x18\x05 \x01(\x05R\vpageCurrent\x12\x1a\n" +
	"\bpageNext\x18\x06 \x01(\x05R\bpageNext\x12\"\n" +
	"\fpagePrevious\x18\a \x01(\x05R\fpagePrevious\x12\x1a\n" +
	"\bpageSize\x18\b \x01(\x05R\bpageSize\x12&\n" +
	"\x0eactiveFilename\x18\t \x01(\tR\x0eactiveFilename\x12$\n" +
	"\ractiveSortKey\x18\n" +
	" \x01(\x05R\ractiveSortKey\x12\x16\n" +
	"\x06paging\x18\v \x01(\bR\x06paging\"\x87\x04\n" +
	"\n" +
	"FindingAid\x12\x1c\n" +
	"\tarchiveID\x18\x01 \x01(\tR\tarchiveID\x12\"\n" +
	"\farchiveTitle\x18\x02 \x01(\tR\farchiveTitle\x12 \n" +
	"\vinventoryID\x18\x03 \x01(\tR\vinventoryID\x12$\n" +
	"\rinventoryPath\x18\x04 \x01(\tR\rinventoryPath\x12&\n" +
	"\x0einventoryTitle\x18\x05 \x01(\tR\x0einventoryTitle\x12\x14\n" +
	"\x05duuid\x18\x06 \x01(\tR\x05duuid\x12\"\n" +
	"\fhasOnlyTiles\x18\a \x01(\bR\fhasOnlyTiles\x12>\n" +
	"\tmimeTypes\x18\b \x03(\v2 .eadpb.FindingAid.MimeTypesEntryR\tmimeTypes\x12\x1c\n" +
	"\tfileCount\x18\t \x01(\x05R\tfileCount\x12!\n" +
	"\x05files\x18\n" +
	" \x03(\v2\v.eadpb.FileR\x05files\x12 \n" +
	"\vfilterTypes\x18\v \x03(\tR\vfilterTypes\x12,\n" +
	"\x11hasScanNavigation\x18\f \x01(\bR\x11hasScanNavigation\x1a<\n" +
	"\x0eMimeTypesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x88\x01\n" +
	"\fViewResponse\x12\"\n" +
	"\x05pager\x18\x01 \x01(\v2\f.eadpb.PagerR\x05pager\x121\n" +
	"\n" +
	"findingAid\x18\x02 \x01(\v2\x11.eadpb.FindingAidR\n" +
	"findingAid\x12!\n" +
	"\x05files\x18\x03 \x03(\v2\v.eadpb.FileR\x05files\"\xb3\x02\n" +
	"\vViewRequest\x12\x1c\n" +
	"\tarchiveID\x18\x01 \x01(\tR\tarchiveID\x12 \n" +
	"\vinventoryID\x18\x02 \x01(\tR\vinventoryID\x12$\n" +
	"\rinvertoryPath\x18\x03 \x01(\tR\rinvertoryPath\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1a\n" +
	"\bfileuuid\x18\x06 \x01(\tR\bfileuuid\x12\x1a\n" +
	"\bfilename\x18\a \x01(\tR\bfilename\x12$\n" +
	"\rthumbnailConf\x18\b \x01(\tR\rthumbnailConf\x12\x16\n" +
	"\x06paging\x18\t \x01(\bR\x06paging\x12\x18\n" +
	"\asortKey\x18\n" +
	" \x01(\x03R\asortKey*N\n" +
	"\bViewType\x12\x10\n" +
	"\fDOWNLOADONLY\x10\x00\x12\a\n" +
	"\x03DZI\x10\x01\x12\b\n" +
	"\x04JPEG\x10\x02\x12\a\n" +
	"\x03PDF\x10\x03\x12\t\n" +
	"\x05AUDIO\x10\x04\x12\t\n" +
	"\x05VIDEO\x10\x052@\n" +
	"\rViewerService\x12/\n" +
	"\x04List\x12\x12.eadpb.ViewRequest\x1a\x13.eadpb.ViewResponseB\x10Z\x0ehub3/ead/eadpbb\x06proto3"

var (
	file_hub3_ead_eadpb_scan_proto_rawDescOnce sync.Once
	file_hub3_ead_eadpb_scan_proto_rawDescData []byte
)

func file_hub3_ead_eadpb_scan_proto_rawDescGZIP() []byte {
	file_hub3_ead_eadpb_scan_proto_rawDescOnce.Do(func() {
		file_hub3_ead_eadpb_scan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hub3_ead_eadpb_scan_proto_rawDesc), len(file_hub3_ead_eadpb_scan_proto_rawDesc)))
	})
	return file_hub3_ead_eadpb_scan_proto_rawDescData
}

var file_hub3_ead_eadpb_scan_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hub3_ead_eadpb_scan_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_hub3_ead_eadpb_scan_proto_goTypes = []any{
	(ViewType)(0),        // 0: eadpb.ViewType
	(*File)(nil),         // 1: eadpb.File
	(*Values)(nil),       // 2: eadpb.Values
	(*Pager)(nil),        // 3: eadpb.Pager
	(*FindingAid)(nil),   // 4: eadpb.FindingAid
	(*ViewResponse)(nil), // 5: eadpb.ViewResponse
	(*ViewRequest)(nil),  // 6: eadpb.ViewRequest
	nil,                  // 7: eadpb.File.MetaDataEntry
	nil,                  // 8: eadpb.FindingAid.MimeTypesEntry
}
var file_hub3_ead_eadpb_scan_proto_depIdxs = []int32{
	0, // 0: eadpb.File.view:type_name -> eadpb.ViewType
	7, // 1: eadpb.File.metaData:type_name -> eadpb.File.MetaDataEntry
	8, // 2: eadpb.FindingAid.mimeTypes:type_name -> eadpb.FindingAid.MimeTypesEntry
	1, // 3: eadpb.FindingAid.files:type_name -> eadpb.File
	3, // 4: eadpb.ViewResponse.pager:type_name -> eadpb.Pager
	4, // 5: eadpb.ViewResponse.findingAid:type_name -> eadpb.FindingAid
	1, // 6: eadpb.ViewResponse.files:type_name -> eadpb.File
	2, // 7: eadpb.File.MetaDataEntry.value:type_name -> eadpb.Values
	6, // 8: eadpb.ViewerService.List:input_type -> eadpb.ViewRequest
	5, // 9: eadpb.ViewerService.List:output_type -> eadpb.ViewResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_hub3_ead_eadpb_scan_proto_init() }
func file_hub3_ead_eadpb_scan_proto_init() {
	if File_hub3_ead_eadpb_scan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hub3_ead_eadpb_scan_proto_rawDesc), len(file_hub3_ead_eadpb_scan_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hub3_ead_eadpb_scan_proto_goTypes,
		DependencyIndexes: file_hub3_ead_eadpb_scan_proto_depIdxs,
		EnumInfos:         file_hub3_ead_eadpb_scan_proto_enumTypes,
		MessageInfos:      file_hub3_ead_eadpb_scan_proto_msgTypes,
	}.Build()
	File_hub3_ead_eadpb_scan_proto = out.File
	file_hub3_ead_eadpb_scan_proto_goTypes = nil
	file_hub3_ead_eadpb_scan_proto_depIdxs = nil
}
