package search

import (
	"bytes"
	"strconv"
	"strings"
	"unicode"

	"golang.org/x/text/runes"
	"golang.org/x/text/transform"
	"golang.org/x/text/unicode/norm"
)

// NativeASCIIFolding uses the Go native ASCII folding functionality.
// This is sufficient in most cases. When full compliance with the Lucene
// ASCIIFoldingFilter is required, use LuceneASCIIFolding().
func NativeASCIIFolding(text string) string {
	t := transform.Chain(norm.NFD, runes.Remove(runes.In(unicode.Mn)), norm.NFC)
	s, _, _ := transform.String(t, text)

	return s
}

// FoldASCII converts Unicode characters to ASCII equivalent.
// When none is found the original unicode is returned.
//
// The native Go solution in NativeASCIIFolding() does not produce the exact same
// result as the Lucene 'ASCIIFoldingFilter'.
func LuceneASCIIFolding(str string) string {
	var buffer bytes.Buffer

	for _, r := range str {
		buffer.WriteString(foldRune(r))
	}

	return buffer.String()
}

func runeToASCII(r rune) string {
	if r < 128 {
		return string(r)
	}

	return strings.ToUpper(strconv.FormatInt(int64(r), 16))
}

// nolint:gocyclo,funlen
// No linting for because this is just a very long list of conversion options
func foldRune(r rune) string {
	var buffer bytes.Buffer

	asciiRune := runeToASCII(r)

	switch asciiRune {
	case "C0", // [LATIN CAPITAL LETTER A WITH GRAVE]
		"C1",   // [LATIN CAPITAL LETTER A WITH ACUTE]
		"C2",   // [LATIN CAPITAL LETTER A WITH CIRCUMFLEX]
		"C3",   // [LATIN CAPITAL LETTER A WITH TILDE]
		"C4",   // [LATIN CAPITAL LETTER A WITH DIAERESIS]
		"C5",   // [LATIN CAPITAL LETTER A WITH RING ABOVE]
		"100",  // [LATIN CAPITAL LETTER A WITH MACRON]
		"102",  // [LATIN CAPITAL LETTER A WITH BREVE]
		"104",  // [LATIN CAPITAL LETTER A WITH OGONEK]
		"18F",  // [LATIN CAPITAL LETTER SCHWA]
		"1CD",  // [LATIN CAPITAL LETTER A WITH CARON]
		"1DE",  // [LATIN CAPITAL LETTER A WITH DIAERESIS AND MACRON]
		"1E0",  // [LATIN CAPITAL LETTER A WITH DOT ABOVE AND MACRON]
		"1FA",  // [LATIN CAPITAL LETTER A WITH RING ABOVE AND ACUTE]
		"200",  // [LATIN CAPITAL LETTER A WITH DOUBLE GRAVE]
		"202",  // [LATIN CAPITAL LETTER A WITH INVERTED BREVE]
		"226",  // [LATIN CAPITAL LETTER A WITH DOT ABOVE]
		"23A",  // [LATIN CAPITAL LETTER A WITH STROKE]
		"1D00", // [LATIN LETTER SMALL CAPITAL A]
		"1E00", // [LATIN CAPITAL LETTER A WITH RING BELOW]
		"1EA0", // [LATIN CAPITAL LETTER A WITH DOT BELOW]
		"1EA2", // [LATIN CAPITAL LETTER A WITH HOOK ABOVE]
		"1EA4", // [LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND ACUTE]
		"1EA6", // [LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND GRAVE]
		"1EA8", // [LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE]
		"1EAA", // [LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND TILDE]
		"1EAC", // [LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND DOT BELOW]
		"1EAE", // [LATIN CAPITAL LETTER A WITH BREVE AND ACUTE]
		"1EB0", // [LATIN CAPITAL LETTER A WITH BREVE AND GRAVE]
		"1EB2", // [LATIN CAPITAL LETTER A WITH BREVE AND HOOK ABOVE]
		"1EB4", // [LATIN CAPITAL LETTER A WITH BREVE AND TILDE]
		"1EB6", // [LATIN CAPITAL LETTER A WITH BREVE AND DOT BELOW]
		"24B6", // [CIRCLED LATIN CAPITAL LETTER A]
		"FF21": // [FULLWIDTH LATIN CAPITAL LETTER A]
		buffer.WriteString("A")
	case "E0", // [LATIN SMALL LETTER A WITH GRAVE]
		"E1",   // [LATIN SMALL LETTER A WITH ACUTE]
		"E2",   // [LATIN SMALL LETTER A WITH CIRCUMFLEX]
		"E3",   // [LATIN SMALL LETTER A WITH TILDE]
		"E4",   // [LATIN SMALL LETTER A WITH DIAERESIS]
		"E5",   // [LATIN SMALL LETTER A WITH RING ABOVE]
		"101",  // [LATIN SMALL LETTER A WITH MACRON]
		"103",  // [LATIN SMALL LETTER A WITH BREVE]
		"105",  // [LATIN SMALL LETTER A WITH OGONEK]
		"1CE",  // [LATIN SMALL LETTER A WITH CARON]
		"1DF",  // [LATIN SMALL LETTER A WITH DIAERESIS AND MACRON]
		"1E1",  // [LATIN SMALL LETTER A WITH DOT ABOVE AND MACRON]
		"1FB",  // [LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE]
		"201",  // [LATIN SMALL LETTER A WITH DOUBLE GRAVE]
		"203",  // [LATIN SMALL LETTER A WITH INVERTED BREVE]
		"227",  // [LATIN SMALL LETTER A WITH DOT ABOVE]
		"250",  // [LATIN SMALL LETTER TURNED A]
		"259",  // [LATIN SMALL LETTER SCHWA]
		"25A",  // [LATIN SMALL LETTER SCHWA WITH HOOK]
		"1D8F", // [LATIN SMALL LETTER A WITH RETROFLEX HOOK]
		"1D95", // [LATIN SMALL LETTER SCHWA WITH RETROFLEX HOOK]
		"1E01", // [LATIN SMALL LETTER A WITH RING BELOW]
		"1E9A", // [LATIN SMALL LETTER A WITH RIGHT HALF RING]
		"1EA1", // [LATIN SMALL LETTER A WITH DOT BELOW]
		"1EA3", // [LATIN SMALL LETTER A WITH HOOK ABOVE]
		"1EA5", // [LATIN SMALL LETTER A WITH CIRCUMFLEX AND ACUTE]
		"1EA7", // [LATIN SMALL LETTER A WITH CIRCUMFLEX AND GRAVE]
		"1EA9", // [LATIN SMALL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE]
		"1EAB", // [LATIN SMALL LETTER A WITH CIRCUMFLEX AND TILDE]
		"1EAD", // [LATIN SMALL LETTER A WITH CIRCUMFLEX AND DOT BELOW]
		"1EAF", // [LATIN SMALL LETTER A WITH BREVE AND ACUTE]
		"1EB1", // [LATIN SMALL LETTER A WITH BREVE AND GRAVE]
		"1EB3", // [LATIN SMALL LETTER A WITH BREVE AND HOOK ABOVE]
		"1EB5", // [LATIN SMALL LETTER A WITH BREVE AND TILDE]
		"1EB7", // [LATIN SMALL LETTER A WITH BREVE AND DOT BELOW]
		"2090", // [LATIN SUBSCRIPT SMALL LETTER A]
		"2094", // [LATIN SUBSCRIPT SMALL LETTER SCHWA]
		"24D0", // [CIRCLED LATIN SMALL LETTER A]
		"2C65", // [LATIN SMALL LETTER A WITH STROKE]
		"2C6F", // [LATIN CAPITAL LETTER TURNED A]
		"FF41": // [FULLWIDTH LATIN SMALL LETTER A]
		buffer.WriteString("a")
	case "A732": // [LATIN CAPITAL LETTER AA]
		buffer.WriteString("A")
		buffer.WriteString("A")
	case "C6", // [LATIN CAPITAL LETTER AE]
		"1E2",  // [LATIN CAPITAL LETTER AE WITH MACRON]
		"1FC",  // [LATIN CAPITAL LETTER AE WITH ACUTE]
		"1D01": // [LATIN LETTER SMALL CAPITAL AE]
		buffer.WriteString("A")
		buffer.WriteString("E")
	case "A734": // [LATIN CAPITAL LETTER AO]
		buffer.WriteString("A")
		buffer.WriteString("O")
	case "A736": // [LATIN CAPITAL LETTER AU]
		buffer.WriteString("A")
		buffer.WriteString("U")
	case "A738", // [LATIN CAPITAL LETTER AV]
		"A73A": // [LATIN CAPITAL LETTER AV WITH HORIZONTAL BAR]
		buffer.WriteString("A")
		buffer.WriteString("V")
	case "A73C": // [LATIN CAPITAL LETTER AY]
		buffer.WriteString("A")
		buffer.WriteString("Y")
	case "249C": // [PARENTHESIZED LATIN SMALL LETTER A]
		buffer.WriteString("(")
		buffer.WriteString("a")
		buffer.WriteString(")")
	case "A733": // [LATIN SMALL LETTER AA]
		buffer.WriteString("a")
		buffer.WriteString("a")
	case "E6", // [LATIN SMALL LETTER AE]
		"1E3",  // [LATIN SMALL LETTER AE WITH MACRON]
		"1FD",  // [LATIN SMALL LETTER AE WITH ACUTE]
		"1D02": // [LATIN SMALL LETTER TURNED AE]
		buffer.WriteString("a")
		buffer.WriteString("e")
	case "A735": // [LATIN SMALL LETTER AO]
		buffer.WriteString("a")
		buffer.WriteString("o")
	case "A737": // [LATIN SMALL LETTER AU]
		buffer.WriteString("a")
		buffer.WriteString("u")
	case "A739", // [LATIN SMALL LETTER AV]
		"A73B": // [LATIN SMALL LETTER AV WITH HORIZONTAL BAR]
		buffer.WriteString("a")
		buffer.WriteString("v")
	case "A73D": // [LATIN SMALL LETTER AY]
		buffer.WriteString("a")
		buffer.WriteString("y")
	case "181", // [LATIN CAPITAL LETTER B WITH HOOK]
		"182",  // [LATIN CAPITAL LETTER B WITH TOPBAR]
		"243",  // [LATIN CAPITAL LETTER B WITH STROKE]
		"299",  // [LATIN LETTER SMALL CAPITAL B]
		"1D03", // [LATIN LETTER SMALL CAPITAL BARRED B]
		"1E02", // [LATIN CAPITAL LETTER B WITH DOT ABOVE]
		"1E04", // [LATIN CAPITAL LETTER B WITH DOT BELOW]
		"1E06", // [LATIN CAPITAL LETTER B WITH LINE BELOW]
		"24B7", // [CIRCLED LATIN CAPITAL LETTER B]
		"FF22": // [FULLWIDTH LATIN CAPITAL LETTER B]
		buffer.WriteString("B")
	case "180", // [LATIN SMALL LETTER B WITH STROKE]
		"183",  // [LATIN SMALL LETTER B WITH TOPBAR]
		"253",  // [LATIN SMALL LETTER B WITH HOOK]
		"1D6C", // [LATIN SMALL LETTER B WITH MIDDLE TILDE]
		"1D80", // [LATIN SMALL LETTER B WITH PALATAL HOOK]
		"1E03", // [LATIN SMALL LETTER B WITH DOT ABOVE]
		"1E05", // [LATIN SMALL LETTER B WITH DOT BELOW]
		"1E07", // [LATIN SMALL LETTER B WITH LINE BELOW]
		"24D1", // [CIRCLED LATIN SMALL LETTER B]
		"FF42": // [FULLWIDTH LATIN SMALL LETTER B]
		buffer.WriteString("b")
	case "249D": // [PARENTHESIZED LATIN SMALL LETTER B]
		buffer.WriteString("(")
		buffer.WriteString("b")
		buffer.WriteString(")")
	case "C7", // [LATIN CAPITAL LETTER C WITH CEDILLA]
		"106",  // [LATIN CAPITAL LETTER C WITH ACUTE]
		"108",  // [LATIN CAPITAL LETTER C WITH CIRCUMFLEX]
		"10A",  // [LATIN CAPITAL LETTER C WITH DOT ABOVE]
		"10C",  // [LATIN CAPITAL LETTER C WITH CARON]
		"187",  // [LATIN CAPITAL LETTER C WITH HOOK]
		"23B",  // [LATIN CAPITAL LETTER C WITH STROKE]
		"297",  // [LATIN LETTER STRETCHED C]
		"1D04", // [LATIN LETTER SMALL CAPITAL C]
		"1E08", // [LATIN CAPITAL LETTER C WITH CEDILLA AND ACUTE]
		"24B8", // [CIRCLED LATIN CAPITAL LETTER C]
		"FF23": // [FULLWIDTH LATIN CAPITAL LETTER C]
		buffer.WriteString("C")
	case "E7", // [LATIN SMALL LETTER C WITH CEDILLA]
		"107",  // [LATIN SMALL LETTER C WITH ACUTE]
		"109",  // [LATIN SMALL LETTER C WITH CIRCUMFLEX]
		"10B",  // [LATIN SMALL LETTER C WITH DOT ABOVE]
		"10D",  // [LATIN SMALL LETTER C WITH CARON]
		"188",  // [LATIN SMALL LETTER C WITH HOOK]
		"23C",  // [LATIN SMALL LETTER C WITH STROKE]
		"255",  // [LATIN SMALL LETTER C WITH CURL]
		"1E09", // [LATIN SMALL LETTER C WITH CEDILLA AND ACUTE]
		"2184", // [LATIN SMALL LETTER REVERSED C]
		"24D2", // [CIRCLED LATIN SMALL LETTER C]
		"A73E", // [LATIN CAPITAL LETTER REVERSED C WITH DOT]
		"A73F", // [LATIN SMALL LETTER REVERSED C WITH DOT]
		"FF43": // [FULLWIDTH LATIN SMALL LETTER C]
		buffer.WriteString("c")
	case "249E": // [PARENTHESIZED LATIN SMALL LETTER C]
		buffer.WriteString("(")
		buffer.WriteString("c")
		buffer.WriteString(")")
	case "D0", // [LATIN CAPITAL LETTER ETH]
		"10E",  // [LATIN CAPITAL LETTER D WITH CARON]
		"110",  // [LATIN CAPITAL LETTER D WITH STROKE]
		"189",  // [LATIN CAPITAL LETTER AFRICAN D]
		"18A",  // [LATIN CAPITAL LETTER D WITH HOOK]
		"18B",  // [LATIN CAPITAL LETTER D WITH TOPBAR]
		"1D05", // [LATIN LETTER SMALL CAPITAL D]
		"1D06", // [LATIN LETTER SMALL CAPITAL ETH]
		"1E0A", // [LATIN CAPITAL LETTER D WITH DOT ABOVE]
		"1E0C", // [LATIN CAPITAL LETTER D WITH DOT BELOW]
		"1E0E", // [LATIN CAPITAL LETTER D WITH LINE BELOW]
		"1E10", // [LATIN CAPITAL LETTER D WITH CEDILLA]
		"1E12", // [LATIN CAPITAL LETTER D WITH CIRCUMFLEX BELOW]
		"24B9", // [CIRCLED LATIN CAPITAL LETTER D]
		"A779", // [LATIN CAPITAL LETTER INSULAR D]
		"FF24": // [FULLWIDTH LATIN CAPITAL LETTER D]
		buffer.WriteString("D")
	case "F0", // [LATIN SMALL LETTER ETH]
		"10F",  // [LATIN SMALL LETTER D WITH CARON]
		"111",  // [LATIN SMALL LETTER D WITH STROKE]
		"18C",  // [LATIN SMALL LETTER D WITH TOPBAR]
		"221",  // [LATIN SMALL LETTER D WITH CURL]
		"256",  // [LATIN SMALL LETTER D WITH TAIL]
		"257",  // [LATIN SMALL LETTER D WITH HOOK]
		"1D6D", // [LATIN SMALL LETTER D WITH MIDDLE TILDE]
		"1D81", // [LATIN SMALL LETTER D WITH PALATAL HOOK]
		"1D91", // [LATIN SMALL LETTER D WITH HOOK AND TAIL]
		"1E0B", // [LATIN SMALL LETTER D WITH DOT ABOVE]
		"1E0D", // [LATIN SMALL LETTER D WITH DOT BELOW]
		"1E0F", // [LATIN SMALL LETTER D WITH LINE BELOW]
		"1E11", // [LATIN SMALL LETTER D WITH CEDILLA]
		"1E13", // [LATIN SMALL LETTER D WITH CIRCUMFLEX BELOW]
		"24D3", // [CIRCLED LATIN SMALL LETTER D]
		"A77A", // [LATIN SMALL LETTER INSULAR D]
		"FF44": // [FULLWIDTH LATIN SMALL LETTER D]
		buffer.WriteString("d")
	case "1C4", // [LATIN CAPITAL LETTER DZ WITH CARON]
		"1F1": // [LATIN CAPITAL LETTER DZ]
		buffer.WriteString("D")
		buffer.WriteString("Z")
	case "1C5", // [LATIN CAPITAL LETTER D WITH SMALL LETTER Z WITH CARON]
		"1F2": // [LATIN CAPITAL LETTER D WITH SMALL LETTER Z]
		buffer.WriteString("D")
		buffer.WriteString("z")
	case "249F": // [PARENTHESIZED LATIN SMALL LETTER D]
		buffer.WriteString("(")
		buffer.WriteString("d")
		buffer.WriteString(")")
	case "238": // [LATIN SMALL LETTER DB DIGRAPH]
		buffer.WriteString("d")
		buffer.WriteString("b")
	case "1C6", // [LATIN SMALL LETTER DZ WITH CARON]
		"1F3", // [LATIN SMALL LETTER DZ]
		"2A3", // [LATIN SMALL LETTER DZ DIGRAPH]
		"2A5": // [LATIN SMALL LETTER DZ DIGRAPH WITH CURL]
		buffer.WriteString("d")
		buffer.WriteString("z")
	case "C8", // [LATIN CAPITAL LETTER E WITH GRAVE]
		"C9",   // [LATIN CAPITAL LETTER E WITH ACUTE]
		"CA",   // [LATIN CAPITAL LETTER E WITH CIRCUMFLEX]
		"CB",   // [LATIN CAPITAL LETTER E WITH DIAERESIS]
		"112",  // [LATIN CAPITAL LETTER E WITH MACRON]
		"114",  // [LATIN CAPITAL LETTER E WITH BREVE]
		"116",  // [LATIN CAPITAL LETTER E WITH DOT ABOVE]
		"118",  // [LATIN CAPITAL LETTER E WITH OGONEK]
		"11A",  // [LATIN CAPITAL LETTER E WITH CARON]
		"18E",  // [LATIN CAPITAL LETTER REVERSED E]
		"190",  // [LATIN CAPITAL LETTER OPEN E]
		"204",  // [LATIN CAPITAL LETTER E WITH DOUBLE GRAVE]
		"206",  // [LATIN CAPITAL LETTER E WITH INVERTED BREVE]
		"228",  // [LATIN CAPITAL LETTER E WITH CEDILLA]
		"246",  // [LATIN CAPITAL LETTER E WITH STROKE]
		"1D07", // [LATIN LETTER SMALL CAPITAL E]
		"1E14", // [LATIN CAPITAL LETTER E WITH MACRON AND GRAVE]
		"1E16", // [LATIN CAPITAL LETTER E WITH MACRON AND ACUTE]
		"1E18", // [LATIN CAPITAL LETTER E WITH CIRCUMFLEX BELOW]
		"1E1A", // [LATIN CAPITAL LETTER E WITH TILDE BELOW]
		"1E1C", // [LATIN CAPITAL LETTER E WITH CEDILLA AND BREVE]
		"1EB8", // [LATIN CAPITAL LETTER E WITH DOT BELOW]
		"1EBA", // [LATIN CAPITAL LETTER E WITH HOOK ABOVE]
		"1EBC", // [LATIN CAPITAL LETTER E WITH TILDE]
		"1EBE", // [LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND ACUTE]
		"1EC0", // [LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND GRAVE]
		"1EC2", // [LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE]
		"1EC4", // [LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND TILDE]
		"1EC6", // [LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND DOT BELOW]
		"24BA", // [CIRCLED LATIN CAPITAL LETTER E]
		"2C7B", // [LATIN LETTER SMALL CAPITAL TURNED E]
		"FF25": // [FULLWIDTH LATIN CAPITAL LETTER E]
		buffer.WriteString("E")
	case "E8", // [LATIN SMALL LETTER E WITH GRAVE]
		"E9",   // [LATIN SMALL LETTER E WITH ACUTE]
		"EA",   // [LATIN SMALL LETTER E WITH CIRCUMFLEX]
		"EB",   // [LATIN SMALL LETTER E WITH DIAERESIS]
		"113",  // [LATIN SMALL LETTER E WITH MACRON]
		"115",  // [LATIN SMALL LETTER E WITH BREVE]
		"117",  // [LATIN SMALL LETTER E WITH DOT ABOVE]
		"119",  // [LATIN SMALL LETTER E WITH OGONEK]
		"11B",  // [LATIN SMALL LETTER E WITH CARON]
		"1DD",  // [LATIN SMALL LETTER TURNED E]
		"205",  // [LATIN SMALL LETTER E WITH DOUBLE GRAVE]
		"207",  // [LATIN SMALL LETTER E WITH INVERTED BREVE]
		"229",  // [LATIN SMALL LETTER E WITH CEDILLA]
		"247",  // [LATIN SMALL LETTER E WITH STROKE]
		"258",  // [LATIN SMALL LETTER REVERSED E]
		"25B",  // [LATIN SMALL LETTER OPEN E]
		"25C",  // [LATIN SMALL LETTER REVERSED OPEN E]
		"25D",  // [LATIN SMALL LETTER REVERSED OPEN E WITH HOOK]
		"25E",  // [LATIN SMALL LETTER CLOSED REVERSED OPEN E]
		"29A",  // [LATIN SMALL LETTER CLOSED OPEN E]
		"1D08", // [LATIN SMALL LETTER TURNED OPEN E]
		"1D92", // [LATIN SMALL LETTER E WITH RETROFLEX HOOK]
		"1D93", // [LATIN SMALL LETTER OPEN E WITH RETROFLEX HOOK]
		"1D94", // [LATIN SMALL LETTER REVERSED OPEN E WITH RETROFLEX HOOK]
		"1E15", // [LATIN SMALL LETTER E WITH MACRON AND GRAVE]
		"1E17", // [LATIN SMALL LETTER E WITH MACRON AND ACUTE]
		"1E19", // [LATIN SMALL LETTER E WITH CIRCUMFLEX BELOW]
		"1E1B", // [LATIN SMALL LETTER E WITH TILDE BELOW]
		"1E1D", // [LATIN SMALL LETTER E WITH CEDILLA AND BREVE]
		"1EB9", // [LATIN SMALL LETTER E WITH DOT BELOW]
		"1EBB", // [LATIN SMALL LETTER E WITH HOOK ABOVE]
		"1EBD", // [LATIN SMALL LETTER E WITH TILDE]
		"1EBF", // [LATIN SMALL LETTER E WITH CIRCUMFLEX AND ACUTE]
		"1EC1", // [LATIN SMALL LETTER E WITH CIRCUMFLEX AND GRAVE]
		"1EC3", // [LATIN SMALL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE]
		"1EC5", // [LATIN SMALL LETTER E WITH CIRCUMFLEX AND TILDE]
		"1EC7", // [LATIN SMALL LETTER E WITH CIRCUMFLEX AND DOT BELOW]
		"2091", // [LATIN SUBSCRIPT SMALL LETTER E]
		"24D4", // [CIRCLED LATIN SMALL LETTER E]
		"2C78", // [LATIN SMALL LETTER E WITH NOTCH]
		"FF45": // [FULLWIDTH LATIN SMALL LETTER E]
		buffer.WriteString("e")
	case "24A0": // [PARENTHESIZED LATIN SMALL LETTER E]
		buffer.WriteString("(")
		buffer.WriteString("e")
		buffer.WriteString(")")
	case "191", // [LATIN CAPITAL LETTER F WITH HOOK]
		"1E1E", // [LATIN CAPITAL LETTER F WITH DOT ABOVE]
		"24BB", // [CIRCLED LATIN CAPITAL LETTER F]
		"A730", // [LATIN LETTER SMALL CAPITAL F]
		"A77B", // [LATIN CAPITAL LETTER INSULAR F]
		"A7FB", // [LATIN EPIGRAPHIC LETTER REVERSED F]
		"FF26": // [FULLWIDTH LATIN CAPITAL LETTER F]
		buffer.WriteString("F")
	case "192", // [LATIN SMALL LETTER F WITH HOOK]
		"1D6E", // [LATIN SMALL LETTER F WITH MIDDLE TILDE]
		"1D82", // [LATIN SMALL LETTER F WITH PALATAL HOOK]
		"1E1F", // [LATIN SMALL LETTER F WITH DOT ABOVE]
		"1E9B", // [LATIN SMALL LETTER LONG S WITH DOT ABOVE]
		"24D5", // [CIRCLED LATIN SMALL LETTER F]
		"A77C", // [LATIN SMALL LETTER INSULAR F]
		"FF46": // [FULLWIDTH LATIN SMALL LETTER F]
		buffer.WriteString("f")
	case "24A1": // [PARENTHESIZED LATIN SMALL LETTER F]
		buffer.WriteString("(")
		buffer.WriteString("f")
		buffer.WriteString(")")
	case "FB00": // [LATIN SMALL LIGATURE FF]
		buffer.WriteString("f")
		buffer.WriteString("f")
	case "FB03": // [LATIN SMALL LIGATURE FFI]
		buffer.WriteString("f")
		buffer.WriteString("f")
		buffer.WriteString("i")
	case "FB04": // [LATIN SMALL LIGATURE FFL]
		buffer.WriteString("f")
		buffer.WriteString("f")
		buffer.WriteString("l")
	case "FB01": // [LATIN SMALL LIGATURE FI]
		buffer.WriteString("f")
		buffer.WriteString("i")
	case "FB02": // [LATIN SMALL LIGATURE FL]
		buffer.WriteString("f")
		buffer.WriteString("l")
	case "11C", // [LATIN CAPITAL LETTER G WITH CIRCUMFLEX]
		"11E",  // [LATIN CAPITAL LETTER G WITH BREVE]
		"120",  // [LATIN CAPITAL LETTER G WITH DOT ABOVE]
		"122",  // [LATIN CAPITAL LETTER G WITH CEDILLA]
		"193",  // [LATIN CAPITAL LETTER G WITH HOOK]
		"1E4",  // [LATIN CAPITAL LETTER G WITH STROKE]
		"1E5",  // [LATIN SMALL LETTER G WITH STROKE]
		"1E6",  // [LATIN CAPITAL LETTER G WITH CARON]
		"1E7",  // [LATIN SMALL LETTER G WITH CARON]
		"1F4",  // [LATIN CAPITAL LETTER G WITH ACUTE]
		"262",  // [LATIN LETTER SMALL CAPITAL G]
		"29B",  // [LATIN LETTER SMALL CAPITAL G WITH HOOK]
		"1E20", // [LATIN CAPITAL LETTER G WITH MACRON]
		"24BC", // [CIRCLED LATIN CAPITAL LETTER G]
		"A77D", // [LATIN CAPITAL LETTER INSULAR G]
		"A77E", // [LATIN CAPITAL LETTER TURNED INSULAR G]
		"FF27": // [FULLWIDTH LATIN CAPITAL LETTER G]
		buffer.WriteString("G")
	case "11D", // [LATIN SMALL LETTER G WITH CIRCUMFLEX]
		"11F",  // [LATIN SMALL LETTER G WITH BREVE]
		"121",  // [LATIN SMALL LETTER G WITH DOT ABOVE]
		"123",  // [LATIN SMALL LETTER G WITH CEDILLA]
		"1F5",  // [LATIN SMALL LETTER G WITH ACUTE]
		"260",  // [LATIN SMALL LETTER G WITH HOOK]
		"261",  // [LATIN SMALL LETTER SCRIPT G]
		"1D77", // [LATIN SMALL LETTER TURNED G]
		"1D79", // [LATIN SMALL LETTER INSULAR G]
		"1D83", // [LATIN SMALL LETTER G WITH PALATAL HOOK]
		"1E21", // [LATIN SMALL LETTER G WITH MACRON]
		"24D6", // [CIRCLED LATIN SMALL LETTER G]
		"A77F", // [LATIN SMALL LETTER TURNED INSULAR G]
		"FF47": // [FULLWIDTH LATIN SMALL LETTER G]
		buffer.WriteString("g")
	case "24A2": // [PARENTHESIZED LATIN SMALL LETTER G]
		buffer.WriteString("(")
		buffer.WriteString("g")
		buffer.WriteString(")")
	case "124", // [LATIN CAPITAL LETTER H WITH CIRCUMFLEX]
		"126",  // [LATIN CAPITAL LETTER H WITH STROKE]
		"21E",  // [LATIN CAPITAL LETTER H WITH CARON]
		"29C",  // [LATIN LETTER SMALL CAPITAL H]
		"1E22", // [LATIN CAPITAL LETTER H WITH DOT ABOVE]
		"1E24", // [LATIN CAPITAL LETTER H WITH DOT BELOW]
		"1E26", // [LATIN CAPITAL LETTER H WITH DIAERESIS]
		"1E28", // [LATIN CAPITAL LETTER H WITH CEDILLA]
		"1E2A", // [LATIN CAPITAL LETTER H WITH BREVE BELOW]
		"24BD", // [CIRCLED LATIN CAPITAL LETTER H]
		"2C67", // [LATIN CAPITAL LETTER H WITH DESCENDER]
		"2C75", // [LATIN CAPITAL LETTER HALF H]
		"FF28": // [FULLWIDTH LATIN CAPITAL LETTER H]
		buffer.WriteString("H")
	case "125", // [LATIN SMALL LETTER H WITH CIRCUMFLEX]
		"127",  // [LATIN SMALL LETTER H WITH STROKE]
		"21F",  // [LATIN SMALL LETTER H WITH CARON]
		"265",  // [LATIN SMALL LETTER TURNED H]
		"266",  // [LATIN SMALL LETTER H WITH HOOK]
		"2AE",  // [LATIN SMALL LETTER TURNED H WITH FISHHOOK]
		"2AF",  // [LATIN SMALL LETTER TURNED H WITH FISHHOOK AND TAIL]
		"1E23", // [LATIN SMALL LETTER H WITH DOT ABOVE]
		"1E25", // [LATIN SMALL LETTER H WITH DOT BELOW]
		"1E27", // [LATIN SMALL LETTER H WITH DIAERESIS]
		"1E29", // [LATIN SMALL LETTER H WITH CEDILLA]
		"1E2B", // [LATIN SMALL LETTER H WITH BREVE BELOW]
		"1E96", // [LATIN SMALL LETTER H WITH LINE BELOW]
		"24D7", // [CIRCLED LATIN SMALL LETTER H]
		"2C68", // [LATIN SMALL LETTER H WITH DESCENDER]
		"2C76", // [LATIN SMALL LETTER HALF H]
		"FF48": // [FULLWIDTH LATIN SMALL LETTER H]
		buffer.WriteString("h")
	case "1F6": // [LATIN CAPITAL LETTER HWAIR]
		buffer.WriteString("H")
		buffer.WriteString("V")
	case "24A3": // [PARENTHESIZED LATIN SMALL LETTER H]
		buffer.WriteString("(")
		buffer.WriteString("h")
		buffer.WriteString(")")
	case "195": // [LATIN SMALL LETTER HV]
		buffer.WriteString("h")
		buffer.WriteString("v")
	case "CC", // [LATIN CAPITAL LETTER I WITH GRAVE]
		"CD",   // [LATIN CAPITAL LETTER I WITH ACUTE]
		"CE",   // [LATIN CAPITAL LETTER I WITH CIRCUMFLEX]
		"CF",   // [LATIN CAPITAL LETTER I WITH DIAERESIS]
		"128",  // [LATIN CAPITAL LETTER I WITH TILDE]
		"12A",  // [LATIN CAPITAL LETTER I WITH MACRON]
		"12C",  // [LATIN CAPITAL LETTER I WITH BREVE]
		"12E",  // [LATIN CAPITAL LETTER I WITH OGONEK]
		"130",  // [LATIN CAPITAL LETTER I WITH DOT ABOVE]
		"196",  // [LATIN CAPITAL LETTER IOTA]
		"197",  // [LATIN CAPITAL LETTER I WITH STROKE]
		"1CF",  // [LATIN CAPITAL LETTER I WITH CARON]
		"208",  // [LATIN CAPITAL LETTER I WITH DOUBLE GRAVE]
		"20A",  // [LATIN CAPITAL LETTER I WITH INVERTED BREVE]
		"26A",  // [LATIN LETTER SMALL CAPITAL I]
		"1D7B", // [LATIN SMALL CAPITAL LETTER I WITH STROKE]
		"1E2C", // [LATIN CAPITAL LETTER I WITH TILDE BELOW]
		"1E2E", // [LATIN CAPITAL LETTER I WITH DIAERESIS AND ACUTE]
		"1EC8", // [LATIN CAPITAL LETTER I WITH HOOK ABOVE]
		"1ECA", // [LATIN CAPITAL LETTER I WITH DOT BELOW]
		"24BE", // [CIRCLED LATIN CAPITAL LETTER I]
		"A7FE", // [LATIN EPIGRAPHIC LETTER I LONGA]
		"FF29": // [FULLWIDTH LATIN CAPITAL LETTER I]
		buffer.WriteString("I")
	case "EC", // [LATIN SMALL LETTER I WITH GRAVE]
		"ED",   // [LATIN SMALL LETTER I WITH ACUTE]
		"EE",   // [LATIN SMALL LETTER I WITH CIRCUMFLEX]
		"EF",   // [LATIN SMALL LETTER I WITH DIAERESIS]
		"129",  // [LATIN SMALL LETTER I WITH TILDE]
		"12B",  // [LATIN SMALL LETTER I WITH MACRON]
		"12D",  // [LATIN SMALL LETTER I WITH BREVE]
		"12F",  // [LATIN SMALL LETTER I WITH OGONEK]
		"131",  // [LATIN SMALL LETTER DOTLESS I]
		"1D0",  // [LATIN SMALL LETTER I WITH CARON]
		"209",  // [LATIN SMALL LETTER I WITH DOUBLE GRAVE]
		"20B",  // [LATIN SMALL LETTER I WITH INVERTED BREVE]
		"268",  // [LATIN SMALL LETTER I WITH STROKE]
		"1D09", // [LATIN SMALL LETTER TURNED I]
		"1D62", // [LATIN SUBSCRIPT SMALL LETTER I]
		"1D7C", // [LATIN SMALL LETTER IOTA WITH STROKE]
		"1D96", // [LATIN SMALL LETTER I WITH RETROFLEX HOOK]
		"1E2D", // [LATIN SMALL LETTER I WITH TILDE BELOW]
		"1E2F", // [LATIN SMALL LETTER I WITH DIAERESIS AND ACUTE]
		"1EC9", // [LATIN SMALL LETTER I WITH HOOK ABOVE]
		"1ECB", // [LATIN SMALL LETTER I WITH DOT BELOW]
		"2071", // [SUPERSCRIPT LATIN SMALL LETTER I]
		"24D8", // [CIRCLED LATIN SMALL LETTER I]
		"FF49": // [FULLWIDTH LATIN SMALL LETTER I]
		buffer.WriteString("i")
	case "132": // [LATIN CAPITAL LIGATURE IJ]
		buffer.WriteString("I")
		buffer.WriteString("J")
	case "24A4": // [PARENTHESIZED LATIN SMALL LETTER I]
		buffer.WriteString("(")
		buffer.WriteString("i")
		buffer.WriteString(")")
	case "133": // [LATIN SMALL LIGATURE IJ]
		buffer.WriteString("i")
		buffer.WriteString("j")
	case "134", // [LATIN CAPITAL LETTER J WITH CIRCUMFLEX]
		"248",  // [LATIN CAPITAL LETTER J WITH STROKE]
		"1D0A", // [LATIN LETTER SMALL CAPITAL J]
		"24BF", // [CIRCLED LATIN CAPITAL LETTER J]
		"FF2A": // [FULLWIDTH LATIN CAPITAL LETTER J]
		buffer.WriteString("J")
	case "135", // [LATIN SMALL LETTER J WITH CIRCUMFLEX]
		"1F0",  // [LATIN SMALL LETTER J WITH CARON]
		"237",  // [LATIN SMALL LETTER DOTLESS J]
		"249",  // [LATIN SMALL LETTER J WITH STROKE]
		"25F",  // [LATIN SMALL LETTER DOTLESS J WITH STROKE]
		"284",  // [LATIN SMALL LETTER DOTLESS J WITH STROKE AND HOOK]
		"29D",  // [LATIN SMALL LETTER J WITH CROSSED-TAIL]
		"24D9", // [CIRCLED LATIN SMALL LETTER J]
		"2C7C", // [LATIN SUBSCRIPT SMALL LETTER J]
		"FF4A": // [FULLWIDTH LATIN SMALL LETTER J]
		buffer.WriteString("j")
	case "24A5": // [PARENTHESIZED LATIN SMALL LETTER J]
		buffer.WriteString("(")
		buffer.WriteString("j")
		buffer.WriteString(")")
	case "136", // [LATIN CAPITAL LETTER K WITH CEDILLA]
		"198",  // [LATIN CAPITAL LETTER K WITH HOOK]
		"1E8",  // [LATIN CAPITAL LETTER K WITH CARON]
		"1D0B", // [LATIN LETTER SMALL CAPITAL K]
		"1E30", // [LATIN CAPITAL LETTER K WITH ACUTE]
		"1E32", // [LATIN CAPITAL LETTER K WITH DOT BELOW]
		"1E34", // [LATIN CAPITAL LETTER K WITH LINE BELOW]
		"24C0", // [CIRCLED LATIN CAPITAL LETTER K]
		"2C69", // [LATIN CAPITAL LETTER K WITH DESCENDER]
		"A740", // [LATIN CAPITAL LETTER K WITH STROKE]
		"A742", // [LATIN CAPITAL LETTER K WITH DIAGONAL STROKE]
		"A744", // [LATIN CAPITAL LETTER K WITH STROKE AND DIAGONAL STROKE]
		"FF2B": // [FULLWIDTH LATIN CAPITAL LETTER K]
		buffer.WriteString("K")
	case "137", // [LATIN SMALL LETTER K WITH CEDILLA]
		"199",  // [LATIN SMALL LETTER K WITH HOOK]
		"1E9",  // [LATIN SMALL LETTER K WITH CARON]
		"29E",  // [LATIN SMALL LETTER TURNED K]
		"1D84", // [LATIN SMALL LETTER K WITH PALATAL HOOK]
		"1E31", // [LATIN SMALL LETTER K WITH ACUTE]
		"1E33", // [LATIN SMALL LETTER K WITH DOT BELOW]
		"1E35", // [LATIN SMALL LETTER K WITH LINE BELOW]
		"24DA", // [CIRCLED LATIN SMALL LETTER K]
		"2C6A", // [LATIN SMALL LETTER K WITH DESCENDER]
		"A741", // [LATIN SMALL LETTER K WITH STROKE]
		"A743", // [LATIN SMALL LETTER K WITH DIAGONAL STROKE]
		"A745", // [LATIN SMALL LETTER K WITH STROKE AND DIAGONAL STROKE]
		"FF4B": // [FULLWIDTH LATIN SMALL LETTER K]
		buffer.WriteString("k")
	case "24A6": // [PARENTHESIZED LATIN SMALL LETTER K]
		buffer.WriteString("(")
		buffer.WriteString("k")
		buffer.WriteString(")")
	case "139", // [LATIN CAPITAL LETTER L WITH ACUTE]
		"13B",  // [LATIN CAPITAL LETTER L WITH CEDILLA]
		"13D",  // [LATIN CAPITAL LETTER L WITH CARON]
		"13F",  // [LATIN CAPITAL LETTER L WITH MIDDLE DOT]
		"141",  // [LATIN CAPITAL LETTER L WITH STROKE]
		"23D",  // [LATIN CAPITAL LETTER L WITH BAR]
		"29F",  // [LATIN LETTER SMALL CAPITAL L]
		"1D0C", // [LATIN LETTER SMALL CAPITAL L WITH STROKE]
		"1E36", // [LATIN CAPITAL LETTER L WITH DOT BELOW]
		"1E38", // [LATIN CAPITAL LETTER L WITH DOT BELOW AND MACRON]
		"1E3A", // [LATIN CAPITAL LETTER L WITH LINE BELOW]
		"1E3C", // [LATIN CAPITAL LETTER L WITH CIRCUMFLEX BELOW]
		"24C1", // [CIRCLED LATIN CAPITAL LETTER L]
		"2C60", // [LATIN CAPITAL LETTER L WITH DOUBLE BAR]
		"2C62", // [LATIN CAPITAL LETTER L WITH MIDDLE TILDE]
		"A746", // [LATIN CAPITAL LETTER BROKEN L]
		"A748", // [LATIN CAPITAL LETTER L WITH HIGH STROKE]
		"A780", // [LATIN CAPITAL LETTER TURNED L]
		"FF2C": // [FULLWIDTH LATIN CAPITAL LETTER L]
		buffer.WriteString("L")
	case "13A", // [LATIN SMALL LETTER L WITH ACUTE]
		"13C",  // [LATIN SMALL LETTER L WITH CEDILLA]
		"13E",  // [LATIN SMALL LETTER L WITH CARON]
		"140",  // [LATIN SMALL LETTER L WITH MIDDLE DOT]
		"142",  // [LATIN SMALL LETTER L WITH STROKE]
		"19A",  // [LATIN SMALL LETTER L WITH BAR]
		"234",  // [LATIN SMALL LETTER L WITH CURL]
		"26B",  // [LATIN SMALL LETTER L WITH MIDDLE TILDE]
		"26C",  // [LATIN SMALL LETTER L WITH BELT]
		"26D",  // [LATIN SMALL LETTER L WITH RETROFLEX HOOK]
		"1D85", // [LATIN SMALL LETTER L WITH PALATAL HOOK]
		"1E37", // [LATIN SMALL LETTER L WITH DOT BELOW]
		"1E39", // [LATIN SMALL LETTER L WITH DOT BELOW AND MACRON]
		"1E3B", // [LATIN SMALL LETTER L WITH LINE BELOW]
		"1E3D", // [LATIN SMALL LETTER L WITH CIRCUMFLEX BELOW]
		"24DB", // [CIRCLED LATIN SMALL LETTER L]
		"2C61", // [LATIN SMALL LETTER L WITH DOUBLE BAR]
		"A747", // [LATIN SMALL LETTER BROKEN L]
		"A749", // [LATIN SMALL LETTER L WITH HIGH STROKE]
		"A781", // [LATIN SMALL LETTER TURNED L]
		"FF4C": // [FULLWIDTH LATIN SMALL LETTER L]
		buffer.WriteString("l")
	case "1C7": // [LATIN CAPITAL LETTER LJ]
		buffer.WriteString("L")
		buffer.WriteString("J")
	case "1EFA": // [LATIN CAPITAL LETTER MIDDLE-WELSH LL]
		buffer.WriteString("L")
		buffer.WriteString("L")
	case "1C8": // [LATIN CAPITAL LETTER L WITH SMALL LETTER J]
		buffer.WriteString("L")
		buffer.WriteString("j")
	case "24A7": // [PARENTHESIZED LATIN SMALL LETTER L]
		buffer.WriteString("(")
		buffer.WriteString("l")
		buffer.WriteString(")")
	case "1C9": // [LATIN SMALL LETTER LJ]
		buffer.WriteString("l")
		buffer.WriteString("j")
	case "1EFB": // [LATIN SMALL LETTER MIDDLE-WELSH LL]
		buffer.WriteString("l")
		buffer.WriteString("l")
	case "2AA": // [LATIN SMALL LETTER LS DIGRAPH]
		buffer.WriteString("l")
		buffer.WriteString("s")
	case "2AB": // [LATIN SMALL LETTER LZ DIGRAPH]
		buffer.WriteString("l")
		buffer.WriteString("z")
	case "19C", // [LATIN CAPITAL LETTER TURNED M]
		"1D0D", // [LATIN LETTER SMALL CAPITAL M]
		"1E3E", // [LATIN CAPITAL LETTER M WITH ACUTE]
		"1E40", // [LATIN CAPITAL LETTER M WITH DOT ABOVE]
		"1E42", // [LATIN CAPITAL LETTER M WITH DOT BELOW]
		"24C2", // [CIRCLED LATIN CAPITAL LETTER M]
		"2C6E", // [LATIN CAPITAL LETTER M WITH HOOK]
		"A7FD", // [LATIN EPIGRAPHIC LETTER INVERTED M]
		"A7FF", // [LATIN EPIGRAPHIC LETTER ARCHAIC M]
		"FF2D": // [FULLWIDTH LATIN CAPITAL LETTER M]
		buffer.WriteString("M")
	case "26F", // [LATIN SMALL LETTER TURNED M]
		"270",  // [LATIN SMALL LETTER TURNED M WITH LONG LEG]
		"271",  // [LATIN SMALL LETTER M WITH HOOK]
		"1D6F", // [LATIN SMALL LETTER M WITH MIDDLE TILDE]
		"1D86", // [LATIN SMALL LETTER M WITH PALATAL HOOK]
		"1E3F", // [LATIN SMALL LETTER M WITH ACUTE]
		"1E41", // [LATIN SMALL LETTER M WITH DOT ABOVE]
		"1E43", // [LATIN SMALL LETTER M WITH DOT BELOW]
		"24DC", // [CIRCLED LATIN SMALL LETTER M]
		"FF4D": // [FULLWIDTH LATIN SMALL LETTER M]
		buffer.WriteString("m")
	case "24A8": // [PARENTHESIZED LATIN SMALL LETTER M]
		buffer.WriteString("(")
		buffer.WriteString("m")
		buffer.WriteString(")")
	case "D1", // [LATIN CAPITAL LETTER N WITH TILDE]
		"143",  // [LATIN CAPITAL LETTER N WITH ACUTE]
		"145",  // [LATIN CAPITAL LETTER N WITH CEDILLA]
		"147",  // [LATIN CAPITAL LETTER N WITH CARON]
		"14A",  // [LATIN CAPITAL LETTER ENG]
		"19D",  // [LATIN CAPITAL LETTER N WITH LEFT HOOK]
		"1F8",  // [LATIN CAPITAL LETTER N WITH GRAVE]
		"220",  // [LATIN CAPITAL LETTER N WITH LONG RIGHT LEG]
		"274",  // [LATIN LETTER SMALL CAPITAL N]
		"1D0E", // [LATIN LETTER SMALL CAPITAL REVERSED N]
		"1E44", // [LATIN CAPITAL LETTER N WITH DOT ABOVE]
		"1E46", // [LATIN CAPITAL LETTER N WITH DOT BELOW]
		"1E48", // [LATIN CAPITAL LETTER N WITH LINE BELOW]
		"1E4A", // [LATIN CAPITAL LETTER N WITH CIRCUMFLEX BELOW]
		"24C3", // [CIRCLED LATIN CAPITAL LETTER N]
		"FF2E": // [FULLWIDTH LATIN CAPITAL LETTER N]
		buffer.WriteString("N")
	case "F1", // [LATIN SMALL LETTER N WITH TILDE]
		"144",  // [LATIN SMALL LETTER N WITH ACUTE]
		"146",  // [LATIN SMALL LETTER N WITH CEDILLA]
		"148",  // [LATIN SMALL LETTER N WITH CARON]
		"149",  // [LATIN SMALL LETTER N PRECEDED BY APOSTROPHE]
		"14B",  // [LATIN SMALL LETTER ENG]
		"19E",  // [LATIN SMALL LETTER N WITH LONG RIGHT LEG]
		"1F9",  // [LATIN SMALL LETTER N WITH GRAVE]
		"235",  // [LATIN SMALL LETTER N WITH CURL]
		"272",  // [LATIN SMALL LETTER N WITH LEFT HOOK]
		"273",  // [LATIN SMALL LETTER N WITH RETROFLEX HOOK]
		"1D70", // [LATIN SMALL LETTER N WITH MIDDLE TILDE]
		"1D87", // [LATIN SMALL LETTER N WITH PALATAL HOOK]
		"1E45", // [LATIN SMALL LETTER N WITH DOT ABOVE]
		"1E47", // [LATIN SMALL LETTER N WITH DOT BELOW]
		"1E49", // [LATIN SMALL LETTER N WITH LINE BELOW]
		"1E4B", // [LATIN SMALL LETTER N WITH CIRCUMFLEX BELOW]
		"207F", // [SUPERSCRIPT LATIN SMALL LETTER N]
		"24DD", // [CIRCLED LATIN SMALL LETTER N]
		"FF4E": // [FULLWIDTH LATIN SMALL LETTER N]
		buffer.WriteString("n")
	case "1CA": // [LATIN CAPITAL LETTER NJ]
		buffer.WriteString("N")
		buffer.WriteString("J")
	case "1CB": // [LATIN CAPITAL LETTER N WITH SMALL LETTER J]
		buffer.WriteString("N")
		buffer.WriteString("j")
	case "24A9": // [PARENTHESIZED LATIN SMALL LETTER N]
		buffer.WriteString("(")
		buffer.WriteString("n")
		buffer.WriteString(")")
	case "1CC": // [LATIN SMALL LETTER NJ]
		buffer.WriteString("n")
		buffer.WriteString("j")
	case "D2", // [LATIN CAPITAL LETTER O WITH GRAVE]
		"D3",   // [LATIN CAPITAL LETTER O WITH ACUTE]
		"D4",   // [LATIN CAPITAL LETTER O WITH CIRCUMFLEX]
		"D5",   // [LATIN CAPITAL LETTER O WITH TILDE]
		"D6",   // [LATIN CAPITAL LETTER O WITH DIAERESIS]
		"D8",   // [LATIN CAPITAL LETTER O WITH STROKE]
		"14C",  // [LATIN CAPITAL LETTER O WITH MACRON]
		"14E",  // [LATIN CAPITAL LETTER O WITH BREVE]
		"150",  // [LATIN CAPITAL LETTER O WITH DOUBLE ACUTE]
		"186",  // [LATIN CAPITAL LETTER OPEN O]
		"19F",  // [LATIN CAPITAL LETTER O WITH MIDDLE TILDE]
		"1A0",  // [LATIN CAPITAL LETTER O WITH HORN]
		"1D1",  // [LATIN CAPITAL LETTER O WITH CARON]
		"1EA",  // [LATIN CAPITAL LETTER O WITH OGONEK]
		"1EC",  // [LATIN CAPITAL LETTER O WITH OGONEK AND MACRON]
		"1FE",  // [LATIN CAPITAL LETTER O WITH STROKE AND ACUTE]
		"20C",  // [LATIN CAPITAL LETTER O WITH DOUBLE GRAVE]
		"20E",  // [LATIN CAPITAL LETTER O WITH INVERTED BREVE]
		"22A",  // [LATIN CAPITAL LETTER O WITH DIAERESIS AND MACRON]
		"22C",  // [LATIN CAPITAL LETTER O WITH TILDE AND MACRON]
		"22E",  // [LATIN CAPITAL LETTER O WITH DOT ABOVE]
		"230",  // [LATIN CAPITAL LETTER O WITH DOT ABOVE AND MACRON]
		"1D0F", // [LATIN LETTER SMALL CAPITAL O]
		"1D10", // [LATIN LETTER SMALL CAPITAL OPEN O]
		"1E4C", // [LATIN CAPITAL LETTER O WITH TILDE AND ACUTE]
		"1E4E", // [LATIN CAPITAL LETTER O WITH TILDE AND DIAERESIS]
		"1E50", // [LATIN CAPITAL LETTER O WITH MACRON AND GRAVE]
		"1E52", // [LATIN CAPITAL LETTER O WITH MACRON AND ACUTE]
		"1ECC", // [LATIN CAPITAL LETTER O WITH DOT BELOW]
		"1ECE", // [LATIN CAPITAL LETTER O WITH HOOK ABOVE]
		"1ED0", // [LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND ACUTE]
		"1ED2", // [LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND GRAVE]
		"1ED4", // [LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE]
		"1ED6", // [LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND TILDE]
		"1ED8", // [LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND DOT BELOW]
		"1EDA", // [LATIN CAPITAL LETTER O WITH HORN AND ACUTE]
		"1EDC", // [LATIN CAPITAL LETTER O WITH HORN AND GRAVE]
		"1EDE", // [LATIN CAPITAL LETTER O WITH HORN AND HOOK ABOVE]
		"1EE0", // [LATIN CAPITAL LETTER O WITH HORN AND TILDE]
		"1EE2", // [LATIN CAPITAL LETTER O WITH HORN AND DOT BELOW]
		"24C4", // [CIRCLED LATIN CAPITAL LETTER O]
		"A74A", // [LATIN CAPITAL LETTER O WITH LONG STROKE OVERLAY]
		"A74C", // [LATIN CAPITAL LETTER O WITH LOOP]
		"FF2F": // [FULLWIDTH LATIN CAPITAL LETTER O]
		buffer.WriteString("O")
	case "F2", // [LATIN SMALL LETTER O WITH GRAVE]
		"F3",   // [LATIN SMALL LETTER O WITH ACUTE]
		"F4",   // [LATIN SMALL LETTER O WITH CIRCUMFLEX]
		"F5",   // [LATIN SMALL LETTER O WITH TILDE]
		"F6",   // [LATIN SMALL LETTER O WITH DIAERESIS]
		"F8",   // [LATIN SMALL LETTER O WITH STROKE]
		"14D",  // [LATIN SMALL LETTER O WITH MACRON]
		"14F",  // [LATIN SMALL LETTER O WITH BREVE]
		"151",  // [LATIN SMALL LETTER O WITH DOUBLE ACUTE]
		"1A1",  // [LATIN SMALL LETTER O WITH HORN]
		"1D2",  // [LATIN SMALL LETTER O WITH CARON]
		"1EB",  // [LATIN SMALL LETTER O WITH OGONEK]
		"1ED",  // [LATIN SMALL LETTER O WITH OGONEK AND MACRON]
		"1FF",  // [LATIN SMALL LETTER O WITH STROKE AND ACUTE]
		"20D",  // [LATIN SMALL LETTER O WITH DOUBLE GRAVE]
		"20F",  // [LATIN SMALL LETTER O WITH INVERTED BREVE]
		"22B",  // [LATIN SMALL LETTER O WITH DIAERESIS AND MACRON]
		"22D",  // [LATIN SMALL LETTER O WITH TILDE AND MACRON]
		"22F",  // [LATIN SMALL LETTER O WITH DOT ABOVE]
		"231",  // [LATIN SMALL LETTER O WITH DOT ABOVE AND MACRON]
		"254",  // [LATIN SMALL LETTER OPEN O]
		"275",  // [LATIN SMALL LETTER BARRED O]
		"1D16", // [LATIN SMALL LETTER TOP HALF O]
		"1D17", // [LATIN SMALL LETTER BOTTOM HALF O]
		"1D97", // [LATIN SMALL LETTER OPEN O WITH RETROFLEX HOOK]
		"1E4D", // [LATIN SMALL LETTER O WITH TILDE AND ACUTE]
		"1E4F", // [LATIN SMALL LETTER O WITH TILDE AND DIAERESIS]
		"1E51", // [LATIN SMALL LETTER O WITH MACRON AND GRAVE]
		"1E53", // [LATIN SMALL LETTER O WITH MACRON AND ACUTE]
		"1ECD", // [LATIN SMALL LETTER O WITH DOT BELOW]
		"1ECF", // [LATIN SMALL LETTER O WITH HOOK ABOVE]
		"1ED1", // [LATIN SMALL LETTER O WITH CIRCUMFLEX AND ACUTE]
		"1ED3", // [LATIN SMALL LETTER O WITH CIRCUMFLEX AND GRAVE]
		"1ED5", // [LATIN SMALL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE]
		"1ED7", // [LATIN SMALL LETTER O WITH CIRCUMFLEX AND TILDE]
		"1ED9", // [LATIN SMALL LETTER O WITH CIRCUMFLEX AND DOT BELOW]
		"1EDB", // [LATIN SMALL LETTER O WITH HORN AND ACUTE]
		"1EDD", // [LATIN SMALL LETTER O WITH HORN AND GRAVE]
		"1EDF", // [LATIN SMALL LETTER O WITH HORN AND HOOK ABOVE]
		"1EE1", // [LATIN SMALL LETTER O WITH HORN AND TILDE]
		"1EE3", // [LATIN SMALL LETTER O WITH HORN AND DOT BELOW]
		"2092", // [LATIN SUBSCRIPT SMALL LETTER O]
		"24DE", // [CIRCLED LATIN SMALL LETTER O]
		"2C7A", // [LATIN SMALL LETTER O WITH LOW RING INSIDE]
		"A74B", // [LATIN SMALL LETTER O WITH LONG STROKE OVERLAY]
		"A74D", // [LATIN SMALL LETTER O WITH LOOP]
		"FF4F": // [FULLWIDTH LATIN SMALL LETTER O]
		buffer.WriteString("o")
	case "152", // [LATIN CAPITAL LIGATURE OE]
		"276": // [LATIN LETTER SMALL CAPITAL OE]
		buffer.WriteString("O")
		buffer.WriteString("E")
	case "A74E": // [LATIN CAPITAL LETTER OO]
		buffer.WriteString("O")
		buffer.WriteString("O")
	case "222", // [LATIN CAPITAL LETTER OU]
		"1D15": // [LATIN LETTER SMALL CAPITAL OU]
		buffer.WriteString("O")
		buffer.WriteString("U")
	case "24AA": // [PARENTHESIZED LATIN SMALL LETTER O]
		buffer.WriteString("(")
		buffer.WriteString("o")
		buffer.WriteString(")")
	case "153", // [LATIN SMALL LIGATURE OE]
		"1D14": // [LATIN SMALL LETTER TURNED OE]
		buffer.WriteString("o")
		buffer.WriteString("e")
	case "A74F": // [LATIN SMALL LETTER OO]
		buffer.WriteString("o")
		buffer.WriteString("o")
	case "223": // [LATIN SMALL LETTER OU]
		buffer.WriteString("o")
		buffer.WriteString("u")
	case "1A4", // [LATIN CAPITAL LETTER P WITH HOOK]
		"1D18", // [LATIN LETTER SMALL CAPITAL P]
		"1E54", // [LATIN CAPITAL LETTER P WITH ACUTE]
		"1E56", // [LATIN CAPITAL LETTER P WITH DOT ABOVE]
		"24C5", // [CIRCLED LATIN CAPITAL LETTER P]
		"2C63", // [LATIN CAPITAL LETTER P WITH STROKE]
		"A750", // [LATIN CAPITAL LETTER P WITH STROKE THROUGH DESCENDER]
		"A752", // [LATIN CAPITAL LETTER P WITH FLOURISH]
		"A754", // [LATIN CAPITAL LETTER P WITH SQUIRREL TAIL]
		"FF30": // [FULLWIDTH LATIN CAPITAL LETTER P]
		buffer.WriteString("P")
	case "1A5", // [LATIN SMALL LETTER P WITH HOOK]
		"1D71", // [LATIN SMALL LETTER P WITH MIDDLE TILDE]
		"1D7D", // [LATIN SMALL LETTER P WITH STROKE]
		"1D88", // [LATIN SMALL LETTER P WITH PALATAL HOOK]
		"1E55", // [LATIN SMALL LETTER P WITH ACUTE]
		"1E57", // [LATIN SMALL LETTER P WITH DOT ABOVE]
		"24DF", // [CIRCLED LATIN SMALL LETTER P]
		"A751", // [LATIN SMALL LETTER P WITH STROKE THROUGH DESCENDER]
		"A753", // [LATIN SMALL LETTER P WITH FLOURISH]
		"A755", // [LATIN SMALL LETTER P WITH SQUIRREL TAIL]
		"A7FC", // [LATIN EPIGRAPHIC LETTER REVERSED P]
		"FF50": // [FULLWIDTH LATIN SMALL LETTER P]
		buffer.WriteString("p")
	case "24AB": // [PARENTHESIZED LATIN SMALL LETTER P]
		buffer.WriteString("(")
		buffer.WriteString("p")
		buffer.WriteString(")")
	case "24A", // [LATIN CAPITAL LETTER SMALL Q WITH HOOK TAIL]
		"24C6", // [CIRCLED LATIN CAPITAL LETTER Q]
		"A756", // [LATIN CAPITAL LETTER Q WITH STROKE THROUGH DESCENDER]
		"A758", // [LATIN CAPITAL LETTER Q WITH DIAGONAL STROKE]
		"FF31": // [FULLWIDTH LATIN CAPITAL LETTER Q]
		buffer.WriteString("Q")
	case "138", // [LATIN SMALL LETTER KRA]
		"24B",  // [LATIN SMALL LETTER Q WITH HOOK TAIL]
		"2A0",  // [LATIN SMALL LETTER Q WITH HOOK]
		"24E0", // [CIRCLED LATIN SMALL LETTER Q]
		"A757", // [LATIN SMALL LETTER Q WITH STROKE THROUGH DESCENDER]
		"A759", // [LATIN SMALL LETTER Q WITH DIAGONAL STROKE]
		"FF51": // [FULLWIDTH LATIN SMALL LETTER Q]
		buffer.WriteString("q")
	case "24AC": // [PARENTHESIZED LATIN SMALL LETTER Q]
		buffer.WriteString("(")
		buffer.WriteString("q")
		buffer.WriteString(")")
	case "239": // [LATIN SMALL LETTER QP DIGRAPH]
		buffer.WriteString("q")
		buffer.WriteString("p")
	case "154", // [LATIN CAPITAL LETTER R WITH ACUTE]
		"156",  // [LATIN CAPITAL LETTER R WITH CEDILLA]
		"158",  // [LATIN CAPITAL LETTER R WITH CARON]
		"210",  // [LATIN CAPITAL LETTER R WITH DOUBLE GRAVE]
		"212",  // [LATIN CAPITAL LETTER R WITH INVERTED BREVE]
		"24C",  // [LATIN CAPITAL LETTER R WITH STROKE]
		"280",  // [LATIN LETTER SMALL CAPITAL R]
		"281",  // [LATIN LETTER SMALL CAPITAL INVERTED R]
		"1D19", // [LATIN LETTER SMALL CAPITAL REVERSED R]
		"1D1A", // [LATIN LETTER SMALL CAPITAL TURNED R]
		"1E58", // [LATIN CAPITAL LETTER R WITH DOT ABOVE]
		"1E5A", // [LATIN CAPITAL LETTER R WITH DOT BELOW]
		"1E5C", // [LATIN CAPITAL LETTER R WITH DOT BELOW AND MACRON]
		"1E5E", // [LATIN CAPITAL LETTER R WITH LINE BELOW]
		"24C7", // [CIRCLED LATIN CAPITAL LETTER R]
		"2C64", // [LATIN CAPITAL LETTER R WITH TAIL]
		"A75A", // [LATIN CAPITAL LETTER R ROTUNDA]
		"A782", // [LATIN CAPITAL LETTER INSULAR R]
		"FF32": // [FULLWIDTH LATIN CAPITAL LETTER R]
		buffer.WriteString("R")
	case "155", // [LATIN SMALL LETTER R WITH ACUTE]
		"157",  // [LATIN SMALL LETTER R WITH CEDILLA]
		"159",  // [LATIN SMALL LETTER R WITH CARON]
		"211",  // [LATIN SMALL LETTER R WITH DOUBLE GRAVE]
		"213",  // [LATIN SMALL LETTER R WITH INVERTED BREVE]
		"24D",  // [LATIN SMALL LETTER R WITH STROKE]
		"27C",  // [LATIN SMALL LETTER R WITH LONG LEG]
		"27D",  // [LATIN SMALL LETTER R WITH TAIL]
		"27E",  // [LATIN SMALL LETTER R WITH FISHHOOK]
		"27F",  // [LATIN SMALL LETTER REVERSED R WITH FISHHOOK]
		"1D63", // [LATIN SUBSCRIPT SMALL LETTER R]
		"1D72", // [LATIN SMALL LETTER R WITH MIDDLE TILDE]
		"1D73", // [LATIN SMALL LETTER R WITH FISHHOOK AND MIDDLE TILDE]
		"1D89", // [LATIN SMALL LETTER R WITH PALATAL HOOK]
		"1E59", // [LATIN SMALL LETTER R WITH DOT ABOVE]
		"1E5B", // [LATIN SMALL LETTER R WITH DOT BELOW]
		"1E5D", // [LATIN SMALL LETTER R WITH DOT BELOW AND MACRON]
		"1E5F", // [LATIN SMALL LETTER R WITH LINE BELOW]
		"24E1", // [CIRCLED LATIN SMALL LETTER R]
		"A75B", // [LATIN SMALL LETTER R ROTUNDA]
		"A783", // [LATIN SMALL LETTER INSULAR R]
		"FF52": // [FULLWIDTH LATIN SMALL LETTER R]
		buffer.WriteString("r")
	case "24AD": // [PARENTHESIZED LATIN SMALL LETTER R]
		buffer.WriteString("(")
		buffer.WriteString("r")
		buffer.WriteString(")")
	case "15A", // [LATIN CAPITAL LETTER S WITH ACUTE]
		"15C",  // [LATIN CAPITAL LETTER S WITH CIRCUMFLEX]
		"15E",  // [LATIN CAPITAL LETTER S WITH CEDILLA]
		"160",  // [LATIN CAPITAL LETTER S WITH CARON]
		"218",  // [LATIN CAPITAL LETTER S WITH COMMA BELOW]
		"1E60", // [LATIN CAPITAL LETTER S WITH DOT ABOVE]
		"1E62", // [LATIN CAPITAL LETTER S WITH DOT BELOW]
		"1E64", // [LATIN CAPITAL LETTER S WITH ACUTE AND DOT ABOVE]
		"1E66", // [LATIN CAPITAL LETTER S WITH CARON AND DOT ABOVE]
		"1E68", // [LATIN CAPITAL LETTER S WITH DOT BELOW AND DOT ABOVE]
		"24C8", // [CIRCLED LATIN CAPITAL LETTER S]
		"A731", // [LATIN LETTER SMALL CAPITAL S]
		"A785", // [LATIN SMALL LETTER INSULAR S]
		"FF33": // [FULLWIDTH LATIN CAPITAL LETTER S]
		buffer.WriteString("S")
	case "15B", // [LATIN SMALL LETTER S WITH ACUTE]
		"15D",  // [LATIN SMALL LETTER S WITH CIRCUMFLEX]
		"15F",  // [LATIN SMALL LETTER S WITH CEDILLA]
		"161",  // [LATIN SMALL LETTER S WITH CARON]
		"17F",  // [LATIN SMALL LETTER LONG S]
		"219",  // [LATIN SMALL LETTER S WITH COMMA BELOW]
		"23F",  // [LATIN SMALL LETTER S WITH SWASH TAIL]
		"282",  // [LATIN SMALL LETTER S WITH HOOK]
		"1D74", // [LATIN SMALL LETTER S WITH MIDDLE TILDE]
		"1D8A", // [LATIN SMALL LETTER S WITH PALATAL HOOK]
		"1E61", // [LATIN SMALL LETTER S WITH DOT ABOVE]
		"1E63", // [LATIN SMALL LETTER S WITH DOT BELOW]
		"1E65", // [LATIN SMALL LETTER S WITH ACUTE AND DOT ABOVE]
		"1E67", // [LATIN SMALL LETTER S WITH CARON AND DOT ABOVE]
		"1E69", // [LATIN SMALL LETTER S WITH DOT BELOW AND DOT ABOVE]
		"1E9C", // [LATIN SMALL LETTER LONG S WITH DIAGONAL STROKE]
		"1E9D", // [LATIN SMALL LETTER LONG S WITH HIGH STROKE]
		"24E2", // [CIRCLED LATIN SMALL LETTER S]
		"A784", // [LATIN CAPITAL LETTER INSULAR S]
		"FF53": // [FULLWIDTH LATIN SMALL LETTER S]
		buffer.WriteString("s")
	case "1E9E": // [LATIN CAPITAL LETTER SHARP S]
		buffer.WriteString("S")
		buffer.WriteString("S")
	case "24AE": // [PARENTHESIZED LATIN SMALL LETTER S]
		buffer.WriteString("(")
		buffer.WriteString("s")
		buffer.WriteString(")")
	case "DF": // [LATIN SMALL LETTER SHARP S]
		buffer.WriteString("s")
		buffer.WriteString("s")
	case "FB06": // [LATIN SMALL LIGATURE ST]
		buffer.WriteString("s")
		buffer.WriteString("t")
	case "162", // [LATIN CAPITAL LETTER T WITH CEDILLA]
		"164",  // [LATIN CAPITAL LETTER T WITH CARON]
		"166",  // [LATIN CAPITAL LETTER T WITH STROKE]
		"1AC",  // [LATIN CAPITAL LETTER T WITH HOOK]
		"1AE",  // [LATIN CAPITAL LETTER T WITH RETROFLEX HOOK]
		"21A",  // [LATIN CAPITAL LETTER T WITH COMMA BELOW]
		"23E",  // [LATIN CAPITAL LETTER T WITH DIAGONAL STROKE]
		"1D1B", // [LATIN LETTER SMALL CAPITAL T]
		"1E6A", // [LATIN CAPITAL LETTER T WITH DOT ABOVE]
		"1E6C", // [LATIN CAPITAL LETTER T WITH DOT BELOW]
		"1E6E", // [LATIN CAPITAL LETTER T WITH LINE BELOW]
		"1E70", // [LATIN CAPITAL LETTER T WITH CIRCUMFLEX BELOW]
		"24C9", // [CIRCLED LATIN CAPITAL LETTER T]
		"A786", // [LATIN CAPITAL LETTER INSULAR T]
		"FF34": // [FULLWIDTH LATIN CAPITAL LETTER T]
		buffer.WriteString("T")
	case "163", // [LATIN SMALL LETTER T WITH CEDILLA]
		"165",  // [LATIN SMALL LETTER T WITH CARON]
		"167",  // [LATIN SMALL LETTER T WITH STROKE]
		"1AB",  // [LATIN SMALL LETTER T WITH PALATAL HOOK]
		"1AD",  // [LATIN SMALL LETTER T WITH HOOK]
		"21B",  // [LATIN SMALL LETTER T WITH COMMA BELOW]
		"236",  // [LATIN SMALL LETTER T WITH CURL]
		"287",  // [LATIN SMALL LETTER TURNED T]
		"288",  // [LATIN SMALL LETTER T WITH RETROFLEX HOOK]
		"1D75", // [LATIN SMALL LETTER T WITH MIDDLE TILDE]
		"1E6B", // [LATIN SMALL LETTER T WITH DOT ABOVE]
		"1E6D", // [LATIN SMALL LETTER T WITH DOT BELOW]
		"1E6F", // [LATIN SMALL LETTER T WITH LINE BELOW]
		"1E71", // [LATIN SMALL LETTER T WITH CIRCUMFLEX BELOW]
		"1E97", // [LATIN SMALL LETTER T WITH DIAERESIS]
		"24E3", // [CIRCLED LATIN SMALL LETTER T]
		"2C66", // [LATIN SMALL LETTER T WITH DIAGONAL STROKE]
		"FF54": // [FULLWIDTH LATIN SMALL LETTER T]
		buffer.WriteString("t")
	case "DE", // [LATIN CAPITAL LETTER THORN]
		"A766": // [LATIN CAPITAL LETTER THORN WITH STROKE THROUGH DESCENDER]
		buffer.WriteString("T")
		buffer.WriteString("H")
	case "A728": // [LATIN CAPITAL LETTER TZ]
		buffer.WriteString("T")
		buffer.WriteString("Z")
	case "24AF": // [PARENTHESIZED LATIN SMALL LETTER T]
		buffer.WriteString("(")
		buffer.WriteString("t")
		buffer.WriteString(")")
	case "2A8": // [LATIN SMALL LETTER TC DIGRAPH WITH CURL]
		buffer.WriteString("t")
		buffer.WriteString("c")
	case "FE", // [LATIN SMALL LETTER THORN]
		"1D7A", // [LATIN SMALL LETTER TH WITH STRIKETHROUGH]
		"A767": // [LATIN SMALL LETTER THORN WITH STROKE THROUGH DESCENDER]
		buffer.WriteString("t")
		buffer.WriteString("h")
	case "2A6": // [LATIN SMALL LETTER TS DIGRAPH]
		buffer.WriteString("t")
		buffer.WriteString("s")
	case "A729": // [LATIN SMALL LETTER TZ]
		buffer.WriteString("t")
		buffer.WriteString("z")
	case "D9", // [LATIN CAPITAL LETTER U WITH GRAVE]
		"DA",   // [LATIN CAPITAL LETTER U WITH ACUTE]
		"DB",   // [LATIN CAPITAL LETTER U WITH CIRCUMFLEX]
		"DC",   // [LATIN CAPITAL LETTER U WITH DIAERESIS]
		"168",  // [LATIN CAPITAL LETTER U WITH TILDE]
		"16A",  // [LATIN CAPITAL LETTER U WITH MACRON]
		"16C",  // [LATIN CAPITAL LETTER U WITH BREVE]
		"16E",  // [LATIN CAPITAL LETTER U WITH RING ABOVE]
		"170",  // [LATIN CAPITAL LETTER U WITH DOUBLE ACUTE]
		"172",  // [LATIN CAPITAL LETTER U WITH OGONEK]
		"1AF",  // [LATIN CAPITAL LETTER U WITH HORN]
		"1D3",  // [LATIN CAPITAL LETTER U WITH CARON]
		"1D5",  // [LATIN CAPITAL LETTER U WITH DIAERESIS AND MACRON]
		"1D7",  // [LATIN CAPITAL LETTER U WITH DIAERESIS AND ACUTE]
		"1D9",  // [LATIN CAPITAL LETTER U WITH DIAERESIS AND CARON]
		"1DB",  // [LATIN CAPITAL LETTER U WITH DIAERESIS AND GRAVE]
		"214",  // [LATIN CAPITAL LETTER U WITH DOUBLE GRAVE]
		"216",  // [LATIN CAPITAL LETTER U WITH INVERTED BREVE]
		"244",  // [LATIN CAPITAL LETTER U BAR]
		"1D1C", // [LATIN LETTER SMALL CAPITAL U]
		"1D7E", // [LATIN SMALL CAPITAL LETTER U WITH STROKE]
		"1E72", // [LATIN CAPITAL LETTER U WITH DIAERESIS BELOW]
		"1E74", // [LATIN CAPITAL LETTER U WITH TILDE BELOW]
		"1E76", // [LATIN CAPITAL LETTER U WITH CIRCUMFLEX BELOW]
		"1E78", // [LATIN CAPITAL LETTER U WITH TILDE AND ACUTE]
		"1E7A", // [LATIN CAPITAL LETTER U WITH MACRON AND DIAERESIS]
		"1EE4", // [LATIN CAPITAL LETTER U WITH DOT BELOW]
		"1EE6", // [LATIN CAPITAL LETTER U WITH HOOK ABOVE]
		"1EE8", // [LATIN CAPITAL LETTER U WITH HORN AND ACUTE]
		"1EEA", // [LATIN CAPITAL LETTER U WITH HORN AND GRAVE]
		"1EEC", // [LATIN CAPITAL LETTER U WITH HORN AND HOOK ABOVE]
		"1EEE", // [LATIN CAPITAL LETTER U WITH HORN AND TILDE]
		"1EF0", // [LATIN CAPITAL LETTER U WITH HORN AND DOT BELOW]
		"24CA", // [CIRCLED LATIN CAPITAL LETTER U]
		"FF35": // [FULLWIDTH LATIN CAPITAL LETTER U]
		buffer.WriteString("U")
	case "F9", // [LATIN SMALL LETTER U WITH GRAVE]
		"FA",   // [LATIN SMALL LETTER U WITH ACUTE]
		"FB",   // [LATIN SMALL LETTER U WITH CIRCUMFLEX]
		"FC",   // [LATIN SMALL LETTER U WITH DIAERESIS]
		"169",  // [LATIN SMALL LETTER U WITH TILDE]
		"16B",  // [LATIN SMALL LETTER U WITH MACRON]
		"16D",  // [LATIN SMALL LETTER U WITH BREVE]
		"16F",  // [LATIN SMALL LETTER U WITH RING ABOVE]
		"171",  // [LATIN SMALL LETTER U WITH DOUBLE ACUTE]
		"173",  // [LATIN SMALL LETTER U WITH OGONEK]
		"1B0",  // [LATIN SMALL LETTER U WITH HORN]
		"1D4",  // [LATIN SMALL LETTER U WITH CARON]
		"1D6",  // [LATIN SMALL LETTER U WITH DIAERESIS AND MACRON]
		"1D8",  // [LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE]
		"1DA",  // [LATIN SMALL LETTER U WITH DIAERESIS AND CARON]
		"1DC",  // [LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE]
		"215",  // [LATIN SMALL LETTER U WITH DOUBLE GRAVE]
		"217",  // [LATIN SMALL LETTER U WITH INVERTED BREVE]
		"289",  // [LATIN SMALL LETTER U BAR]
		"1D64", // [LATIN SUBSCRIPT SMALL LETTER U]
		"1D99", // [LATIN SMALL LETTER U WITH RETROFLEX HOOK]
		"1E73", // [LATIN SMALL LETTER U WITH DIAERESIS BELOW]
		"1E75", // [LATIN SMALL LETTER U WITH TILDE BELOW]
		"1E77", // [LATIN SMALL LETTER U WITH CIRCUMFLEX BELOW]
		"1E79", // [LATIN SMALL LETTER U WITH TILDE AND ACUTE]
		"1E7B", // [LATIN SMALL LETTER U WITH MACRON AND DIAERESIS]
		"1EE5", // [LATIN SMALL LETTER U WITH DOT BELOW]
		"1EE7", // [LATIN SMALL LETTER U WITH HOOK ABOVE]
		"1EE9", // [LATIN SMALL LETTER U WITH HORN AND ACUTE]
		"1EEB", // [LATIN SMALL LETTER U WITH HORN AND GRAVE]
		"1EED", // [LATIN SMALL LETTER U WITH HORN AND HOOK ABOVE]
		"1EEF", // [LATIN SMALL LETTER U WITH HORN AND TILDE]
		"1EF1", // [LATIN SMALL LETTER U WITH HORN AND DOT BELOW]
		"24E4", // [CIRCLED LATIN SMALL LETTER U]
		"FF55": // [FULLWIDTH LATIN SMALL LETTER U]
		buffer.WriteString("u")
	case "24B0": // [PARENTHESIZED LATIN SMALL LETTER U]
		buffer.WriteString("(")
		buffer.WriteString("u")
		buffer.WriteString(")")
	case "1D6B": // [LATIN SMALL LETTER UE]
		buffer.WriteString("u")
		buffer.WriteString("e")
	case "1B2", // [LATIN CAPITAL LETTER V WITH HOOK]
		"245",  // [LATIN CAPITAL LETTER TURNED V]
		"1D20", // [LATIN LETTER SMALL CAPITAL V]
		"1E7C", // [LATIN CAPITAL LETTER V WITH TILDE]
		"1E7E", // [LATIN CAPITAL LETTER V WITH DOT BELOW]
		"1EFC", // [LATIN CAPITAL LETTER MIDDLE-WELSH V]
		"24CB", // [CIRCLED LATIN CAPITAL LETTER V]
		"A75E", // [LATIN CAPITAL LETTER V WITH DIAGONAL STROKE]
		"A768", // [LATIN CAPITAL LETTER VEND]
		"FF36": // [FULLWIDTH LATIN CAPITAL LETTER V]
		buffer.WriteString("V")
	case "28B", // [LATIN SMALL LETTER V WITH HOOK]
		"28C",  // [LATIN SMALL LETTER TURNED V]
		"1D65", // [LATIN SUBSCRIPT SMALL LETTER V]
		"1D8C", // [LATIN SMALL LETTER V WITH PALATAL HOOK]
		"1E7D", // [LATIN SMALL LETTER V WITH TILDE]
		"1E7F", // [LATIN SMALL LETTER V WITH DOT BELOW]
		"24E5", // [CIRCLED LATIN SMALL LETTER V]
		"2C71", // [LATIN SMALL LETTER V WITH RIGHT HOOK]
		"2C74", // [LATIN SMALL LETTER V WITH CURL]
		"A75F", // [LATIN SMALL LETTER V WITH DIAGONAL STROKE]
		"FF56": // [FULLWIDTH LATIN SMALL LETTER V]
		buffer.WriteString("v")
	case "A760": // [LATIN CAPITAL LETTER VY]
		buffer.WriteString("V")
		buffer.WriteString("Y")
	case "24B1": // [PARENTHESIZED LATIN SMALL LETTER V]
		buffer.WriteString("(")
		buffer.WriteString("v")
		buffer.WriteString(")")
	case "A761": // [LATIN SMALL LETTER VY]
		buffer.WriteString("v")
		buffer.WriteString("y")
	case "174", // [LATIN CAPITAL LETTER W WITH CIRCUMFLEX]
		"1F7",  // [LATIN CAPITAL LETTER WYNN]
		"1D21", // [LATIN LETTER SMALL CAPITAL W]
		"1E80", // [LATIN CAPITAL LETTER W WITH GRAVE]
		"1E82", // [LATIN CAPITAL LETTER W WITH ACUTE]
		"1E84", // [LATIN CAPITAL LETTER W WITH DIAERESIS]
		"1E86", // [LATIN CAPITAL LETTER W WITH DOT ABOVE]
		"1E88", // [LATIN CAPITAL LETTER W WITH DOT BELOW]
		"24CC", // [CIRCLED LATIN CAPITAL LETTER W]
		"2C72", // [LATIN CAPITAL LETTER W WITH HOOK]
		"FF37": // [FULLWIDTH LATIN CAPITAL LETTER W]
		buffer.WriteString("W")
	case "175", // [LATIN SMALL LETTER W WITH CIRCUMFLEX]
		"1BF",  // [LATIN LETTER WYNN]
		"28D",  // [LATIN SMALL LETTER TURNED W]
		"1E81", // [LATIN SMALL LETTER W WITH GRAVE]
		"1E83", // [LATIN SMALL LETTER W WITH ACUTE]
		"1E85", // [LATIN SMALL LETTER W WITH DIAERESIS]
		"1E87", // [LATIN SMALL LETTER W WITH DOT ABOVE]
		"1E89", // [LATIN SMALL LETTER W WITH DOT BELOW]
		"1E98", // [LATIN SMALL LETTER W WITH RING ABOVE]
		"24E6", // [CIRCLED LATIN SMALL LETTER W]
		"2C73", // [LATIN SMALL LETTER W WITH HOOK]
		"FF57": // [FULLWIDTH LATIN SMALL LETTER W]
		buffer.WriteString("w")
	case "24B2": // [PARENTHESIZED LATIN SMALL LETTER W]
		buffer.WriteString("(")
		buffer.WriteString("w")
		buffer.WriteString(")")
	case "1E8A", // [LATIN CAPITAL LETTER X WITH DOT ABOVE]
		"1E8C", // [LATIN CAPITAL LETTER X WITH DIAERESIS]
		"24CD", // [CIRCLED LATIN CAPITAL LETTER X]
		"FF38": // [FULLWIDTH LATIN CAPITAL LETTER X]
		buffer.WriteString("X")
	case "1D8D", // [LATIN SMALL LETTER X WITH PALATAL HOOK]
		"1E8B", // [LATIN SMALL LETTER X WITH DOT ABOVE]
		"1E8D", // [LATIN SMALL LETTER X WITH DIAERESIS]
		"2093", // [LATIN SUBSCRIPT SMALL LETTER X]
		"24E7", // [CIRCLED LATIN SMALL LETTER X]
		"FF58": // [FULLWIDTH LATIN SMALL LETTER X]
		buffer.WriteString("x")
	case "24B3": // [PARENTHESIZED LATIN SMALL LETTER X]
		buffer.WriteString("(")
		buffer.WriteString("x")
		buffer.WriteString(")")
	case "DD", // [LATIN CAPITAL LETTER Y WITH ACUTE]
		"176",  // [LATIN CAPITAL LETTER Y WITH CIRCUMFLEX]
		"178",  // [LATIN CAPITAL LETTER Y WITH DIAERESIS]
		"1B3",  // [LATIN CAPITAL LETTER Y WITH HOOK]
		"232",  // [LATIN CAPITAL LETTER Y WITH MACRON]
		"24E",  // [LATIN CAPITAL LETTER Y WITH STROKE]
		"28F",  // [LATIN LETTER SMALL CAPITAL Y]
		"1E8E", // [LATIN CAPITAL LETTER Y WITH DOT ABOVE]
		"1EF2", // [LATIN CAPITAL LETTER Y WITH GRAVE]
		"1EF4", // [LATIN CAPITAL LETTER Y WITH DOT BELOW]
		"1EF6", // [LATIN CAPITAL LETTER Y WITH HOOK ABOVE]
		"1EF8", // [LATIN CAPITAL LETTER Y WITH TILDE]
		"1EFE", // [LATIN CAPITAL LETTER Y WITH LOOP]
		"24CE", // [CIRCLED LATIN CAPITAL LETTER Y]
		"FF39": // [FULLWIDTH LATIN CAPITAL LETTER Y]
		buffer.WriteString("Y")
	case "FD", // [LATIN SMALL LETTER Y WITH ACUTE]
		"FF",   // [LATIN SMALL LETTER Y WITH DIAERESIS]
		"177",  // [LATIN SMALL LETTER Y WITH CIRCUMFLEX]
		"1B4",  // [LATIN SMALL LETTER Y WITH HOOK]
		"233",  // [LATIN SMALL LETTER Y WITH MACRON]
		"24F",  // [LATIN SMALL LETTER Y WITH STROKE]
		"28E",  // [LATIN SMALL LETTER TURNED Y]
		"1E8F", // [LATIN SMALL LETTER Y WITH DOT ABOVE]
		"1E99", // [LATIN SMALL LETTER Y WITH RING ABOVE]
		"1EF3", // [LATIN SMALL LETTER Y WITH GRAVE]
		"1EF5", // [LATIN SMALL LETTER Y WITH DOT BELOW]
		"1EF7", // [LATIN SMALL LETTER Y WITH HOOK ABOVE]
		"1EF9", // [LATIN SMALL LETTER Y WITH TILDE]
		"1EFF", // [LATIN SMALL LETTER Y WITH LOOP]
		"24E8", // [CIRCLED LATIN SMALL LETTER Y]
		"FF59": // [FULLWIDTH LATIN SMALL LETTER Y]
		buffer.WriteString("y")
	case "24B4": // [PARENTHESIZED LATIN SMALL LETTER Y]
		buffer.WriteString("(")
		buffer.WriteString("y")
		buffer.WriteString(")")
	case "179", // [LATIN CAPITAL LETTER Z WITH ACUTE]
		"17B",  // [LATIN CAPITAL LETTER Z WITH DOT ABOVE]
		"17D",  // [LATIN CAPITAL LETTER Z WITH CARON]
		"1B5",  // [LATIN CAPITAL LETTER Z WITH STROKE]
		"21C",  // [LATIN CAPITAL LETTER YOGH]
		"224",  // [LATIN CAPITAL LETTER Z WITH HOOK]
		"1D22", // [LATIN LETTER SMALL CAPITAL Z]
		"1E90", // [LATIN CAPITAL LETTER Z WITH CIRCUMFLEX]
		"1E92", // [LATIN CAPITAL LETTER Z WITH DOT BELOW]
		"1E94", // [LATIN CAPITAL LETTER Z WITH LINE BELOW]
		"24CF", // [CIRCLED LATIN CAPITAL LETTER Z]
		"2C6B", // [LATIN CAPITAL LETTER Z WITH DESCENDER]
		"A762", // [LATIN CAPITAL LETTER VISIGOTHIC Z]
		"FF3A": // [FULLWIDTH LATIN CAPITAL LETTER Z]
		buffer.WriteString("Z")
	case "17A", // [LATIN SMALL LETTER Z WITH ACUTE]
		"17C",  // [LATIN SMALL LETTER Z WITH DOT ABOVE]
		"17E",  // [LATIN SMALL LETTER Z WITH CARON]
		"1B6",  // [LATIN SMALL LETTER Z WITH STROKE]
		"21D",  // [LATIN SMALL LETTER YOGH]
		"225",  // [LATIN SMALL LETTER Z WITH HOOK]
		"240",  // [LATIN SMALL LETTER Z WITH SWASH TAIL]
		"290",  // [LATIN SMALL LETTER Z WITH RETROFLEX HOOK]
		"291",  // [LATIN SMALL LETTER Z WITH CURL]
		"1D76", // [LATIN SMALL LETTER Z WITH MIDDLE TILDE]
		"1D8E", // [LATIN SMALL LETTER Z WITH PALATAL HOOK]
		"1E91", // [LATIN SMALL LETTER Z WITH CIRCUMFLEX]
		"1E93", // [LATIN SMALL LETTER Z WITH DOT BELOW]
		"1E95", // [LATIN SMALL LETTER Z WITH LINE BELOW]
		"24E9", // [CIRCLED LATIN SMALL LETTER Z]
		"2C6C", // [LATIN SMALL LETTER Z WITH DESCENDER]
		"A763", // [LATIN SMALL LETTER VISIGOTHIC Z]
		"FF5A": // [FULLWIDTH LATIN SMALL LETTER Z]
		buffer.WriteString("z")
	case "24B5": // [PARENTHESIZED LATIN SMALL LETTER Z]
		buffer.WriteString("(")
		buffer.WriteString("z")
		buffer.WriteString(")")
	case "2070", // [SUPERSCRIPT ZERO]
		"2080", // [SUBSCRIPT ZERO]
		"24EA", // [CIRCLED DIGIT ZERO]
		"24FF", // [NEGATIVE CIRCLED DIGIT ZERO]
		"FF10": // [FULLWIDTH DIGIT ZERO]
		buffer.WriteString("0")
	case "B9", // [SUPERSCRIPT ONE]
		"2081", // [SUBSCRIPT ONE]
		"2460", // [CIRCLED DIGIT ONE]
		"24F5", // [DOUBLE CIRCLED DIGIT ONE]
		"2776", // [DINGBAT NEGATIVE CIRCLED DIGIT ONE]
		"2780", // [DINGBAT CIRCLED SANS-SERIF DIGIT ONE]
		"278A", // [DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT ONE]
		"FF11": // [FULLWIDTH DIGIT ONE]
		buffer.WriteString("1")
	case "2488": // [DIGIT ONE FULL STOP]
		buffer.WriteString("1")
		buffer.WriteString(".")
	case "2474": // [PARENTHESIZED DIGIT ONE]
		buffer.WriteString("(")
		buffer.WriteString("1")
		buffer.WriteString(")")
	case "B2", // [SUPERSCRIPT TWO]
		"2082", // [SUBSCRIPT TWO]
		"2461", // [CIRCLED DIGIT TWO]
		"24F6", // [DOUBLE CIRCLED DIGIT TWO]
		"2777", // [DINGBAT NEGATIVE CIRCLED DIGIT TWO]
		"2781", // [DINGBAT CIRCLED SANS-SERIF DIGIT TWO]
		"278B", // [DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT TWO]
		"FF12": // [FULLWIDTH DIGIT TWO]
		buffer.WriteString("2")
	case "2489": // [DIGIT TWO FULL STOP]
		buffer.WriteString("2")
		buffer.WriteString(".")
	case "2475": // [PARENTHESIZED DIGIT TWO]
		buffer.WriteString("(")
		buffer.WriteString("2")
		buffer.WriteString(")")
	case "B3", // [SUPERSCRIPT THREE]
		"2083", // [SUBSCRIPT THREE]
		"2462", // [CIRCLED DIGIT THREE]
		"24F7", // [DOUBLE CIRCLED DIGIT THREE]
		"2778", // [DINGBAT NEGATIVE CIRCLED DIGIT THREE]
		"2782", // [DINGBAT CIRCLED SANS-SERIF DIGIT THREE]
		"278C", // [DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT THREE]
		"FF13": // [FULLWIDTH DIGIT THREE]
		buffer.WriteString("3")
	case "248A": // [DIGIT THREE FULL STOP]
		buffer.WriteString("3")
		buffer.WriteString(".")
	case "2476": // [PARENTHESIZED DIGIT THREE]
		buffer.WriteString("(")
		buffer.WriteString("3")
		buffer.WriteString(")")
	case "2074", // [SUPERSCRIPT FOUR]
		"2084", // [SUBSCRIPT FOUR]
		"2463", // [CIRCLED DIGIT FOUR]
		"24F8", // [DOUBLE CIRCLED DIGIT FOUR]
		"2779", // [DINGBAT NEGATIVE CIRCLED DIGIT FOUR]
		"2783", // [DINGBAT CIRCLED SANS-SERIF DIGIT FOUR]
		"278D", // [DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT FOUR]
		"FF14": // [FULLWIDTH DIGIT FOUR]
		buffer.WriteString("4")
	case "248B": // [DIGIT FOUR FULL STOP]
		buffer.WriteString("4")
		buffer.WriteString(".")
	case "2477": // [PARENTHESIZED DIGIT FOUR]
		buffer.WriteString("(")
		buffer.WriteString("4")
		buffer.WriteString(")")
	case "2075", // [SUPERSCRIPT FIVE]
		"2085", // [SUBSCRIPT FIVE]
		"2464", // [CIRCLED DIGIT FIVE]
		"24F9", // [DOUBLE CIRCLED DIGIT FIVE]
		"277A", // [DINGBAT NEGATIVE CIRCLED DIGIT FIVE]
		"2784", // [DINGBAT CIRCLED SANS-SERIF DIGIT FIVE]
		"278E", // [DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT FIVE]
		"FF15": // [FULLWIDTH DIGIT FIVE]
		buffer.WriteString("5")
	case "248C": // [DIGIT FIVE FULL STOP]
		buffer.WriteString("5")
		buffer.WriteString(".")
	case "2478": // [PARENTHESIZED DIGIT FIVE]
		buffer.WriteString("(")
		buffer.WriteString("5")
		buffer.WriteString(")")
	case "2076", // [SUPERSCRIPT SIX]
		"2086", // [SUBSCRIPT SIX]
		"2465", // [CIRCLED DIGIT SIX]
		"24FA", // [DOUBLE CIRCLED DIGIT SIX]
		"277B", // [DINGBAT NEGATIVE CIRCLED DIGIT SIX]
		"2785", // [DINGBAT CIRCLED SANS-SERIF DIGIT SIX]
		"278F", // [DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT SIX]
		"FF16": // [FULLWIDTH DIGIT SIX]
		buffer.WriteString("6")
	case "248D": // [DIGIT SIX FULL STOP]
		buffer.WriteString("6")
		buffer.WriteString(".")
	case "2479": // [PARENTHESIZED DIGIT SIX]
		buffer.WriteString("(")
		buffer.WriteString("6")
		buffer.WriteString(")")
	case "2077", // [SUPERSCRIPT SEVEN]
		"2087", // [SUBSCRIPT SEVEN]
		"2466", // [CIRCLED DIGIT SEVEN]
		"24FB", // [DOUBLE CIRCLED DIGIT SEVEN]
		"277C", // [DINGBAT NEGATIVE CIRCLED DIGIT SEVEN]
		"2786", // [DINGBAT CIRCLED SANS-SERIF DIGIT SEVEN]
		"2790", // [DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT SEVEN]
		"FF17": // [FULLWIDTH DIGIT SEVEN]
		buffer.WriteString("7")
	case "248E": // [DIGIT SEVEN FULL STOP]
		buffer.WriteString("7")
		buffer.WriteString(".")
	case "247A": // [PARENTHESIZED DIGIT SEVEN]
		buffer.WriteString("(")
		buffer.WriteString("7")
		buffer.WriteString(")")
	case "2078", // [SUPERSCRIPT EIGHT]
		"2088", // [SUBSCRIPT EIGHT]
		"2467", // [CIRCLED DIGIT EIGHT]
		"24FC", // [DOUBLE CIRCLED DIGIT EIGHT]
		"277D", // [DINGBAT NEGATIVE CIRCLED DIGIT EIGHT]
		"2787", // [DINGBAT CIRCLED SANS-SERIF DIGIT EIGHT]
		"2791", // [DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT EIGHT]
		"FF18": // [FULLWIDTH DIGIT EIGHT]
		buffer.WriteString("8")
	case "248F": // [DIGIT EIGHT FULL STOP]
		buffer.WriteString("8")
		buffer.WriteString(".")
	case "247B": // [PARENTHESIZED DIGIT EIGHT]
		buffer.WriteString("(")
		buffer.WriteString("8")
		buffer.WriteString(")")
	case "2079", // [SUPERSCRIPT NINE]
		"2089", // [SUBSCRIPT NINE]
		"2468", // [CIRCLED DIGIT NINE]
		"24FD", // [DOUBLE CIRCLED DIGIT NINE]
		"277E", // [DINGBAT NEGATIVE CIRCLED DIGIT NINE]
		"2788", // [DINGBAT CIRCLED SANS-SERIF DIGIT NINE]
		"2792", // [DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT NINE]
		"FF19": // [FULLWIDTH DIGIT NINE]
		buffer.WriteString("9")
	case "2490": // [DIGIT NINE FULL STOP]
		buffer.WriteString("9")
		buffer.WriteString(".")
	case "247C": // [PARENTHESIZED DIGIT NINE]
		buffer.WriteString("(")
		buffer.WriteString("9")
		buffer.WriteString(")")
	case "2469", // [CIRCLED NUMBER TEN]
		"24FE", // [DOUBLE CIRCLED NUMBER TEN]
		"277F", // [DINGBAT NEGATIVE CIRCLED NUMBER TEN]
		"2789", // [DINGBAT CIRCLED SANS-SERIF NUMBER TEN]
		"2793": // [DINGBAT NEGATIVE CIRCLED SANS-SERIF NUMBER TEN]
		buffer.WriteString("1")
		buffer.WriteString("0")
	case "2491": // [NUMBER TEN FULL STOP]
		buffer.WriteString("1")
		buffer.WriteString("0")
		buffer.WriteString(".")
	case "247D": // [PARENTHESIZED NUMBER TEN]
		buffer.WriteString("(")
		buffer.WriteString("1")
		buffer.WriteString("0")
		buffer.WriteString(")")
	case "246A", // [CIRCLED NUMBER ELEVEN]
		"24EB": // [NEGATIVE CIRCLED NUMBER ELEVEN]
		buffer.WriteString("1")
		buffer.WriteString("1")
	case "2492": // [NUMBER ELEVEN FULL STOP]
		buffer.WriteString("1")
		buffer.WriteString("1")
		buffer.WriteString(".")
	case "247E": // [PARENTHESIZED NUMBER ELEVEN]
		buffer.WriteString("(")
		buffer.WriteString("1")
		buffer.WriteString("1")
		buffer.WriteString(")")
	case "246B", // [CIRCLED NUMBER TWELVE]
		"24EC": // [NEGATIVE CIRCLED NUMBER TWELVE]
		buffer.WriteString("1")
		buffer.WriteString("2")
	case "2493": // [NUMBER TWELVE FULL STOP]
		buffer.WriteString("1")
		buffer.WriteString("2")
		buffer.WriteString(".")
	case "247F": // [PARENTHESIZED NUMBER TWELVE]
		buffer.WriteString("(")
		buffer.WriteString("1")
		buffer.WriteString("2")
		buffer.WriteString(")")
	case "246C", // [CIRCLED NUMBER THIRTEEN]
		"24ED": // [NEGATIVE CIRCLED NUMBER THIRTEEN]
		buffer.WriteString("1")
		buffer.WriteString("3")
	case "2494": // [NUMBER THIRTEEN FULL STOP]
		buffer.WriteString("1")
		buffer.WriteString("3")
		buffer.WriteString(".")
	case "2480": // [PARENTHESIZED NUMBER THIRTEEN]
		buffer.WriteString("(")
		buffer.WriteString("1")
		buffer.WriteString("3")
		buffer.WriteString(")")
	case "246D", // [CIRCLED NUMBER FOURTEEN]
		"24EE": // [NEGATIVE CIRCLED NUMBER FOURTEEN]
		buffer.WriteString("1")
		buffer.WriteString("4")
	case "2495": // [NUMBER FOURTEEN FULL STOP]
		buffer.WriteString("1")
		buffer.WriteString("4")
		buffer.WriteString(".")
	case "2481": // [PARENTHESIZED NUMBER FOURTEEN]
		buffer.WriteString("(")
		buffer.WriteString("1")
		buffer.WriteString("4")
		buffer.WriteString(")")
	case "246E", // [CIRCLED NUMBER FIFTEEN]
		"24EF": // [NEGATIVE CIRCLED NUMBER FIFTEEN]
		buffer.WriteString("1")
		buffer.WriteString("5")
	case "2496": // [NUMBER FIFTEEN FULL STOP]
		buffer.WriteString("1")
		buffer.WriteString("5")
		buffer.WriteString(".")
	case "2482": // [PARENTHESIZED NUMBER FIFTEEN]
		buffer.WriteString("(")
		buffer.WriteString("1")
		buffer.WriteString("5")
		buffer.WriteString(")")
	case "246F", // [CIRCLED NUMBER SIXTEEN]
		"24F0": // [NEGATIVE CIRCLED NUMBER SIXTEEN]
		buffer.WriteString("1")
		buffer.WriteString("6")
	case "2497": // [NUMBER SIXTEEN FULL STOP]
		buffer.WriteString("1")
		buffer.WriteString("6")
		buffer.WriteString(".")
	case "2483": // [PARENTHESIZED NUMBER SIXTEEN]
		buffer.WriteString("(")
		buffer.WriteString("1")
		buffer.WriteString("6")
		buffer.WriteString(")")
	case "2470", // [CIRCLED NUMBER SEVENTEEN]
		"24F1": // [NEGATIVE CIRCLED NUMBER SEVENTEEN]
		buffer.WriteString("1")
		buffer.WriteString("7")
	case "2498": // [NUMBER SEVENTEEN FULL STOP]
		buffer.WriteString("1")
		buffer.WriteString("7")
		buffer.WriteString(".")
	case "2484": // [PARENTHESIZED NUMBER SEVENTEEN]
		buffer.WriteString("(")
		buffer.WriteString("1")
		buffer.WriteString("7")
		buffer.WriteString(")")
	case "2471", // [CIRCLED NUMBER EIGHTEEN]
		"24F2": // [NEGATIVE CIRCLED NUMBER EIGHTEEN]
		buffer.WriteString("1")
		buffer.WriteString("8")
	case "2499": // [NUMBER EIGHTEEN FULL STOP]
		buffer.WriteString("1")
		buffer.WriteString("8")
		buffer.WriteString(".")
	case "2485": // [PARENTHESIZED NUMBER EIGHTEEN]
		buffer.WriteString("(")
		buffer.WriteString("1")
		buffer.WriteString("8")
		buffer.WriteString(")")
	case "2472", // [CIRCLED NUMBER NINETEEN]
		"24F3": // [NEGATIVE CIRCLED NUMBER NINETEEN]
		buffer.WriteString("1")
		buffer.WriteString("9")
	case "249A": // [NUMBER NINETEEN FULL STOP]
		buffer.WriteString("1")
		buffer.WriteString("9")
		buffer.WriteString(".")
	case "2486": // [PARENTHESIZED NUMBER NINETEEN]
		buffer.WriteString("(")
		buffer.WriteString("1")
		buffer.WriteString("9")
		buffer.WriteString(")")
	case "2473", // [CIRCLED NUMBER TWENTY]
		"24F4": // [NEGATIVE CIRCLED NUMBER TWENTY]
		buffer.WriteString("2")
		buffer.WriteString("0")
	case "249B": // [NUMBER TWENTY FULL STOP]
		buffer.WriteString("2")
		buffer.WriteString("0")
		buffer.WriteString(".")
	case "2487": // [PARENTHESIZED NUMBER TWENTY]
		buffer.WriteString("(")
		buffer.WriteString("2")
		buffer.WriteString("0")
		buffer.WriteString(")")
	case "AB", // [LEFT-POINTING DOUBLE ANGLE QUOTATION MARK]
		"BB",   // [RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK]
		"201C", // [LEFT DOUBLE QUOTATION MARK]
		"201D", // [RIGHT DOUBLE QUOTATION MARK]
		"201E", // [DOUBLE LOW-9 QUOTATION MARK]
		"2033", // [DOUBLE PRIME]
		"2036", // [REVERSED DOUBLE PRIME]
		"275D", // [HEAVY DOUBLE TURNED COMMA QUOTATION MARK ORNAMENT]
		"275E", // [HEAVY DOUBLE COMMA QUOTATION MARK ORNAMENT]
		"276E", // [HEAVY LEFT-POINTING ANGLE QUOTATION MARK ORNAMENT]
		"276F", // [HEAVY RIGHT-POINTING ANGLE QUOTATION MARK ORNAMENT]
		"FF02": // [FULLWIDTH QUOTATION MARK]
		buffer.WriteString("\"")
	case "2018", // [LEFT SINGLE QUOTATION MARK]
		"2019", // [RIGHT SINGLE QUOTATION MARK]
		"201A", // [SINGLE LOW-9 QUOTATION MARK]
		"201B", // [SINGLE HIGH-REVERSED-9 QUOTATION MARK]
		"2032", // [PRIME]
		"2035", // [REVERSED PRIME]
		"2039", // [SINGLE LEFT-POINTING ANGLE QUOTATION MARK]
		"203A", // [SINGLE RIGHT-POINTING ANGLE QUOTATION MARK]
		"275B", // [HEAVY SINGLE TURNED COMMA QUOTATION MARK ORNAMENT]
		"275C", // [HEAVY SINGLE COMMA QUOTATION MARK ORNAMENT]
		"FF07": // [FULLWIDTH APOSTROPHE]
		buffer.WriteString("'")
	case "2010", // [HYPHEN]
		"2011", // [NON-BREAKING HYPHEN]
		"2012", // [FIGURE DASH]
		"2013", // [EN DASH]
		"2014", // [EM DASH]
		"207B", // [SUPERSCRIPT MINUS]
		"208B", // [SUBSCRIPT MINUS]
		"FF0D": // [FULLWIDTH HYPHEN-MINUS]
		buffer.WriteString("-")
	case "2045", // [LEFT SQUARE BRACKET WITH QUILL]
		"2772", // [LIGHT LEFT TORTOISE SHELL BRACKET ORNAMENT]
		"FF3B": // [FULLWIDTH LEFT SQUARE BRACKET]
		buffer.WriteString("[")
	case "2046", // [RIGHT SQUARE BRACKET WITH QUILL]
		"2773", // [LIGHT RIGHT TORTOISE SHELL BRACKET ORNAMENT]
		"FF3D": // [FULLWIDTH RIGHT SQUARE BRACKET]
		buffer.WriteString("]")
	case "207D", // [SUPERSCRIPT LEFT PARENTHESIS]
		"208D", // [SUBSCRIPT LEFT PARENTHESIS]
		"2768", // [MEDIUM LEFT PARENTHESIS ORNAMENT]
		"276A", // [MEDIUM FLATTENED LEFT PARENTHESIS ORNAMENT]
		"FF08": // [FULLWIDTH LEFT PARENTHESIS]
		buffer.WriteString("(")
	case "2E28": // [LEFT DOUBLE PARENTHESIS]
		buffer.WriteString("(")
		buffer.WriteString("(")
	case "207E", // [SUPERSCRIPT RIGHT PARENTHESIS]
		"208E", // [SUBSCRIPT RIGHT PARENTHESIS]
		"2769", // [MEDIUM RIGHT PARENTHESIS ORNAMENT]
		"276B", // [MEDIUM FLATTENED RIGHT PARENTHESIS ORNAMENT]
		"FF09": // [FULLWIDTH RIGHT PARENTHESIS]
		buffer.WriteString(")")
	case "2E29": // [RIGHT DOUBLE PARENTHESIS]
		buffer.WriteString(")")
		buffer.WriteString(")")
	case "276C", // [MEDIUM LEFT-POINTING ANGLE BRACKET ORNAMENT]
		"2770", // [HEAVY LEFT-POINTING ANGLE BRACKET ORNAMENT]
		"FF1C": // [FULLWIDTH LESS-THAN SIGN]
		buffer.WriteString("<")
	case "276D", // [MEDIUM RIGHT-POINTING ANGLE BRACKET ORNAMENT]
		"2771", // [HEAVY RIGHT-POINTING ANGLE BRACKET ORNAMENT]
		"FF1E": // [FULLWIDTH GREATER-THAN SIGN]
		buffer.WriteString(">")
	case "2774", // [MEDIUM LEFT CURLY BRACKET ORNAMENT]
		"FF5B": // [FULLWIDTH LEFT CURLY BRACKET]
		buffer.WriteString("{")
	case "2775", // [MEDIUM RIGHT CURLY BRACKET ORNAMENT]
		"FF5D": // [FULLWIDTH RIGHT CURLY BRACKET]
		buffer.WriteString("}")
	case "207A", // [SUPERSCRIPT PLUS SIGN]
		"208A", // [SUBSCRIPT PLUS SIGN]
		"FF0B": // [FULLWIDTH PLUS SIGN]
		buffer.WriteString("+")
	case "207C", // [SUPERSCRIPT EQUALS SIGN]
		"208C", // [SUBSCRIPT EQUALS SIGN]
		"FF1D": // [FULLWIDTH EQUALS SIGN]
		buffer.WriteString("=")
	case "FF01": // [FULLWIDTH EXCLAMATION MARK]
		buffer.WriteString("!")
	case "203C": // [DOUBLE EXCLAMATION MARK]
		buffer.WriteString("!")
		buffer.WriteString("!")
	case "2049": // [EXCLAMATION QUESTION MARK]
		buffer.WriteString("!")
		buffer.WriteString("?")
	case "FF03": // [FULLWIDTH NUMBER SIGN]
		buffer.WriteString("#")
	case "FF04": // [FULLWIDTH DOLLAR SIGN]
		buffer.WriteString("$")
	case "2052", // [COMMERCIAL MINUS SIGN]
		"FF05": // [FULLWIDTH PERCENT SIGN]
		buffer.WriteString("%")
	case "FF06": // [FULLWIDTH AMPERSAND]
		buffer.WriteString("&")
	case "204E", // [LOW ASTERISK]
		"FF0A": // [FULLWIDTH ASTERISK]
		buffer.WriteString("*")
	case "FF0C": // [FULLWIDTH COMMA]
		buffer.WriteString(",")
	case "FF0E": // [FULLWIDTH FULL STOP]
		buffer.WriteString(".")
	case "2044", // [FRACTION SLASH]
		"FF0F": // [FULLWIDTH SOLIDUS]
		buffer.WriteString("/")
	case "FF1A": // [FULLWIDTH COLON]
		buffer.WriteString(":")
	case "204F", // [REVERSED SEMICOLON]
		"FF1B": // [FULLWIDTH SEMICOLON]
		buffer.WriteString(";")
	case "FF1F": // [FULLWIDTH QUESTION MARK]
		buffer.WriteString("?")
	case "2047": // [DOUBLE QUESTION MARK]
		buffer.WriteString("?")
		buffer.WriteString("?")
	case "2048": // [QUESTION EXCLAMATION MARK]
		buffer.WriteString("?")
		buffer.WriteString("!")
	case "FF20": // [FULLWIDTH COMMERCIAL AT]
		buffer.WriteString("@")
	case "FF3C": // [FULLWIDTH REVERSE SOLIDUS]
		buffer.WriteString("\\")
	case "2038", // [CARET]
		"FF3E": // [FULLWIDTH CIRCUMFLEX ACCENT]
		buffer.WriteString("^")
	case "FF3F": // [FULLWIDTH LOW LINE]
		buffer.WriteString("_")
	case "2053", // [SWUNG DASH]
		"FF5E": // [FULLWIDTH TILDE]
		buffer.WriteString("~")
	default:
		buffer.WriteRune(r)
	}

	return buffer.String()
}
