#%RAML 1.0 ResourceType

base:
  uriParameters:
    mediaTypeExtension:
      enum: [ .json ]
      description: Use .json to specify application/json media type.
  get?: &common
    headers:
      Accept:
        description: Is used to set specified media type.
        type: string
    body:
      application/json:
        schema: {"name": "string"}
        example: {"name": "Foo Bar"}
    responses:
      403:
        description: |
          API rate limit exceeded.
        headers:
          X-waiting-period:
            description: |
              The number of seconds to wait before you can attempt to make a request again.
            type: integer
            required: true
            minimum: 1
            maximum: 3600
            example: 34
        body:
          application/json:
            schema: {"name": "string"}
            example: {"name": "Foo Bar"}
  post?: *common
