#%RAML 1.0 Library

uses:
  tra: ../traits/traits.lib.raml
  typ: ../dataTypes/types.lib.raml

resourceTypes:
  collection: !include collection.raml
  member: !include member.raml
  base: !include base.raml
  rdf: !include rdf.raml

