// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.4
// source: ikuzo/service/x/mapping/mappingpb/mapping.proto

package mappingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttrType int32

const (
	AttrType_XML_LANG     AttrType = 0
	AttrType_RDF_TYPE     AttrType = 1
	AttrType_RDF_RESOURCE AttrType = 2
	AttrType_RDF_ABOUT    AttrType = 3
	AttrType_RDF_DATATYPE AttrType = 4
)

// Enum value maps for AttrType.
var (
	AttrType_name = map[int32]string{
		0: "XML_LANG",
		1: "RDF_TYPE",
		2: "RDF_RESOURCE",
		3: "RDF_ABOUT",
		4: "RDF_DATATYPE",
	}
	AttrType_value = map[string]int32{
		"XML_LANG":     0,
		"RDF_TYPE":     1,
		"RDF_RESOURCE": 2,
		"RDF_ABOUT":    3,
		"RDF_DATATYPE": 4,
	}
)

func (x AttrType) Enum() *AttrType {
	p := new(AttrType)
	*p = x
	return p
}

func (x AttrType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttrType) Descriptor() protoreflect.EnumDescriptor {
	return file_ikuzo_service_x_mapping_mappingpb_mapping_proto_enumTypes[0].Descriptor()
}

func (AttrType) Type() protoreflect.EnumType {
	return &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_enumTypes[0]
}

func (x AttrType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttrType.Descriptor instead.
func (AttrType) EnumDescriptor() ([]byte, []int) {
	return file_ikuzo_service_x_mapping_mappingpb_mapping_proto_rawDescGZIP(), []int{0}
}

type RecDef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header       *Header            `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Namespaces   []*Namespace       `protobuf:"bytes,2,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	Functions    []*MappingFunction `protobuf:"bytes,3,rep,name=functions,proto3" json:"functions,omitempty"`
	Attrs        []*Attr            `protobuf:"bytes,4,rep,name=attrs,proto3" json:"attrs,omitempty"`
	Root         *Root              `protobuf:"bytes,5,opt,name=root,proto3" json:"root,omitempty"`
	FieldMarkers []*FieldMarker     `protobuf:"bytes,6,rep,name=fieldMarkers,proto3" json:"fieldMarkers,omitempty"`
	Docs         []*Doc             `protobuf:"bytes,7,rep,name=docs,proto3" json:"docs,omitempty"`
}

func (x *RecDef) Reset() {
	*x = RecDef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecDef) ProtoMessage() {}

func (x *RecDef) ProtoReflect() protoreflect.Message {
	mi := &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecDef.ProtoReflect.Descriptor instead.
func (*RecDef) Descriptor() ([]byte, []int) {
	return file_ikuzo_service_x_mapping_mappingpb_mapping_proto_rawDescGZIP(), []int{0}
}

func (x *RecDef) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RecDef) GetNamespaces() []*Namespace {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *RecDef) GetFunctions() []*MappingFunction {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *RecDef) GetAttrs() []*Attr {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *RecDef) GetRoot() *Root {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *RecDef) GetFieldMarkers() []*FieldMarker {
	if x != nil {
		return x.FieldMarkers
	}
	return nil
}

func (x *RecDef) GetDocs() []*Doc {
	if x != nil {
		return x.Docs
	}
	return nil
}

type Mapping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header       *Header            `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Facts        []*Fact            `protobuf:"bytes,2,rep,name=facts,proto3" json:"facts,omitempty"`
	Functions    []*MappingFunction `protobuf:"bytes,3,rep,name=functions,proto3" json:"functions,omitempty"`
	DynOpts      []*DynOpt          `protobuf:"bytes,4,rep,name=dynOpts,proto3" json:"dynOpts,omitempty"`
	NodeMappings []*NodeMapping     `protobuf:"bytes,5,rep,name=nodeMappings,proto3" json:"nodeMappings,omitempty"`
}

func (x *Mapping) Reset() {
	*x = Mapping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mapping) ProtoMessage() {}

func (x *Mapping) ProtoReflect() protoreflect.Message {
	mi := &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mapping.ProtoReflect.Descriptor instead.
func (*Mapping) Descriptor() ([]byte, []int) {
	return file_ikuzo_service_x_mapping_mappingpb_mapping_proto_rawDescGZIP(), []int{1}
}

func (x *Mapping) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Mapping) GetFacts() []*Fact {
	if x != nil {
		return x.Facts
	}
	return nil
}

func (x *Mapping) GetFunctions() []*MappingFunction {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *Mapping) GetDynOpts() []*DynOpt {
	if x != nil {
		return x.DynOpts
	}
	return nil
}

func (x *Mapping) GetNodeMappings() []*NodeMapping {
	if x != nil {
		return x.NodeMappings
	}
	return nil
}

type DynOpt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path  string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DynOpt) Reset() {
	*x = DynOpt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DynOpt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynOpt) ProtoMessage() {}

func (x *DynOpt) ProtoReflect() protoreflect.Message {
	mi := &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynOpt.ProtoReflect.Descriptor instead.
func (*DynOpt) Descriptor() ([]byte, []int) {
	return file_ikuzo_service_x_mapping_mappingpb_mapping_proto_rawDescGZIP(), []int{2}
}

func (x *DynOpt) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DynOpt) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Fact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Fact) Reset() {
	*x = Fact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fact) ProtoMessage() {}

func (x *Fact) ProtoReflect() protoreflect.Message {
	mi := &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fact.ProtoReflect.Descriptor instead.
func (*Fact) Descriptor() ([]byte, []int) {
	return file_ikuzo_service_x_mapping_mappingpb_mapping_proto_rawDescGZIP(), []int{3}
}

func (x *Fact) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Fact) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Doc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path  string  `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Paras []*Para `protobuf:"bytes,2,rep,name=paras,proto3" json:"paras,omitempty"`
}

func (x *Doc) Reset() {
	*x = Doc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Doc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Doc) ProtoMessage() {}

func (x *Doc) ProtoReflect() protoreflect.Message {
	mi := &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Doc.ProtoReflect.Descriptor instead.
func (*Doc) Descriptor() ([]byte, []int) {
	return file_ikuzo_service_x_mapping_mappingpb_mapping_proto_rawDescGZIP(), []int{4}
}

func (x *Doc) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Doc) GetParas() []*Para {
	if x != nil {
		return x.Paras
	}
	return nil
}

// TODO(kiivihal): Describe this message.
type Para struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Para) Reset() {
	*x = Para{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Para) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Para) ProtoMessage() {}

func (x *Para) ProtoReflect() protoreflect.Message {
	mi := &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Para.ProtoReflect.Descriptor instead.
func (*Para) Descriptor() ([]byte, []int) {
	return file_ikuzo_service_x_mapping_mappingpb_mapping_proto_rawDescGZIP(), []int{5}
}

func (x *Para) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Para) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// todo finish
type FieldMarker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FieldMarker) Reset() {
	*x = FieldMarker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldMarker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldMarker) ProtoMessage() {}

func (x *FieldMarker) ProtoReflect() protoreflect.Message {
	mi := &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldMarker.ProtoReflect.Descriptor instead.
func (*FieldMarker) Descriptor() ([]byte, []int) {
	return file_ikuzo_service_x_mapping_mappingpb_mapping_proto_rawDescGZIP(), []int{6}
}

type Root struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag         string       `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	NodeMapping *NodeMapping `protobuf:"bytes,2,opt,name=nodeMapping,proto3" json:"nodeMapping,omitempty"`
	Elems       []*Elem      `protobuf:"bytes,3,rep,name=elems,proto3" json:"elems,omitempty"`
}

func (x *Root) Reset() {
	*x = Root{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Root) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Root) ProtoMessage() {}

func (x *Root) ProtoReflect() protoreflect.Message {
	mi := &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Root.ProtoReflect.Descriptor instead.
func (*Root) Descriptor() ([]byte, []int) {
	return file_ikuzo_service_x_mapping_mappingpb_mapping_proto_rawDescGZIP(), []int{7}
}

func (x *Root) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Root) GetNodeMapping() *NodeMapping {
	if x != nil {
		return x.NodeMapping
	}
	return nil
}

func (x *Root) GetElems() []*Elem {
	if x != nil {
		return x.Elems
	}
	return nil
}

type Elem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag         string       `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	AttrType    AttrType     `protobuf:"varint,2,opt,name=attrType,proto3,enum=mappingpb.AttrType" json:"attrType,omitempty"`
	Attr        *Attr        `protobuf:"bytes,3,opt,name=attr,proto3" json:"attr,omitempty"`
	NodeMapping *NodeMapping `protobuf:"bytes,4,opt,name=nodeMapping,proto3" json:"nodeMapping,omitempty"`
	Elems       []*Elem      `protobuf:"bytes,5,rep,name=elems,proto3" json:"elems,omitempty"`
}

func (x *Elem) Reset() {
	*x = Elem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Elem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Elem) ProtoMessage() {}

func (x *Elem) ProtoReflect() protoreflect.Message {
	mi := &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Elem.ProtoReflect.Descriptor instead.
func (*Elem) Descriptor() ([]byte, []int) {
	return file_ikuzo_service_x_mapping_mappingpb_mapping_proto_rawDescGZIP(), []int{8}
}

func (x *Elem) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Elem) GetAttrType() AttrType {
	if x != nil {
		return x.AttrType
	}
	return AttrType_XML_LANG
}

func (x *Elem) GetAttr() *Attr {
	if x != nil {
		return x.Attr
	}
	return nil
}

func (x *Elem) GetNodeMapping() *NodeMapping {
	if x != nil {
		return x.NodeMapping
	}
	return nil
}

func (x *Elem) GetElems() []*Elem {
	if x != nil {
		return x.Elems
	}
	return nil
}

// TODO(kiivihal): Describe this message.
type Attr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag         string       `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	UriCheck    bool         `protobuf:"varint,2,opt,name=uriCheck,proto3" json:"uriCheck,omitempty"`
	Hidden      bool         `protobuf:"varint,3,opt,name=hidden,proto3" json:"hidden,omitempty"`
	NodeMapping *NodeMapping `protobuf:"bytes,4,opt,name=nodeMapping,proto3" json:"nodeMapping,omitempty"`
}

func (x *Attr) Reset() {
	*x = Attr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Attr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attr) ProtoMessage() {}

func (x *Attr) ProtoReflect() protoreflect.Message {
	mi := &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attr.ProtoReflect.Descriptor instead.
func (*Attr) Descriptor() ([]byte, []int) {
	return file_ikuzo_service_x_mapping_mappingpb_mapping_proto_rawDescGZIP(), []int{9}
}

func (x *Attr) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Attr) GetUriCheck() bool {
	if x != nil {
		return x.UriCheck
	}
	return false
}

func (x *Attr) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *Attr) GetNodeMapping() *NodeMapping {
	if x != nil {
		return x.NodeMapping
	}
	return nil
}

type NodeMapping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InputPath  string `protobuf:"bytes,1,opt,name=inputPath,proto3" json:"inputPath,omitempty"`
	OutputPath string `protobuf:"bytes,2,opt,name=outputPath,proto3" json:"outputPath,omitempty"`
	GroovyCode string `protobuf:"bytes,3,opt,name=groovyCode,proto3" json:"groovyCode,omitempty"`
}

func (x *NodeMapping) Reset() {
	*x = NodeMapping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMapping) ProtoMessage() {}

func (x *NodeMapping) ProtoReflect() protoreflect.Message {
	mi := &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMapping.ProtoReflect.Descriptor instead.
func (*NodeMapping) Descriptor() ([]byte, []int) {
	return file_ikuzo_service_x_mapping_mappingpb_mapping_proto_rawDescGZIP(), []int{10}
}

func (x *NodeMapping) GetInputPath() string {
	if x != nil {
		return x.InputPath
	}
	return ""
}

func (x *NodeMapping) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

func (x *NodeMapping) GetGroovyCode() string {
	if x != nil {
		return x.GroovyCode
	}
	return ""
}

type MappingFunction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GroovyCode  string   `protobuf:"bytes,2,opt,name=groovyCode,proto3" json:"groovyCode,omitempty"`
	SampleInput []string `protobuf:"bytes,3,rep,name=sampleInput,proto3" json:"sampleInput,omitempty"` // slightly different from before
}

func (x *MappingFunction) Reset() {
	*x = MappingFunction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MappingFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappingFunction) ProtoMessage() {}

func (x *MappingFunction) ProtoReflect() protoreflect.Message {
	mi := &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappingFunction.ProtoReflect.Descriptor instead.
func (*MappingFunction) Descriptor() ([]byte, []int) {
	return file_ikuzo_service_x_mapping_mappingpb_mapping_proto_rawDescGZIP(), []int{11}
}

func (x *MappingFunction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MappingFunction) GetGroovyCode() string {
	if x != nil {
		return x.GroovyCode
	}
	return ""
}

func (x *MappingFunction) GetSampleInput() []string {
	if x != nil {
		return x.SampleInput
	}
	return nil
}

type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prefix  string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Flat    bool   `protobuf:"varint,3,opt,name=flat,proto3" json:"flat,omitempty"`
	Locked  bool   `protobuf:"varint,4,opt,name=locked,proto3" json:"locked,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_ikuzo_service_x_mapping_mappingpb_mapping_proto_rawDescGZIP(), []int{12}
}

func (x *Header) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *Header) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Header) GetFlat() bool {
	if x != nil {
		return x.Flat
	}
	return false
}

func (x *Header) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

type Namespace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prefix string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Uri    string `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_ikuzo_service_x_mapping_mappingpb_mapping_proto_rawDescGZIP(), []int{13}
}

func (x *Namespace) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *Namespace) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

var File_ikuzo_service_x_mapping_mappingpb_mapping_proto protoreflect.FileDescriptor

var file_ikuzo_service_x_mapping_mappingpb_mapping_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x69, 0x6b, 0x75, 0x7a, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x78, 0x2f, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x2f, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x70, 0x62, 0x2f, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x22, 0xcf, 0x02, 0x0a,
	0x06, 0x52, 0x65, 0x63, 0x44, 0x65, 0x66, 0x12, 0x29, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x70, 0x62, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x34, 0x0a, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x70, 0x62, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x0a, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x12, 0x38, 0x0a, 0x09, 0x66, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x61,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x46,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x25, 0x0a, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x41, 0x74,
	0x74, 0x72, 0x52, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x12, 0x23, 0x0a, 0x04, 0x72, 0x6f, 0x6f,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x70, 0x62, 0x2e, 0x52, 0x6f, 0x6f, 0x74, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x12, 0x3a,
	0x0a, 0x0c, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x70, 0x62,
	0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x52, 0x0c, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x12, 0x22, 0x0a, 0x04, 0x64, 0x6f,
	0x63, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x70, 0x62, 0x2e, 0x44, 0x6f, 0x63, 0x52, 0x04, 0x64, 0x6f, 0x63, 0x73, 0x22, 0xfe,
	0x01, 0x0a, 0x07, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x29, 0x0a, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x61, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x05, 0x66, 0x61, 0x63, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x70, 0x62,
	0x2e, 0x46, 0x61, 0x63, 0x74, 0x52, 0x05, 0x66, 0x61, 0x63, 0x74, 0x73, 0x12, 0x38, 0x0a, 0x09,
	0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x66, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2b, 0x0a, 0x07, 0x64, 0x79, 0x6e, 0x4f, 0x70, 0x74,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x70, 0x62, 0x2e, 0x44, 0x79, 0x6e, 0x4f, 0x70, 0x74, 0x52, 0x07, 0x64, 0x79, 0x6e, 0x4f,
	0x70, 0x74, 0x73, 0x12, 0x3a, 0x0a, 0x0c, 0x6e, 0x6f, 0x64, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x61, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x52, 0x0c, 0x6e, 0x6f, 0x64, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x22,
	0x32, 0x0a, 0x06, 0x44, 0x79, 0x6e, 0x4f, 0x70, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x2e, 0x0a, 0x04, 0x46, 0x61, 0x63, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x40, 0x0a, 0x03, 0x44, 0x6f, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x25,
	0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x52, 0x05,
	0x70, 0x61, 0x72, 0x61, 0x73, 0x22, 0x3c, 0x0a, 0x04, 0x50, 0x61, 0x72, 0x61, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x0d, 0x0a, 0x0b, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4d, 0x61, 0x72, 0x6b,
	0x65, 0x72, 0x22, 0x79, 0x0a, 0x04, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x38, 0x0a, 0x0b,
	0x6e, 0x6f, 0x64, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x4e, 0x6f,
	0x64, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x0b, 0x6e, 0x6f, 0x64, 0x65, 0x4d,
	0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x25, 0x0a, 0x05, 0x65, 0x6c, 0x65, 0x6d, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x70,
	0x62, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x52, 0x05, 0x65, 0x6c, 0x65, 0x6d, 0x73, 0x22, 0xcf, 0x01,
	0x0a, 0x04, 0x45, 0x6c, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x2f, 0x0a, 0x08, 0x61, 0x74, 0x74, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6d, 0x61, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x08, 0x61, 0x74, 0x74, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x61, 0x74, 0x74,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x70, 0x62, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x52, 0x04, 0x61, 0x74, 0x74, 0x72, 0x12, 0x38,
	0x0a, 0x0b, 0x6e, 0x6f, 0x64, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x0b, 0x6e, 0x6f, 0x64,
	0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x25, 0x0a, 0x05, 0x65, 0x6c, 0x65, 0x6d,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x70, 0x62, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x52, 0x05, 0x65, 0x6c, 0x65, 0x6d, 0x73, 0x22,
	0x86, 0x01, 0x0a, 0x04, 0x41, 0x74, 0x74, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x72,
	0x69, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x75, 0x72,
	0x69, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x69, 0x64, 0x64, 0x65, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x68, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x12, 0x38,
	0x0a, 0x0b, 0x6e, 0x6f, 0x64, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x0b, 0x6e, 0x6f, 0x64,
	0x65, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x22, 0x6b, 0x0a, 0x0b, 0x4e, 0x6f, 0x64, 0x65,
	0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x70, 0x75, 0x74,
	0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x70, 0x75,
	0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x50,
	0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x6f, 0x76, 0x79, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67, 0x72, 0x6f, 0x6f, 0x76,
	0x79, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x67, 0x0a, 0x0f, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x67, 0x72, 0x6f, 0x6f, 0x76, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x67, 0x72, 0x6f, 0x6f, 0x76, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0b, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x22, 0x66,
	0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66,
	0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c,
	0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x22, 0x35, 0x0a, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x2a, 0x59, 0x0a,
	0x08, 0x41, 0x74, 0x74, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x58, 0x4d, 0x4c,
	0x5f, 0x4c, 0x41, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x44, 0x46, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x44, 0x46, 0x5f, 0x52, 0x45, 0x53,
	0x4f, 0x55, 0x52, 0x43, 0x45, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x44, 0x46, 0x5f, 0x41,
	0x42, 0x4f, 0x55, 0x54, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x44, 0x46, 0x5f, 0x44, 0x41,
	0x54, 0x41, 0x54, 0x59, 0x50, 0x45, 0x10, 0x04, 0x42, 0x23, 0x5a, 0x21, 0x69, 0x6b, 0x75, 0x7a,
	0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x78, 0x2f, 0x6d, 0x61, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x2f, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ikuzo_service_x_mapping_mappingpb_mapping_proto_rawDescOnce sync.Once
	file_ikuzo_service_x_mapping_mappingpb_mapping_proto_rawDescData = file_ikuzo_service_x_mapping_mappingpb_mapping_proto_rawDesc
)

func file_ikuzo_service_x_mapping_mappingpb_mapping_proto_rawDescGZIP() []byte {
	file_ikuzo_service_x_mapping_mappingpb_mapping_proto_rawDescOnce.Do(func() {
		file_ikuzo_service_x_mapping_mappingpb_mapping_proto_rawDescData = protoimpl.X.CompressGZIP(file_ikuzo_service_x_mapping_mappingpb_mapping_proto_rawDescData)
	})
	return file_ikuzo_service_x_mapping_mappingpb_mapping_proto_rawDescData
}

var file_ikuzo_service_x_mapping_mappingpb_mapping_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_ikuzo_service_x_mapping_mappingpb_mapping_proto_goTypes = []interface{}{
	(AttrType)(0),           // 0: mappingpb.AttrType
	(*RecDef)(nil),          // 1: mappingpb.RecDef
	(*Mapping)(nil),         // 2: mappingpb.Mapping
	(*DynOpt)(nil),          // 3: mappingpb.DynOpt
	(*Fact)(nil),            // 4: mappingpb.Fact
	(*Doc)(nil),             // 5: mappingpb.Doc
	(*Para)(nil),            // 6: mappingpb.Para
	(*FieldMarker)(nil),     // 7: mappingpb.FieldMarker
	(*Root)(nil),            // 8: mappingpb.Root
	(*Elem)(nil),            // 9: mappingpb.Elem
	(*Attr)(nil),            // 10: mappingpb.Attr
	(*NodeMapping)(nil),     // 11: mappingpb.NodeMapping
	(*MappingFunction)(nil), // 12: mappingpb.MappingFunction
	(*Header)(nil),          // 13: mappingpb.Header
	(*Namespace)(nil),       // 14: mappingpb.Namespace
}
var file_ikuzo_service_x_mapping_mappingpb_mapping_proto_depIdxs = []int32{
	13, // 0: mappingpb.RecDef.header:type_name -> mappingpb.Header
	14, // 1: mappingpb.RecDef.namespaces:type_name -> mappingpb.Namespace
	12, // 2: mappingpb.RecDef.functions:type_name -> mappingpb.MappingFunction
	10, // 3: mappingpb.RecDef.attrs:type_name -> mappingpb.Attr
	8,  // 4: mappingpb.RecDef.root:type_name -> mappingpb.Root
	7,  // 5: mappingpb.RecDef.fieldMarkers:type_name -> mappingpb.FieldMarker
	5,  // 6: mappingpb.RecDef.docs:type_name -> mappingpb.Doc
	13, // 7: mappingpb.Mapping.header:type_name -> mappingpb.Header
	4,  // 8: mappingpb.Mapping.facts:type_name -> mappingpb.Fact
	12, // 9: mappingpb.Mapping.functions:type_name -> mappingpb.MappingFunction
	3,  // 10: mappingpb.Mapping.dynOpts:type_name -> mappingpb.DynOpt
	11, // 11: mappingpb.Mapping.nodeMappings:type_name -> mappingpb.NodeMapping
	6,  // 12: mappingpb.Doc.paras:type_name -> mappingpb.Para
	11, // 13: mappingpb.Root.nodeMapping:type_name -> mappingpb.NodeMapping
	9,  // 14: mappingpb.Root.elems:type_name -> mappingpb.Elem
	0,  // 15: mappingpb.Elem.attrType:type_name -> mappingpb.AttrType
	10, // 16: mappingpb.Elem.attr:type_name -> mappingpb.Attr
	11, // 17: mappingpb.Elem.nodeMapping:type_name -> mappingpb.NodeMapping
	9,  // 18: mappingpb.Elem.elems:type_name -> mappingpb.Elem
	11, // 19: mappingpb.Attr.nodeMapping:type_name -> mappingpb.NodeMapping
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_ikuzo_service_x_mapping_mappingpb_mapping_proto_init() }
func file_ikuzo_service_x_mapping_mappingpb_mapping_proto_init() {
	if File_ikuzo_service_x_mapping_mappingpb_mapping_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecDef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mapping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DynOpt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Doc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Para); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldMarker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Root); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Elem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Attr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeMapping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MappingFunction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Namespace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ikuzo_service_x_mapping_mappingpb_mapping_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ikuzo_service_x_mapping_mappingpb_mapping_proto_goTypes,
		DependencyIndexes: file_ikuzo_service_x_mapping_mappingpb_mapping_proto_depIdxs,
		EnumInfos:         file_ikuzo_service_x_mapping_mappingpb_mapping_proto_enumTypes,
		MessageInfos:      file_ikuzo_service_x_mapping_mappingpb_mapping_proto_msgTypes,
	}.Build()
	File_ikuzo_service_x_mapping_mappingpb_mapping_proto = out.File
	file_ikuzo_service_x_mapping_mappingpb_mapping_proto_rawDesc = nil
	file_ikuzo_service_x_mapping_mappingpb_mapping_proto_goTypes = nil
	file_ikuzo_service_x_mapping_mappingpb_mapping_proto_depIdxs = nil
}
