// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hub3/fragments/api.proto

package fragments

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResponseFormatType int32

const (
	ResponseFormatType_JSON     ResponseFormatType = 0
	ResponseFormatType_PROTOBUF ResponseFormatType = 1
	// not supported
	ResponseFormatType_XML ResponseFormatType = 2
	// not supported
	ResponseFormatType_JSONP ResponseFormatType = 3
	// not supported
	ResponseFormatType_KML ResponseFormatType = 4
	// not supported
	ResponseFormatType_GEOCLUSTER ResponseFormatType = 5
	// not supported
	ResponseFormatType_GEOJSON ResponseFormatType = 6
	// not supported
	ResponseFormatType_GEOBUF ResponseFormatType = 7
)

var ResponseFormatType_name = map[int32]string{
	0: "JSON",
	1: "PROTOBUF",
	2: "XML",
	3: "JSONP",
	4: "KML",
	5: "GEOCLUSTER",
	6: "GEOJSON",
	7: "GEOBUF",
}
var ResponseFormatType_value = map[string]int32{
	"JSON":       0,
	"PROTOBUF":   1,
	"XML":        2,
	"JSONP":      3,
	"KML":        4,
	"GEOCLUSTER": 5,
	"GEOJSON":    6,
	"GEOBUF":     7,
}

func (x ResponseFormatType) String() string {
	return proto.EnumName(ResponseFormatType_name, int32(x))
}
func (ResponseFormatType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{0}
}

type ItemFormatType int32

const (
	ItemFormatType_SUMMARY       ItemFormatType = 0
	ItemFormatType_FRAGMENTGRAPH ItemFormatType = 1
	ItemFormatType_GROUPED       ItemFormatType = 2
	ItemFormatType_JSONLD        ItemFormatType = 3
)

var ItemFormatType_name = map[int32]string{
	0: "SUMMARY",
	1: "FRAGMENTGRAPH",
	2: "GROUPED",
	3: "JSONLD",
}
var ItemFormatType_value = map[string]int32{
	"SUMMARY":       0,
	"FRAGMENTGRAPH": 1,
	"GROUPED":       2,
	"JSONLD":        3,
}

func (x ItemFormatType) String() string {
	return proto.EnumName(ItemFormatType_name, int32(x))
}
func (ItemFormatType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{1}
}

type ResponseBlockType int32

const (
	ResponseBlockType_QUERY      ResponseBlockType = 0
	ResponseBlockType_ITEMS      ResponseBlockType = 1
	ResponseBlockType_FACETS     ResponseBlockType = 2
	ResponseBlockType_LAYOUT     ResponseBlockType = 3
	ResponseBlockType_PAGINATION ResponseBlockType = 4
)

var ResponseBlockType_name = map[int32]string{
	0: "QUERY",
	1: "ITEMS",
	2: "FACETS",
	3: "LAYOUT",
	4: "PAGINATION",
}
var ResponseBlockType_value = map[string]int32{
	"QUERY":      0,
	"ITEMS":      1,
	"FACETS":     2,
	"LAYOUT":     3,
	"PAGINATION": 4,
}

func (x ResponseBlockType) String() string {
	return proto.EnumName(ResponseBlockType_name, int32(x))
}
func (ResponseBlockType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{2}
}

type GeoType int32

const (
	GeoType_BBOX    GeoType = 0
	GeoType_GEOFILT GeoType = 1
	GeoType_CLUSTER GeoType = 2
)

var GeoType_name = map[int32]string{
	0: "BBOX",
	1: "GEOFILT",
	2: "CLUSTER",
}
var GeoType_value = map[string]int32{
	"BBOX":    0,
	"GEOFILT": 1,
	"CLUSTER": 2,
}

func (x GeoType) String() string {
	return proto.EnumName(GeoType_name, int32(x))
}
func (GeoType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{3}
}

type IdType int32

const (
	// same as ES doc_id
	IdType_HUDID IdType = 0
	// case insensitive id search
	IdType_IDCI IdType = 1
	// named graph
	IdType_NAMEDGRAPH IdType = 2
)

var IdType_name = map[int32]string{
	0: "HUDID",
	1: "IDCI",
	2: "NAMEDGRAPH",
}
var IdType_value = map[string]int32{
	"HUDID":      0,
	"IDCI":       1,
	"NAMEDGRAPH": 2,
}

func (x IdType) String() string {
	return proto.EnumName(IdType_name, int32(x))
}
func (IdType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{4}
}

type ObjectType int32

const (
	ObjectType_RESOURCE ObjectType = 0
	ObjectType_LITERAL  ObjectType = 1
)

var ObjectType_name = map[int32]string{
	0: "RESOURCE",
	1: "LITERAL",
}
var ObjectType_value = map[string]int32{
	"RESOURCE": 0,
	"LITERAL":  1,
}

func (x ObjectType) String() string {
	return proto.EnumName(ObjectType_name, int32(x))
}
func (ObjectType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{5}
}

type ObjectXSDType int32

const (
	ObjectXSDType_STRING             ObjectXSDType = 0
	ObjectXSDType_BOOLEAN            ObjectXSDType = 1
	ObjectXSDType_DECIMAL            ObjectXSDType = 2
	ObjectXSDType_FLOAT              ObjectXSDType = 3
	ObjectXSDType_DOUBLE             ObjectXSDType = 4
	ObjectXSDType_DATETIME           ObjectXSDType = 5
	ObjectXSDType_TIME               ObjectXSDType = 6
	ObjectXSDType_DATE               ObjectXSDType = 7
	ObjectXSDType_GYEARMONTH         ObjectXSDType = 8
	ObjectXSDType_GYEAR              ObjectXSDType = 9
	ObjectXSDType_GMONTHDAY          ObjectXSDType = 10
	ObjectXSDType_GDAY               ObjectXSDType = 11
	ObjectXSDType_GMONTH             ObjectXSDType = 12
	ObjectXSDType_HEXBINARY          ObjectXSDType = 13
	ObjectXSDType_BASE64BINARY       ObjectXSDType = 14
	ObjectXSDType_ANYURI             ObjectXSDType = 15
	ObjectXSDType_NORMALIZEDSTRING   ObjectXSDType = 16
	ObjectXSDType_TOKEN              ObjectXSDType = 17
	ObjectXSDType_LANGUAGE           ObjectXSDType = 18
	ObjectXSDType_NMTOKEN            ObjectXSDType = 19
	ObjectXSDType_NAME               ObjectXSDType = 20
	ObjectXSDType_NCNAME             ObjectXSDType = 21
	ObjectXSDType_INTEGER            ObjectXSDType = 22
	ObjectXSDType_NONPOSITIVEINTEGER ObjectXSDType = 23
	ObjectXSDType_NEGATIVEINTEGER    ObjectXSDType = 24
	ObjectXSDType_LONG               ObjectXSDType = 25
	ObjectXSDType_INT                ObjectXSDType = 26
	ObjectXSDType_SHORT              ObjectXSDType = 27
	ObjectXSDType_BYTE               ObjectXSDType = 28
	ObjectXSDType_NONNEGATIVEINTEGER ObjectXSDType = 29
	ObjectXSDType_UNSIGNEDLONG       ObjectXSDType = 30
	ObjectXSDType_UNSIGNEDINT        ObjectXSDType = 31
	ObjectXSDType_UNSIGNEDSHORT      ObjectXSDType = 32
	ObjectXSDType_UNSIGNEDBYTE       ObjectXSDType = 33
	ObjectXSDType_POSITIVEINTEGER    ObjectXSDType = 34
)

var ObjectXSDType_name = map[int32]string{
	0:  "STRING",
	1:  "BOOLEAN",
	2:  "DECIMAL",
	3:  "FLOAT",
	4:  "DOUBLE",
	5:  "DATETIME",
	6:  "TIME",
	7:  "DATE",
	8:  "GYEARMONTH",
	9:  "GYEAR",
	10: "GMONTHDAY",
	11: "GDAY",
	12: "GMONTH",
	13: "HEXBINARY",
	14: "BASE64BINARY",
	15: "ANYURI",
	16: "NORMALIZEDSTRING",
	17: "TOKEN",
	18: "LANGUAGE",
	19: "NMTOKEN",
	20: "NAME",
	21: "NCNAME",
	22: "INTEGER",
	23: "NONPOSITIVEINTEGER",
	24: "NEGATIVEINTEGER",
	25: "LONG",
	26: "INT",
	27: "SHORT",
	28: "BYTE",
	29: "NONNEGATIVEINTEGER",
	30: "UNSIGNEDLONG",
	31: "UNSIGNEDINT",
	32: "UNSIGNEDSHORT",
	33: "UNSIGNEDBYTE",
	34: "POSITIVEINTEGER",
}
var ObjectXSDType_value = map[string]int32{
	"STRING":             0,
	"BOOLEAN":            1,
	"DECIMAL":            2,
	"FLOAT":              3,
	"DOUBLE":             4,
	"DATETIME":           5,
	"TIME":               6,
	"DATE":               7,
	"GYEARMONTH":         8,
	"GYEAR":              9,
	"GMONTHDAY":          10,
	"GDAY":               11,
	"GMONTH":             12,
	"HEXBINARY":          13,
	"BASE64BINARY":       14,
	"ANYURI":             15,
	"NORMALIZEDSTRING":   16,
	"TOKEN":              17,
	"LANGUAGE":           18,
	"NMTOKEN":            19,
	"NAME":               20,
	"NCNAME":             21,
	"INTEGER":            22,
	"NONPOSITIVEINTEGER": 23,
	"NEGATIVEINTEGER":    24,
	"LONG":               25,
	"INT":                26,
	"SHORT":              27,
	"BYTE":               28,
	"NONNEGATIVEINTEGER": 29,
	"UNSIGNEDLONG":       30,
	"UNSIGNEDINT":        31,
	"UNSIGNEDSHORT":      32,
	"UNSIGNEDBYTE":       33,
	"POSITIVEINTEGER":    34,
}

func (x ObjectXSDType) String() string {
	return proto.EnumName(ObjectXSDType_name, int32(x))
}
func (ObjectXSDType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{6}
}

type RecordType int32

const (
	RecordType_NARTHEX    RecordType = 0
	RecordType_SCHEMA     RecordType = 1
	RecordType_VOCABULARY RecordType = 2
	RecordType_SOURCE     RecordType = 3
	RecordType_CACHE      RecordType = 4
)

var RecordType_name = map[int32]string{
	0: "NARTHEX",
	1: "SCHEMA",
	2: "VOCABULARY",
	3: "SOURCE",
	4: "CACHE",
}
var RecordType_value = map[string]int32{
	"NARTHEX":    0,
	"SCHEMA":     1,
	"VOCABULARY": 2,
	"SOURCE":     3,
	"CACHE":      4,
}

func (x RecordType) String() string {
	return proto.EnumName(RecordType_name, int32(x))
}
func (RecordType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{7}
}

type FilterValue struct {
	Value                []string `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterValue) Reset()         { *m = FilterValue{} }
func (m *FilterValue) String() string { return proto.CompactTextString(m) }
func (*FilterValue) ProtoMessage()    {}
func (*FilterValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{0}
}
func (m *FilterValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterValue.Unmarshal(m, b)
}
func (m *FilterValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterValue.Marshal(b, m, deterministic)
}
func (dst *FilterValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterValue.Merge(dst, src)
}
func (m *FilterValue) XXX_Size() int {
	return xxx_messageInfo_FilterValue.Size(m)
}
func (m *FilterValue) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterValue.DiscardUnknown(m)
}

var xxx_messageInfo_FilterValue proto.InternalMessageInfo

func (m *FilterValue) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type SearchRequest struct {
	// Will output a summary result set. Any valid Lucene or Solr Query syntax will work.
	Query              string             `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	ResponseFormatType ResponseFormatType `protobuf:"varint,2,opt,name=responseFormatType,enum=fragments.ResponseFormatType" json:"responseFormatType,omitempty"`
	// number of results returned
	// rows
	ResponseSize      int32                   `protobuf:"varint,3,opt,name=responseSize" json:"responseSize,omitempty"`
	Start             int32                   `protobuf:"varint,4,opt,name=start" json:"start,omitempty"`
	Page              int32                   `protobuf:"varint,5,opt,name=page" json:"page,omitempty"`
	QueryFilter       map[string]*FilterValue `protobuf:"bytes,6,rep,name=QueryFilter" json:"QueryFilter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	HiddenQueryFilter map[string]*FilterValue `protobuf:"bytes,7,rep,name=HiddenQueryFilter" json:"HiddenQueryFilter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Disable           []ResponseBlockType     `protobuf:"varint,8,rep,packed,name=disable,enum=fragments.ResponseBlockType" json:"disable,omitempty"`
	Enable            []ResponseBlockType     `protobuf:"varint,9,rep,packed,name=enable,enum=fragments.ResponseBlockType" json:"enable,omitempty"`
	FacetField        []string                `protobuf:"bytes,10,rep,name=FacetField" json:"FacetField,omitempty"`
	FacetLimit        int32                   `protobuf:"varint,11,opt,name=FacetLimit" json:"FacetLimit,omitempty"`
	FacetBoolType     bool                    `protobuf:"varint,12,opt,name=FacetBoolType" json:"FacetBoolType,omitempty"`
	SortBy            string                  `protobuf:"bytes,13,opt,name=sortBy" json:"sortBy,omitempty"`
	// geo options
	LatLong  string `protobuf:"bytes,14,opt,name=LatLong" json:"LatLong,omitempty"`
	Distance string `protobuf:"bytes,15,opt,name=Distance" json:"Distance,omitempty"`
	// min_* and max_* are the bounding box parameters
	MinX float32 `protobuf:"fixed32,16,opt,name=min_x,json=minX" json:"min_x,omitempty"`
	MinY float32 `protobuf:"fixed32,17,opt,name=min_y,json=minY" json:"min_y,omitempty"`
	MaxX float32 `protobuf:"fixed32,18,opt,name=max_x,json=maxX" json:"max_x,omitempty"`
	MaxY float32 `protobuf:"fixed32,19,opt,name=max_y,json=maxY" json:"max_y,omitempty"`
	// add support for polygon
	Field   []string `protobuf:"bytes,20,rep,name=field" json:"field,omitempty"`
	GeoType GeoType  `protobuf:"varint,21,opt,name=geoType,enum=fragments.GeoType" json:"geoType,omitempty"`
	// qr
	QueryRefinement      string         `protobuf:"bytes,22,opt,name=QueryRefinement" json:"QueryRefinement,omitempty"`
	SearchAfter          string         `protobuf:"bytes,23,opt,name=searchAfter" json:"searchAfter,omitempty"`
	ItemFormat           ItemFormatType `protobuf:"varint,24,opt,name=itemFormat,enum=fragments.ItemFormatType" json:"itemFormat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{1}
}
func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (dst *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(dst, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchRequest) GetResponseFormatType() ResponseFormatType {
	if m != nil {
		return m.ResponseFormatType
	}
	return ResponseFormatType_JSON
}

func (m *SearchRequest) GetResponseSize() int32 {
	if m != nil {
		return m.ResponseSize
	}
	return 0
}

func (m *SearchRequest) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *SearchRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchRequest) GetQueryFilter() map[string]*FilterValue {
	if m != nil {
		return m.QueryFilter
	}
	return nil
}

func (m *SearchRequest) GetHiddenQueryFilter() map[string]*FilterValue {
	if m != nil {
		return m.HiddenQueryFilter
	}
	return nil
}

func (m *SearchRequest) GetDisable() []ResponseBlockType {
	if m != nil {
		return m.Disable
	}
	return nil
}

func (m *SearchRequest) GetEnable() []ResponseBlockType {
	if m != nil {
		return m.Enable
	}
	return nil
}

func (m *SearchRequest) GetFacetField() []string {
	if m != nil {
		return m.FacetField
	}
	return nil
}

func (m *SearchRequest) GetFacetLimit() int32 {
	if m != nil {
		return m.FacetLimit
	}
	return 0
}

func (m *SearchRequest) GetFacetBoolType() bool {
	if m != nil {
		return m.FacetBoolType
	}
	return false
}

func (m *SearchRequest) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *SearchRequest) GetLatLong() string {
	if m != nil {
		return m.LatLong
	}
	return ""
}

func (m *SearchRequest) GetDistance() string {
	if m != nil {
		return m.Distance
	}
	return ""
}

func (m *SearchRequest) GetMinX() float32 {
	if m != nil {
		return m.MinX
	}
	return 0
}

func (m *SearchRequest) GetMinY() float32 {
	if m != nil {
		return m.MinY
	}
	return 0
}

func (m *SearchRequest) GetMaxX() float32 {
	if m != nil {
		return m.MaxX
	}
	return 0
}

func (m *SearchRequest) GetMaxY() float32 {
	if m != nil {
		return m.MaxY
	}
	return 0
}

func (m *SearchRequest) GetField() []string {
	if m != nil {
		return m.Field
	}
	return nil
}

func (m *SearchRequest) GetGeoType() GeoType {
	if m != nil {
		return m.GeoType
	}
	return GeoType_BBOX
}

func (m *SearchRequest) GetQueryRefinement() string {
	if m != nil {
		return m.QueryRefinement
	}
	return ""
}

func (m *SearchRequest) GetSearchAfter() string {
	if m != nil {
		return m.SearchAfter
	}
	return ""
}

func (m *SearchRequest) GetItemFormat() ItemFormatType {
	if m != nil {
		return m.ItemFormat
	}
	return ItemFormatType_SUMMARY
}

type DetailRequest struct {
	// option: any valid identifier specified by the idType
	// description: Will output a full-view. Default idType is hubId taken from the delving_hubId field.
	Id             string             `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Mlt            bool               `protobuf:"varint,2,opt,name=mlt" json:"mlt,omitempty"`
	Format         ResponseFormatType `protobuf:"varint,3,opt,name=format,enum=fragments.ResponseFormatType" json:"format,omitempty"`
	MltCount       int32              `protobuf:"varint,4,opt,name=mltCount" json:"mltCount,omitempty"`
	MltQueryFilter string             `protobuf:"bytes,5,opt,name=mltQueryFilter" json:"mltQueryFilter,omitempty"`
	MltFilterKey   string             `protobuf:"bytes,6,opt,name=mltFilterKey" json:"mltFilterKey,omitempty"`
	// searchRequest is a serialised form of the search result and is the return
	// to results link
	SearchRequest string `protobuf:"bytes,7,opt,name=searchRequest" json:"searchRequest,omitempty"`
	// resultIndex is the point where this detail object is in the search result order
	ResultIndex int32 `protobuf:"varint,8,opt,name=resultIndex" json:"resultIndex,omitempty"`
	// converter for result fields
	Converter string `protobuf:"bytes,9,opt,name=converter" json:"converter,omitempty"`
	// the type of id used in the ?id field
	IdType               IdType   `protobuf:"varint,10,opt,name=idType,enum=fragments.IdType" json:"idType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailRequest) Reset()         { *m = DetailRequest{} }
func (m *DetailRequest) String() string { return proto.CompactTextString(m) }
func (*DetailRequest) ProtoMessage()    {}
func (*DetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{2}
}
func (m *DetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailRequest.Unmarshal(m, b)
}
func (m *DetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailRequest.Marshal(b, m, deterministic)
}
func (dst *DetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailRequest.Merge(dst, src)
}
func (m *DetailRequest) XXX_Size() int {
	return xxx_messageInfo_DetailRequest.Size(m)
}
func (m *DetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetailRequest proto.InternalMessageInfo

func (m *DetailRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DetailRequest) GetMlt() bool {
	if m != nil {
		return m.Mlt
	}
	return false
}

func (m *DetailRequest) GetFormat() ResponseFormatType {
	if m != nil {
		return m.Format
	}
	return ResponseFormatType_JSON
}

func (m *DetailRequest) GetMltCount() int32 {
	if m != nil {
		return m.MltCount
	}
	return 0
}

func (m *DetailRequest) GetMltQueryFilter() string {
	if m != nil {
		return m.MltQueryFilter
	}
	return ""
}

func (m *DetailRequest) GetMltFilterKey() string {
	if m != nil {
		return m.MltFilterKey
	}
	return ""
}

func (m *DetailRequest) GetSearchRequest() string {
	if m != nil {
		return m.SearchRequest
	}
	return ""
}

func (m *DetailRequest) GetResultIndex() int32 {
	if m != nil {
		return m.ResultIndex
	}
	return 0
}

func (m *DetailRequest) GetConverter() string {
	if m != nil {
		return m.Converter
	}
	return ""
}

func (m *DetailRequest) GetIdType() IdType {
	if m != nil {
		return m.IdType
	}
	return IdType_HUDID
}

type BreadCrumb struct {
	Href                 string   `protobuf:"bytes,1,opt,name=href" json:"href,omitempty"`
	Display              string   `protobuf:"bytes,2,opt,name=display" json:"display,omitempty"`
	Field                string   `protobuf:"bytes,3,opt,name=field" json:"field,omitempty"`
	LocalisedField       string   `protobuf:"bytes,4,opt,name=localised_field,json=localisedField" json:"localised_field,omitempty"`
	Value                string   `protobuf:"bytes,5,opt,name=value" json:"value,omitempty"`
	IsLast               bool     `protobuf:"varint,6,opt,name=is_last,json=isLast" json:"is_last,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BreadCrumb) Reset()         { *m = BreadCrumb{} }
func (m *BreadCrumb) String() string { return proto.CompactTextString(m) }
func (*BreadCrumb) ProtoMessage()    {}
func (*BreadCrumb) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{3}
}
func (m *BreadCrumb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BreadCrumb.Unmarshal(m, b)
}
func (m *BreadCrumb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BreadCrumb.Marshal(b, m, deterministic)
}
func (dst *BreadCrumb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BreadCrumb.Merge(dst, src)
}
func (m *BreadCrumb) XXX_Size() int {
	return xxx_messageInfo_BreadCrumb.Size(m)
}
func (m *BreadCrumb) XXX_DiscardUnknown() {
	xxx_messageInfo_BreadCrumb.DiscardUnknown(m)
}

var xxx_messageInfo_BreadCrumb proto.InternalMessageInfo

func (m *BreadCrumb) GetHref() string {
	if m != nil {
		return m.Href
	}
	return ""
}

func (m *BreadCrumb) GetDisplay() string {
	if m != nil {
		return m.Display
	}
	return ""
}

func (m *BreadCrumb) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *BreadCrumb) GetLocalisedField() string {
	if m != nil {
		return m.LocalisedField
	}
	return ""
}

func (m *BreadCrumb) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *BreadCrumb) GetIsLast() bool {
	if m != nil {
		return m.IsLast
	}
	return false
}

type PaginationLink struct {
	Start                int32    `protobuf:"varint,1,opt,name=start" json:"start,omitempty"`
	IsLinked             bool     `protobuf:"varint,2,opt,name=isLinked" json:"isLinked,omitempty"`
	PageNumber           int32    `protobuf:"varint,3,opt,name=pageNumber" json:"pageNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaginationLink) Reset()         { *m = PaginationLink{} }
func (m *PaginationLink) String() string { return proto.CompactTextString(m) }
func (*PaginationLink) ProtoMessage()    {}
func (*PaginationLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{4}
}
func (m *PaginationLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaginationLink.Unmarshal(m, b)
}
func (m *PaginationLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaginationLink.Marshal(b, m, deterministic)
}
func (dst *PaginationLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginationLink.Merge(dst, src)
}
func (m *PaginationLink) XXX_Size() int {
	return xxx_messageInfo_PaginationLink.Size(m)
}
func (m *PaginationLink) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginationLink.DiscardUnknown(m)
}

var xxx_messageInfo_PaginationLink proto.InternalMessageInfo

func (m *PaginationLink) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *PaginationLink) GetIsLinked() bool {
	if m != nil {
		return m.IsLinked
	}
	return false
}

func (m *PaginationLink) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

type ScrollPager struct {
	// scrollID is serialized version SearchRequest
	ScrollID             string   `protobuf:"bytes,1,opt,name=scrollID" json:"scrollID,omitempty"`
	Cursor               int32    `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
	Total                int64    `protobuf:"varint,3,opt,name=total" json:"total,omitempty"`
	Rows                 int32    `protobuf:"varint,4,opt,name=rows" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScrollPager) Reset()         { *m = ScrollPager{} }
func (m *ScrollPager) String() string { return proto.CompactTextString(m) }
func (*ScrollPager) ProtoMessage()    {}
func (*ScrollPager) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{5}
}
func (m *ScrollPager) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScrollPager.Unmarshal(m, b)
}
func (m *ScrollPager) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScrollPager.Marshal(b, m, deterministic)
}
func (dst *ScrollPager) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScrollPager.Merge(dst, src)
}
func (m *ScrollPager) XXX_Size() int {
	return xxx_messageInfo_ScrollPager.Size(m)
}
func (m *ScrollPager) XXX_DiscardUnknown() {
	xxx_messageInfo_ScrollPager.DiscardUnknown(m)
}

var xxx_messageInfo_ScrollPager proto.InternalMessageInfo

func (m *ScrollPager) GetScrollID() string {
	if m != nil {
		return m.ScrollID
	}
	return ""
}

func (m *ScrollPager) GetCursor() int32 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

func (m *ScrollPager) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ScrollPager) GetRows() int32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

type Pagination struct {
	Start                int32             `protobuf:"varint,1,opt,name=start" json:"start,omitempty"`
	Rows                 int32             `protobuf:"varint,2,opt,name=rows" json:"rows,omitempty"`
	NumFound             int32             `protobuf:"varint,3,opt,name=numFound" json:"numFound,omitempty"`
	HasNext              bool              `protobuf:"varint,4,opt,name=hasNext" json:"hasNext,omitempty"`
	NextPage             int32             `protobuf:"varint,5,opt,name=nextPage" json:"nextPage,omitempty"`
	HasPrevious          bool              `protobuf:"varint,6,opt,name=hasPrevious" json:"hasPrevious,omitempty"`
	PreviousPage         int32             `protobuf:"varint,7,opt,name=previousPage" json:"previousPage,omitempty"`
	CurrentPage          int32             `protobuf:"varint,8,opt,name=currentPage" json:"currentPage,omitempty"`
	Links                []*PaginationLink `protobuf:"bytes,9,rep,name=links" json:"links,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{6}
}
func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (dst *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(dst, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Pagination) GetRows() int32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

func (m *Pagination) GetNumFound() int32 {
	if m != nil {
		return m.NumFound
	}
	return 0
}

func (m *Pagination) GetHasNext() bool {
	if m != nil {
		return m.HasNext
	}
	return false
}

func (m *Pagination) GetNextPage() int32 {
	if m != nil {
		return m.NextPage
	}
	return 0
}

func (m *Pagination) GetHasPrevious() bool {
	if m != nil {
		return m.HasPrevious
	}
	return false
}

func (m *Pagination) GetPreviousPage() int32 {
	if m != nil {
		return m.PreviousPage
	}
	return 0
}

func (m *Pagination) GetCurrentPage() int32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *Pagination) GetLinks() []*PaginationLink {
	if m != nil {
		return m.Links
	}
	return nil
}

type Query struct {
	Numfound             int32         `protobuf:"varint,1,opt,name=numfound" json:"numfound,omitempty"`
	Terms                string        `protobuf:"bytes,2,opt,name=terms" json:"terms,omitempty"`
	BreadCrumbs          []*BreadCrumb `protobuf:"bytes,3,rep,name=breadCrumbs" json:"breadCrumbs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{7}
}
func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (dst *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(dst, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetNumfound() int32 {
	if m != nil {
		return m.Numfound
	}
	return 0
}

func (m *Query) GetTerms() string {
	if m != nil {
		return m.Terms
	}
	return ""
}

func (m *Query) GetBreadCrumbs() []*BreadCrumb {
	if m != nil {
		return m.BreadCrumbs
	}
	return nil
}

type Facet struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	IsSelected           bool        `protobuf:"varint,2,opt,name=isSelected" json:"isSelected,omitempty"`
	I18N                 string      `protobuf:"bytes,3,opt,name=i18n" json:"i18n,omitempty"`
	Total                int32       `protobuf:"varint,4,opt,name=total" json:"total,omitempty"`
	MissingDocs          int32       `protobuf:"varint,5,opt,name=missingDocs" json:"missingDocs,omitempty"`
	OtherDocs            int32       `protobuf:"varint,6,opt,name=otherDocs" json:"otherDocs,omitempty"`
	Links                []*FaceLink `protobuf:"bytes,7,rep,name=links" json:"links,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Facet) Reset()         { *m = Facet{} }
func (m *Facet) String() string { return proto.CompactTextString(m) }
func (*Facet) ProtoMessage()    {}
func (*Facet) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{8}
}
func (m *Facet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Facet.Unmarshal(m, b)
}
func (m *Facet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Facet.Marshal(b, m, deterministic)
}
func (dst *Facet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Facet.Merge(dst, src)
}
func (m *Facet) XXX_Size() int {
	return xxx_messageInfo_Facet.Size(m)
}
func (m *Facet) XXX_DiscardUnknown() {
	xxx_messageInfo_Facet.DiscardUnknown(m)
}

var xxx_messageInfo_Facet proto.InternalMessageInfo

func (m *Facet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Facet) GetIsSelected() bool {
	if m != nil {
		return m.IsSelected
	}
	return false
}

func (m *Facet) GetI18N() string {
	if m != nil {
		return m.I18N
	}
	return ""
}

func (m *Facet) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Facet) GetMissingDocs() int32 {
	if m != nil {
		return m.MissingDocs
	}
	return 0
}

func (m *Facet) GetOtherDocs() int32 {
	if m != nil {
		return m.OtherDocs
	}
	return 0
}

func (m *Facet) GetLinks() []*FaceLink {
	if m != nil {
		return m.Links
	}
	return nil
}

type FaceLink struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	IsSelected           bool     `protobuf:"varint,2,opt,name=isSelected" json:"isSelected,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	Count                int32    `protobuf:"varint,4,opt,name=count" json:"count,omitempty"`
	DisplayString        string   `protobuf:"bytes,5,opt,name=displayString" json:"displayString,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FaceLink) Reset()         { *m = FaceLink{} }
func (m *FaceLink) String() string { return proto.CompactTextString(m) }
func (*FaceLink) ProtoMessage()    {}
func (*FaceLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{9}
}
func (m *FaceLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FaceLink.Unmarshal(m, b)
}
func (m *FaceLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FaceLink.Marshal(b, m, deterministic)
}
func (dst *FaceLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaceLink.Merge(dst, src)
}
func (m *FaceLink) XXX_Size() int {
	return xxx_messageInfo_FaceLink.Size(m)
}
func (m *FaceLink) XXX_DiscardUnknown() {
	xxx_messageInfo_FaceLink.DiscardUnknown(m)
}

var xxx_messageInfo_FaceLink proto.InternalMessageInfo

func (m *FaceLink) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *FaceLink) GetIsSelected() bool {
	if m != nil {
		return m.IsSelected
	}
	return false
}

func (m *FaceLink) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *FaceLink) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *FaceLink) GetDisplayString() string {
	if m != nil {
		return m.DisplayString
	}
	return ""
}

type SearchResultWrapperV3 struct {
	Result               *SearchResultV3 `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SearchResultWrapperV3) Reset()         { *m = SearchResultWrapperV3{} }
func (m *SearchResultWrapperV3) String() string { return proto.CompactTextString(m) }
func (*SearchResultWrapperV3) ProtoMessage()    {}
func (*SearchResultWrapperV3) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{10}
}
func (m *SearchResultWrapperV3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResultWrapperV3.Unmarshal(m, b)
}
func (m *SearchResultWrapperV3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResultWrapperV3.Marshal(b, m, deterministic)
}
func (dst *SearchResultWrapperV3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResultWrapperV3.Merge(dst, src)
}
func (m *SearchResultWrapperV3) XXX_Size() int {
	return xxx_messageInfo_SearchResultWrapperV3.Size(m)
}
func (m *SearchResultWrapperV3) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResultWrapperV3.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResultWrapperV3 proto.InternalMessageInfo

func (m *SearchResultWrapperV3) GetResult() *SearchResultV3 {
	if m != nil {
		return m.Result
	}
	return nil
}

// Full SearchResult
type SearchResultV3 struct {
	Query                *Query           `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	Request              *SearchRequest   `protobuf:"bytes,2,opt,name=request" json:"request,omitempty"`
	Pagination           *Pagination      `protobuf:"bytes,3,opt,name=pagination" json:"pagination,omitempty"`
	Items                []*FragmentGraph `protobuf:"bytes,4,rep,name=items" json:"items,omitempty"`
	Facets               []*Facet         `protobuf:"bytes,5,rep,name=facets" json:"facets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SearchResultV3) Reset()         { *m = SearchResultV3{} }
func (m *SearchResultV3) String() string { return proto.CompactTextString(m) }
func (*SearchResultV3) ProtoMessage()    {}
func (*SearchResultV3) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{11}
}
func (m *SearchResultV3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResultV3.Unmarshal(m, b)
}
func (m *SearchResultV3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResultV3.Marshal(b, m, deterministic)
}
func (dst *SearchResultV3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResultV3.Merge(dst, src)
}
func (m *SearchResultV3) XXX_Size() int {
	return xxx_messageInfo_SearchResultV3.Size(m)
}
func (m *SearchResultV3) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResultV3.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResultV3 proto.InternalMessageInfo

func (m *SearchResultV3) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *SearchResultV3) GetRequest() *SearchRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *SearchResultV3) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *SearchResultV3) GetItems() []*FragmentGraph {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *SearchResultV3) GetFacets() []*Facet {
	if m != nil {
		return m.Facets
	}
	return nil
}

type ScrollResultV3 struct {
	Pager                *ScrollPager     `protobuf:"bytes,1,opt,name=pager" json:"pager,omitempty"`
	Items                []*FragmentGraph `protobuf:"bytes,5,rep,name=items" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ScrollResultV3) Reset()         { *m = ScrollResultV3{} }
func (m *ScrollResultV3) String() string { return proto.CompactTextString(m) }
func (*ScrollResultV3) ProtoMessage()    {}
func (*ScrollResultV3) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{12}
}
func (m *ScrollResultV3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScrollResultV3.Unmarshal(m, b)
}
func (m *ScrollResultV3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScrollResultV3.Marshal(b, m, deterministic)
}
func (dst *ScrollResultV3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScrollResultV3.Merge(dst, src)
}
func (m *ScrollResultV3) XXX_Size() int {
	return xxx_messageInfo_ScrollResultV3.Size(m)
}
func (m *ScrollResultV3) XXX_DiscardUnknown() {
	xxx_messageInfo_ScrollResultV3.DiscardUnknown(m)
}

var xxx_messageInfo_ScrollResultV3 proto.InternalMessageInfo

func (m *ScrollResultV3) GetPager() *ScrollPager {
	if m != nil {
		return m.Pager
	}
	return nil
}

func (m *ScrollResultV3) GetItems() []*FragmentGraph {
	if m != nil {
		return m.Items
	}
	return nil
}

type MetadataFieldV1 struct {
	Field                []string `protobuf:"bytes,1,rep,name=field" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetadataFieldV1) Reset()         { *m = MetadataFieldV1{} }
func (m *MetadataFieldV1) String() string { return proto.CompactTextString(m) }
func (*MetadataFieldV1) ProtoMessage()    {}
func (*MetadataFieldV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{13}
}
func (m *MetadataFieldV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetadataFieldV1.Unmarshal(m, b)
}
func (m *MetadataFieldV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetadataFieldV1.Marshal(b, m, deterministic)
}
func (dst *MetadataFieldV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataFieldV1.Merge(dst, src)
}
func (m *MetadataFieldV1) XXX_Size() int {
	return xxx_messageInfo_MetadataFieldV1.Size(m)
}
func (m *MetadataFieldV1) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataFieldV1.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataFieldV1 proto.InternalMessageInfo

func (m *MetadataFieldV1) GetField() []string {
	if m != nil {
		return m.Field
	}
	return nil
}

type MetadataItemV1 struct {
	DocId                string                      `protobuf:"bytes,1,opt,name=doc_id,json=docId" json:"doc_id,omitempty"`
	DocType              string                      `protobuf:"bytes,2,opt,name=doc_type,json=docType" json:"doc_type,omitempty"`
	Fields               map[string]*MetadataFieldV1 `protobuf:"bytes,3,rep,name=fields" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *MetadataItemV1) Reset()         { *m = MetadataItemV1{} }
func (m *MetadataItemV1) String() string { return proto.CompactTextString(m) }
func (*MetadataItemV1) ProtoMessage()    {}
func (*MetadataItemV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{14}
}
func (m *MetadataItemV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetadataItemV1.Unmarshal(m, b)
}
func (m *MetadataItemV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetadataItemV1.Marshal(b, m, deterministic)
}
func (dst *MetadataItemV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataItemV1.Merge(dst, src)
}
func (m *MetadataItemV1) XXX_Size() int {
	return xxx_messageInfo_MetadataItemV1.Size(m)
}
func (m *MetadataItemV1) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataItemV1.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataItemV1 proto.InternalMessageInfo

func (m *MetadataItemV1) GetDocId() string {
	if m != nil {
		return m.DocId
	}
	return ""
}

func (m *MetadataItemV1) GetDocType() string {
	if m != nil {
		return m.DocType
	}
	return ""
}

func (m *MetadataItemV1) GetFields() map[string]*MetadataFieldV1 {
	if m != nil {
		return m.Fields
	}
	return nil
}

type SearchResultWrapperV1 struct {
	Result               *SearchResultV1 `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SearchResultWrapperV1) Reset()         { *m = SearchResultWrapperV1{} }
func (m *SearchResultWrapperV1) String() string { return proto.CompactTextString(m) }
func (*SearchResultWrapperV1) ProtoMessage()    {}
func (*SearchResultWrapperV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{15}
}
func (m *SearchResultWrapperV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResultWrapperV1.Unmarshal(m, b)
}
func (m *SearchResultWrapperV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResultWrapperV1.Marshal(b, m, deterministic)
}
func (dst *SearchResultWrapperV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResultWrapperV1.Merge(dst, src)
}
func (m *SearchResultWrapperV1) XXX_Size() int {
	return xxx_messageInfo_SearchResultWrapperV1.Size(m)
}
func (m *SearchResultWrapperV1) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResultWrapperV1.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResultWrapperV1 proto.InternalMessageInfo

func (m *SearchResultWrapperV1) GetResult() *SearchResultV1 {
	if m != nil {
		return m.Result
	}
	return nil
}

// Full SearchResult
type SearchResultV1 struct {
	Query                *Query            `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	Pagination           *Pagination       `protobuf:"bytes,2,opt,name=pagination" json:"pagination,omitempty"`
	Items                []*MetadataItemV1 `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"`
	Facets               []*Facet          `protobuf:"bytes,4,rep,name=facets" json:"facets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SearchResultV1) Reset()         { *m = SearchResultV1{} }
func (m *SearchResultV1) String() string { return proto.CompactTextString(m) }
func (*SearchResultV1) ProtoMessage()    {}
func (*SearchResultV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{16}
}
func (m *SearchResultV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResultV1.Unmarshal(m, b)
}
func (m *SearchResultV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResultV1.Marshal(b, m, deterministic)
}
func (dst *SearchResultV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResultV1.Merge(dst, src)
}
func (m *SearchResultV1) XXX_Size() int {
	return xxx_messageInfo_SearchResultV1.Size(m)
}
func (m *SearchResultV1) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResultV1.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResultV1 proto.InternalMessageInfo

func (m *SearchResultV1) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *SearchResultV1) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *SearchResultV1) GetItems() []*MetadataItemV1 {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *SearchResultV1) GetFacets() []*Facet {
	if m != nil {
		return m.Facets
	}
	return nil
}

// The structure of the detail page
type DetailResult struct {
	Item                 *MetadataItemV1 `protobuf:"bytes,1,opt,name=item" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DetailResult) Reset()         { *m = DetailResult{} }
func (m *DetailResult) String() string { return proto.CompactTextString(m) }
func (*DetailResult) ProtoMessage()    {}
func (*DetailResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{17}
}
func (m *DetailResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailResult.Unmarshal(m, b)
}
func (m *DetailResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailResult.Marshal(b, m, deterministic)
}
func (dst *DetailResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailResult.Merge(dst, src)
}
func (m *DetailResult) XXX_Size() int {
	return xxx_messageInfo_DetailResult.Size(m)
}
func (m *DetailResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailResult.DiscardUnknown(m)
}

var xxx_messageInfo_DetailResult proto.InternalMessageInfo

func (m *DetailResult) GetItem() *MetadataItemV1 {
	if m != nil {
		return m.Item
	}
	return nil
}

type FragmentSearchResponse struct {
	Request              *FragmentRequest `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	NrTriples            int32            `protobuf:"varint,2,opt,name=nrTriples" json:"nrTriples,omitempty"`
	Page                 int32            `protobuf:"varint,3,opt,name=page" json:"page,omitempty"`
	Fragments            []*Fragment      `protobuf:"bytes,4,rep,name=fragments" json:"fragments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FragmentSearchResponse) Reset()         { *m = FragmentSearchResponse{} }
func (m *FragmentSearchResponse) String() string { return proto.CompactTextString(m) }
func (*FragmentSearchResponse) ProtoMessage()    {}
func (*FragmentSearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{18}
}
func (m *FragmentSearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FragmentSearchResponse.Unmarshal(m, b)
}
func (m *FragmentSearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FragmentSearchResponse.Marshal(b, m, deterministic)
}
func (dst *FragmentSearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FragmentSearchResponse.Merge(dst, src)
}
func (m *FragmentSearchResponse) XXX_Size() int {
	return xxx_messageInfo_FragmentSearchResponse.Size(m)
}
func (m *FragmentSearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FragmentSearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FragmentSearchResponse proto.InternalMessageInfo

func (m *FragmentSearchResponse) GetRequest() *FragmentRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *FragmentSearchResponse) GetNrTriples() int32 {
	if m != nil {
		return m.NrTriples
	}
	return 0
}

func (m *FragmentSearchResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *FragmentSearchResponse) GetFragments() []*Fragment {
	if m != nil {
		return m.Fragments
	}
	return nil
}

type FragmentUpdateResponse struct {
	GraphsStored         int32            `protobuf:"varint,1,opt,name=graphsStored" json:"graphsStored,omitempty"`
	Spec                 string           `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
	HasErrors            bool             `protobuf:"varint,3,opt,name=hasErrors" json:"hasErrors,omitempty"`
	Errors               []*FragmentError `protobuf:"bytes,4,rep,name=errors" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FragmentUpdateResponse) Reset()         { *m = FragmentUpdateResponse{} }
func (m *FragmentUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*FragmentUpdateResponse) ProtoMessage()    {}
func (*FragmentUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{19}
}
func (m *FragmentUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FragmentUpdateResponse.Unmarshal(m, b)
}
func (m *FragmentUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FragmentUpdateResponse.Marshal(b, m, deterministic)
}
func (dst *FragmentUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FragmentUpdateResponse.Merge(dst, src)
}
func (m *FragmentUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_FragmentUpdateResponse.Size(m)
}
func (m *FragmentUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FragmentUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FragmentUpdateResponse proto.InternalMessageInfo

func (m *FragmentUpdateResponse) GetGraphsStored() int32 {
	if m != nil {
		return m.GraphsStored
	}
	return 0
}

func (m *FragmentUpdateResponse) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

func (m *FragmentUpdateResponse) GetHasErrors() bool {
	if m != nil {
		return m.HasErrors
	}
	return false
}

func (m *FragmentUpdateResponse) GetErrors() []*FragmentError {
	if m != nil {
		return m.Errors
	}
	return nil
}

type FragmentError struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FragmentError) Reset()         { *m = FragmentError{} }
func (m *FragmentError) String() string { return proto.CompactTextString(m) }
func (*FragmentError) ProtoMessage()    {}
func (*FragmentError) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{20}
}
func (m *FragmentError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FragmentError.Unmarshal(m, b)
}
func (m *FragmentError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FragmentError.Marshal(b, m, deterministic)
}
func (dst *FragmentError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FragmentError.Merge(dst, src)
}
func (m *FragmentError) XXX_Size() int {
	return xxx_messageInfo_FragmentError.Size(m)
}
func (m *FragmentError) XXX_DiscardUnknown() {
	xxx_messageInfo_FragmentError.DiscardUnknown(m)
}

var xxx_messageInfo_FragmentError proto.InternalMessageInfo

type FragmentRequest struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject" json:"subject,omitempty"`
	Predicate            string   `protobuf:"bytes,2,opt,name=predicate" json:"predicate,omitempty"`
	Object               string   `protobuf:"bytes,3,opt,name=object" json:"object,omitempty"`
	Page                 int32    `protobuf:"varint,4,opt,name=page" json:"page,omitempty"`
	Language             string   `protobuf:"bytes,5,opt,name=language" json:"language,omitempty"`
	OrgID                string   `protobuf:"bytes,6,opt,name=orgID" json:"orgID,omitempty"`
	Graph                string   `protobuf:"bytes,7,opt,name=graph" json:"graph,omitempty"`
	Spec                 string   `protobuf:"bytes,8,opt,name=spec" json:"spec,omitempty"`
	Echo                 string   `protobuf:"bytes,9,opt,name=echo" json:"echo,omitempty"`
	LodKey               string   `protobuf:"bytes,10,opt,name=lodKey" json:"lodKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FragmentRequest) Reset()         { *m = FragmentRequest{} }
func (m *FragmentRequest) String() string { return proto.CompactTextString(m) }
func (*FragmentRequest) ProtoMessage()    {}
func (*FragmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{21}
}
func (m *FragmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FragmentRequest.Unmarshal(m, b)
}
func (m *FragmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FragmentRequest.Marshal(b, m, deterministic)
}
func (dst *FragmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FragmentRequest.Merge(dst, src)
}
func (m *FragmentRequest) XXX_Size() int {
	return xxx_messageInfo_FragmentRequest.Size(m)
}
func (m *FragmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FragmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FragmentRequest proto.InternalMessageInfo

func (m *FragmentRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *FragmentRequest) GetPredicate() string {
	if m != nil {
		return m.Predicate
	}
	return ""
}

func (m *FragmentRequest) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *FragmentRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *FragmentRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *FragmentRequest) GetOrgID() string {
	if m != nil {
		return m.OrgID
	}
	return ""
}

func (m *FragmentRequest) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

func (m *FragmentRequest) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

func (m *FragmentRequest) GetEcho() string {
	if m != nil {
		return m.Echo
	}
	return ""
}

func (m *FragmentRequest) GetLodKey() string {
	if m != nil {
		return m.LodKey
	}
	return ""
}

type FragmentGraph struct {
	Meta                 *Header          `protobuf:"bytes,1,opt,name=meta" json:"meta,omitempty"`
	EntryURI             string           `protobuf:"bytes,2,opt,name=entryURI" json:"entryURI,omitempty"`
	NamedGraphURI        string           `protobuf:"bytes,3,opt,name=namedGraphURI" json:"namedGraphURI,omitempty"`
	RecordType           RecordType       `protobuf:"varint,4,opt,name=recordType,enum=fragments.RecordType" json:"recordType,omitempty"`
	Fragments            []*Fragment      `protobuf:"bytes,5,rep,name=fragments" json:"fragments,omitempty"`
	Summary              []*ResultSummary `protobuf:"bytes,6,rep,name=summary" json:"summary,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FragmentGraph) Reset()         { *m = FragmentGraph{} }
func (m *FragmentGraph) String() string { return proto.CompactTextString(m) }
func (*FragmentGraph) ProtoMessage()    {}
func (*FragmentGraph) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{22}
}
func (m *FragmentGraph) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FragmentGraph.Unmarshal(m, b)
}
func (m *FragmentGraph) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FragmentGraph.Marshal(b, m, deterministic)
}
func (dst *FragmentGraph) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FragmentGraph.Merge(dst, src)
}
func (m *FragmentGraph) XXX_Size() int {
	return xxx_messageInfo_FragmentGraph.Size(m)
}
func (m *FragmentGraph) XXX_DiscardUnknown() {
	xxx_messageInfo_FragmentGraph.DiscardUnknown(m)
}

var xxx_messageInfo_FragmentGraph proto.InternalMessageInfo

func (m *FragmentGraph) GetMeta() *Header {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *FragmentGraph) GetEntryURI() string {
	if m != nil {
		return m.EntryURI
	}
	return ""
}

func (m *FragmentGraph) GetNamedGraphURI() string {
	if m != nil {
		return m.NamedGraphURI
	}
	return ""
}

func (m *FragmentGraph) GetRecordType() RecordType {
	if m != nil {
		return m.RecordType
	}
	return RecordType_NARTHEX
}

func (m *FragmentGraph) GetFragments() []*Fragment {
	if m != nil {
		return m.Fragments
	}
	return nil
}

func (m *FragmentGraph) GetSummary() []*ResultSummary {
	if m != nil {
		return m.Summary
	}
	return nil
}

type ResultSummary struct {
	Title                string   `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner" json:"owner,omitempty"`
	DatasetTitle         string   `protobuf:"bytes,3,opt,name=datasetTitle" json:"datasetTitle,omitempty"`
	Thumbnail            string   `protobuf:"bytes,4,opt,name=thumbnail" json:"thumbnail,omitempty"`
	LandingPage          string   `protobuf:"bytes,5,opt,name=landingPage" json:"landingPage,omitempty"`
	LatLong              string   `protobuf:"bytes,6,opt,name=latLong" json:"latLong,omitempty"`
	Date                 string   `protobuf:"bytes,7,opt,name=date" json:"date,omitempty"`
	Description          string   `protobuf:"bytes,8,opt,name=description" json:"description,omitempty"`
	Subject              string   `protobuf:"bytes,9,opt,name=subject" json:"subject,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultSummary) Reset()         { *m = ResultSummary{} }
func (m *ResultSummary) String() string { return proto.CompactTextString(m) }
func (*ResultSummary) ProtoMessage()    {}
func (*ResultSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{23}
}
func (m *ResultSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultSummary.Unmarshal(m, b)
}
func (m *ResultSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultSummary.Marshal(b, m, deterministic)
}
func (dst *ResultSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultSummary.Merge(dst, src)
}
func (m *ResultSummary) XXX_Size() int {
	return xxx_messageInfo_ResultSummary.Size(m)
}
func (m *ResultSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultSummary.DiscardUnknown(m)
}

var xxx_messageInfo_ResultSummary proto.InternalMessageInfo

func (m *ResultSummary) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ResultSummary) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ResultSummary) GetDatasetTitle() string {
	if m != nil {
		return m.DatasetTitle
	}
	return ""
}

func (m *ResultSummary) GetThumbnail() string {
	if m != nil {
		return m.Thumbnail
	}
	return ""
}

func (m *ResultSummary) GetLandingPage() string {
	if m != nil {
		return m.LandingPage
	}
	return ""
}

func (m *ResultSummary) GetLatLong() string {
	if m != nil {
		return m.LatLong
	}
	return ""
}

func (m *ResultSummary) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *ResultSummary) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ResultSummary) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

type Header struct {
	// The tenant identifier for this RecordType.
	OrgID string `protobuf:"bytes,1,opt,name=orgID" json:"orgID,omitempty"`
	// The spec is the unique dataset string to identify which dataset  this
	// Fragment belongs to
	Spec string `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
	// The revision is used to determine which version is an orphan and should be removed
	Revision int32 `protobuf:"varint,3,opt,name=revision" json:"revision,omitempty"`
	// The hubId is the unique identifier for any document record in hub3
	HubID string `protobuf:"bytes,4,opt,name=hubID" json:"hubID,omitempty"`
	// Each fragment can be tagged with additional metadata. This can be queried for.
	// Some examples are 'resource', 'literal', 'bnode', 'rdfType', etc.
	Tags []string `protobuf:"bytes,5,rep,name=tags" json:"tags,omitempty"`
	// The document type for ElasticSearch. This is a constant value
	DocType              string   `protobuf:"bytes,6,opt,name=docType" json:"docType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{24}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (dst *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(dst, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetOrgID() string {
	if m != nil {
		return m.OrgID
	}
	return ""
}

func (m *Header) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

func (m *Header) GetRevision() int32 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *Header) GetHubID() string {
	if m != nil {
		return m.HubID
	}
	return ""
}

func (m *Header) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Header) GetDocType() string {
	if m != nil {
		return m.DocType
	}
	return ""
}

// Fragment are used and stored in ElasticSearch for the Linked Data Fragments
// API
type Fragment struct {
	// Generic Header for all ElasticSearch records
	Meta *Header `protobuf:"bytes,1,opt,name=meta" json:"meta,omitempty"`
	// RDF core
	// URI of the Triple subject
	Subject string `protobuf:"bytes,7,opt,name=subject" json:"subject,omitempty"`
	// URI of the Triple predicate
	Predicate string `protobuf:"bytes,8,opt,name=predicate" json:"predicate,omitempty"`
	// An underscore delimited version of the namespace and the label of the URI
	// This is used in the Search DSL, for example dc:title becomes dc_title
	SearchLabel string `protobuf:"bytes,9,opt,name=searchLabel" json:"searchLabel,omitempty"`
	// The triple object. Can be both literal or resource (including Blank Nodes)
	Object string `protobuf:"bytes,10,opt,name=object" json:"object,omitempty"`
	// ISO 693 represenation of language code
	Language string `protobuf:"bytes,11,opt,name=language" json:"language,omitempty"`
	// Human readable version of the xsd:dataType
	DataType string `protobuf:"bytes,12,opt,name=dataType" json:"dataType,omitempty"`
	// The n-triples representation of the triple. Used to quickly render
	// RDF from a FragmentQuery
	Triple string `protobuf:"bytes,13,opt,name=triple" json:"triple,omitempty"`
	// The named graph that this triple is part of
	NamedGraphURI string `protobuf:"bytes,14,opt,name=namedGraphURI" json:"namedGraphURI,omitempty"`
	// the relative key that is used to resolve a SPARQL describe for a Subject
	LodKey               string   `protobuf:"bytes,15,opt,name=lodKey" json:"lodKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Fragment) Reset()         { *m = Fragment{} }
func (m *Fragment) String() string { return proto.CompactTextString(m) }
func (*Fragment) ProtoMessage()    {}
func (*Fragment) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{25}
}
func (m *Fragment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fragment.Unmarshal(m, b)
}
func (m *Fragment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fragment.Marshal(b, m, deterministic)
}
func (dst *Fragment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fragment.Merge(dst, src)
}
func (m *Fragment) XXX_Size() int {
	return xxx_messageInfo_Fragment.Size(m)
}
func (m *Fragment) XXX_DiscardUnknown() {
	xxx_messageInfo_Fragment.DiscardUnknown(m)
}

var xxx_messageInfo_Fragment proto.InternalMessageInfo

func (m *Fragment) GetMeta() *Header {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Fragment) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Fragment) GetPredicate() string {
	if m != nil {
		return m.Predicate
	}
	return ""
}

func (m *Fragment) GetSearchLabel() string {
	if m != nil {
		return m.SearchLabel
	}
	return ""
}

func (m *Fragment) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *Fragment) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Fragment) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *Fragment) GetTriple() string {
	if m != nil {
		return m.Triple
	}
	return ""
}

func (m *Fragment) GetNamedGraphURI() string {
	if m != nil {
		return m.NamedGraphURI
	}
	return ""
}

func (m *Fragment) GetLodKey() string {
	if m != nil {
		return m.LodKey
	}
	return ""
}

type FragmentGen1 struct {
	// meta block
	OrgID    string `protobuf:"bytes,1,opt,name=orgID" json:"orgID,omitempty"`
	Spec     string `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
	Revision int32  `protobuf:"varint,3,opt,name=revision" json:"revision,omitempty"`
	HubID    string `protobuf:"bytes,4,opt,name=hubID" json:"hubID,omitempty"`
	// RDF core
	Subject           string        `protobuf:"bytes,5,opt,name=subject" json:"subject,omitempty"`
	SubjectClass      []string      `protobuf:"bytes,6,rep,name=subjectClass" json:"subjectClass,omitempty"`
	Predicate         string        `protobuf:"bytes,7,opt,name=predicate" json:"predicate,omitempty"`
	SearchLabel       string        `protobuf:"bytes,8,opt,name=searchLabel" json:"searchLabel,omitempty"`
	Object            string        `protobuf:"bytes,9,opt,name=object" json:"object,omitempty"`
	ObjectType        ObjectType    `protobuf:"varint,10,opt,name=objectType,enum=fragments.ObjectType" json:"objectType,omitempty"`
	Language          string        `protobuf:"bytes,11,opt,name=language" json:"language,omitempty"`
	ObjectContentType string        `protobuf:"bytes,12,opt,name=objectContentType" json:"objectContentType,omitempty"`
	DataType          ObjectXSDType `protobuf:"varint,13,opt,name=dataType,enum=fragments.ObjectXSDType" json:"dataType,omitempty"`
	XSDRaw            string        `protobuf:"bytes,14,opt,name=XSDRaw" json:"XSDRaw,omitempty"`
	ObjectTypeRaw     string        `protobuf:"bytes,29,opt,name=objectTypeRaw" json:"objectTypeRaw,omitempty"`
	NamedGraphURI     string        `protobuf:"bytes,15,opt,name=namedGraphURI" json:"namedGraphURI,omitempty"`
	Triple            string        `protobuf:"bytes,16,opt,name=triple" json:"triple,omitempty"`
	// RDF graph position
	Level                int32    `protobuf:"varint,17,opt,name=level" json:"level,omitempty"`
	ReferrerSubject      string   `protobuf:"bytes,18,opt,name=referrerSubject" json:"referrerSubject,omitempty"`
	ReferrerPredicate    string   `protobuf:"bytes,19,opt,name=referrerPredicate" json:"referrerPredicate,omitempty"`
	ReferrerSearchLabel  string   `protobuf:"bytes,20,opt,name=referrerSearchLabel" json:"referrerSearchLabel,omitempty"`
	ReferrerSubjectClass []string `protobuf:"bytes,21,rep,name=referrerSubjectClass" json:"referrerSubjectClass,omitempty"`
	// Content Index
	LatLong                   string `protobuf:"bytes,22,opt,name=latLong" json:"latLong,omitempty"`
	Date                      string `protobuf:"bytes,23,opt,name=date" json:"date,omitempty"`
	DateRange                 string `protobuf:"bytes,24,opt,name=dateRange" json:"dateRange,omitempty"`
	Integer                   int32  `protobuf:"varint,25,opt,name=integer" json:"integer,omitempty"`
	IntegerRange              int32  `protobuf:"varint,26,opt,name=integerRange" json:"integerRange,omitempty"`
	ReferrerResourceSortOrder int32  `protobuf:"varint,27,opt,name=referrerResourceSortOrder" json:"referrerResourceSortOrder,omitempty"`
	// content tags
	// example values linkGraphExternal prefLabel linkDomainExternal thumbnail date
	Tags                 []string `protobuf:"bytes,28,rep,name=tags" json:"tags,omitempty"`
	DocType              string   `protobuf:"bytes,30,opt,name=docType" json:"docType,omitempty"`
	LodKey               string   `protobuf:"bytes,31,opt,name=lodKey" json:"lodKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FragmentGen1) Reset()         { *m = FragmentGen1{} }
func (m *FragmentGen1) String() string { return proto.CompactTextString(m) }
func (*FragmentGen1) ProtoMessage()    {}
func (*FragmentGen1) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1b43a261f9bd47f7, []int{26}
}
func (m *FragmentGen1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FragmentGen1.Unmarshal(m, b)
}
func (m *FragmentGen1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FragmentGen1.Marshal(b, m, deterministic)
}
func (dst *FragmentGen1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FragmentGen1.Merge(dst, src)
}
func (m *FragmentGen1) XXX_Size() int {
	return xxx_messageInfo_FragmentGen1.Size(m)
}
func (m *FragmentGen1) XXX_DiscardUnknown() {
	xxx_messageInfo_FragmentGen1.DiscardUnknown(m)
}

var xxx_messageInfo_FragmentGen1 proto.InternalMessageInfo

func (m *FragmentGen1) GetOrgID() string {
	if m != nil {
		return m.OrgID
	}
	return ""
}

func (m *FragmentGen1) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

func (m *FragmentGen1) GetRevision() int32 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *FragmentGen1) GetHubID() string {
	if m != nil {
		return m.HubID
	}
	return ""
}

func (m *FragmentGen1) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *FragmentGen1) GetSubjectClass() []string {
	if m != nil {
		return m.SubjectClass
	}
	return nil
}

func (m *FragmentGen1) GetPredicate() string {
	if m != nil {
		return m.Predicate
	}
	return ""
}

func (m *FragmentGen1) GetSearchLabel() string {
	if m != nil {
		return m.SearchLabel
	}
	return ""
}

func (m *FragmentGen1) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *FragmentGen1) GetObjectType() ObjectType {
	if m != nil {
		return m.ObjectType
	}
	return ObjectType_RESOURCE
}

func (m *FragmentGen1) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *FragmentGen1) GetObjectContentType() string {
	if m != nil {
		return m.ObjectContentType
	}
	return ""
}

func (m *FragmentGen1) GetDataType() ObjectXSDType {
	if m != nil {
		return m.DataType
	}
	return ObjectXSDType_STRING
}

func (m *FragmentGen1) GetXSDRaw() string {
	if m != nil {
		return m.XSDRaw
	}
	return ""
}

func (m *FragmentGen1) GetObjectTypeRaw() string {
	if m != nil {
		return m.ObjectTypeRaw
	}
	return ""
}

func (m *FragmentGen1) GetNamedGraphURI() string {
	if m != nil {
		return m.NamedGraphURI
	}
	return ""
}

func (m *FragmentGen1) GetTriple() string {
	if m != nil {
		return m.Triple
	}
	return ""
}

func (m *FragmentGen1) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *FragmentGen1) GetReferrerSubject() string {
	if m != nil {
		return m.ReferrerSubject
	}
	return ""
}

func (m *FragmentGen1) GetReferrerPredicate() string {
	if m != nil {
		return m.ReferrerPredicate
	}
	return ""
}

func (m *FragmentGen1) GetReferrerSearchLabel() string {
	if m != nil {
		return m.ReferrerSearchLabel
	}
	return ""
}

func (m *FragmentGen1) GetReferrerSubjectClass() []string {
	if m != nil {
		return m.ReferrerSubjectClass
	}
	return nil
}

func (m *FragmentGen1) GetLatLong() string {
	if m != nil {
		return m.LatLong
	}
	return ""
}

func (m *FragmentGen1) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *FragmentGen1) GetDateRange() string {
	if m != nil {
		return m.DateRange
	}
	return ""
}

func (m *FragmentGen1) GetInteger() int32 {
	if m != nil {
		return m.Integer
	}
	return 0
}

func (m *FragmentGen1) GetIntegerRange() int32 {
	if m != nil {
		return m.IntegerRange
	}
	return 0
}

func (m *FragmentGen1) GetReferrerResourceSortOrder() int32 {
	if m != nil {
		return m.ReferrerResourceSortOrder
	}
	return 0
}

func (m *FragmentGen1) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *FragmentGen1) GetDocType() string {
	if m != nil {
		return m.DocType
	}
	return ""
}

func (m *FragmentGen1) GetLodKey() string {
	if m != nil {
		return m.LodKey
	}
	return ""
}

func init() {
	proto.RegisterType((*FilterValue)(nil), "fragments.FilterValue")
	proto.RegisterType((*SearchRequest)(nil), "fragments.SearchRequest")
	proto.RegisterMapType((map[string]*FilterValue)(nil), "fragments.SearchRequest.HiddenQueryFilterEntry")
	proto.RegisterMapType((map[string]*FilterValue)(nil), "fragments.SearchRequest.QueryFilterEntry")
	proto.RegisterType((*DetailRequest)(nil), "fragments.DetailRequest")
	proto.RegisterType((*BreadCrumb)(nil), "fragments.BreadCrumb")
	proto.RegisterType((*PaginationLink)(nil), "fragments.PaginationLink")
	proto.RegisterType((*ScrollPager)(nil), "fragments.ScrollPager")
	proto.RegisterType((*Pagination)(nil), "fragments.Pagination")
	proto.RegisterType((*Query)(nil), "fragments.Query")
	proto.RegisterType((*Facet)(nil), "fragments.Facet")
	proto.RegisterType((*FaceLink)(nil), "fragments.FaceLink")
	proto.RegisterType((*SearchResultWrapperV3)(nil), "fragments.SearchResultWrapperV3")
	proto.RegisterType((*SearchResultV3)(nil), "fragments.SearchResultV3")
	proto.RegisterType((*ScrollResultV3)(nil), "fragments.ScrollResultV3")
	proto.RegisterType((*MetadataFieldV1)(nil), "fragments.MetadataFieldV1")
	proto.RegisterType((*MetadataItemV1)(nil), "fragments.MetadataItemV1")
	proto.RegisterMapType((map[string]*MetadataFieldV1)(nil), "fragments.MetadataItemV1.FieldsEntry")
	proto.RegisterType((*SearchResultWrapperV1)(nil), "fragments.SearchResultWrapperV1")
	proto.RegisterType((*SearchResultV1)(nil), "fragments.SearchResultV1")
	proto.RegisterType((*DetailResult)(nil), "fragments.DetailResult")
	proto.RegisterType((*FragmentSearchResponse)(nil), "fragments.FragmentSearchResponse")
	proto.RegisterType((*FragmentUpdateResponse)(nil), "fragments.FragmentUpdateResponse")
	proto.RegisterType((*FragmentError)(nil), "fragments.FragmentError")
	proto.RegisterType((*FragmentRequest)(nil), "fragments.FragmentRequest")
	proto.RegisterType((*FragmentGraph)(nil), "fragments.FragmentGraph")
	proto.RegisterType((*ResultSummary)(nil), "fragments.ResultSummary")
	proto.RegisterType((*Header)(nil), "fragments.Header")
	proto.RegisterType((*Fragment)(nil), "fragments.Fragment")
	proto.RegisterType((*FragmentGen1)(nil), "fragments.FragmentGen1")
	proto.RegisterEnum("fragments.ResponseFormatType", ResponseFormatType_name, ResponseFormatType_value)
	proto.RegisterEnum("fragments.ItemFormatType", ItemFormatType_name, ItemFormatType_value)
	proto.RegisterEnum("fragments.ResponseBlockType", ResponseBlockType_name, ResponseBlockType_value)
	proto.RegisterEnum("fragments.GeoType", GeoType_name, GeoType_value)
	proto.RegisterEnum("fragments.IdType", IdType_name, IdType_value)
	proto.RegisterEnum("fragments.ObjectType", ObjectType_name, ObjectType_value)
	proto.RegisterEnum("fragments.ObjectXSDType", ObjectXSDType_name, ObjectXSDType_value)
	proto.RegisterEnum("fragments.RecordType", RecordType_name, RecordType_value)
}

func init() { proto.RegisterFile("hub3/fragments/api.proto", fileDescriptor_api_1b43a261f9bd47f7) }

var fileDescriptor_api_1b43a261f9bd47f7 = []byte{
	// 2906 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x59, 0x4b, 0x73, 0x1b, 0xc7,
	0xf1, 0x17, 0xde, 0x40, 0x83, 0x8f, 0xd5, 0x90, 0xa2, 0x56, 0xb4, 0x6c, 0xd3, 0xf8, 0xff, 0x6d,
	0xd3, 0x2c, 0x59, 0x32, 0x29, 0xd9, 0x71, 0x52, 0xf1, 0x01, 0x24, 0x96, 0x20, 0x2c, 0x3c, 0xe8,
	0x01, 0xc0, 0x88, 0xa9, 0xa4, 0x54, 0x4b, 0x60, 0x08, 0x6e, 0xb4, 0xd8, 0x85, 0x67, 0x17, 0xb2,
	0x98, 0x73, 0x2e, 0xb9, 0xe4, 0x90, 0xaa, 0xe4, 0x1c, 0xdf, 0x72, 0x4d, 0xe5, 0x5b, 0xe4, 0x94,
	0x63, 0xae, 0x39, 0xe4, 0x63, 0xa4, 0x2a, 0xd5, 0x33, 0xb3, 0x8b, 0x59, 0x00, 0x94, 0x79, 0x48,
	0x6e, 0xd3, 0x3d, 0x3d, 0x3d, 0xdd, 0x3d, 0xbf, 0xee, 0xe9, 0xd9, 0x05, 0xf3, 0x6a, 0x7a, 0xf1,
	0xf4, 0xc9, 0x25, 0xb7, 0x47, 0x63, 0xe6, 0x85, 0xc1, 0x13, 0x7b, 0xe2, 0x3c, 0x9e, 0x70, 0x3f,
	0xf4, 0x49, 0x29, 0x66, 0x56, 0xfe, 0x0f, 0xca, 0xc7, 0x8e, 0x1b, 0x32, 0x7e, 0x66, 0xbb, 0x53,
	0x46, 0x36, 0x21, 0xf7, 0x1a, 0x07, 0x66, 0x6a, 0x27, 0xb3, 0x5b, 0xa2, 0x92, 0xa8, 0xfc, 0xab,
	0x08, 0xab, 0x5d, 0x66, 0xf3, 0xc1, 0x15, 0x65, 0xdf, 0x4e, 0x59, 0x10, 0xa2, 0xdc, 0xb7, 0x53,
	0xc6, 0xaf, 0xcd, 0xd4, 0x4e, 0x0a, 0xe5, 0x04, 0x41, 0x5a, 0x40, 0x38, 0x0b, 0x26, 0xbe, 0x17,
	0xb0, 0x63, 0x9f, 0x8f, 0xed, 0xb0, 0x77, 0x3d, 0x61, 0x66, 0x7a, 0x27, 0xb5, 0xbb, 0x76, 0xf0,
	0xee, 0xe3, 0x78, 0xd3, 0xc7, 0x74, 0x41, 0x88, 0x2e, 0x59, 0x48, 0x2a, 0xb0, 0x12, 0x71, 0xbb,
	0xce, 0xaf, 0x99, 0x99, 0xd9, 0x49, 0xed, 0xe6, 0x68, 0x82, 0x87, 0x86, 0x04, 0xa1, 0xcd, 0x43,
	0x33, 0x2b, 0x26, 0x25, 0x41, 0x08, 0x64, 0x27, 0xf6, 0x88, 0x99, 0x39, 0xc1, 0x14, 0x63, 0xf2,
	0x1c, 0xca, 0xdf, 0xa0, 0x95, 0xd2, 0x5d, 0x33, 0xbf, 0x93, 0xd9, 0x2d, 0x1f, 0x7c, 0xa2, 0x59,
	0x95, 0xf0, 0xf0, 0xb1, 0x26, 0x6b, 0x79, 0x21, 0xbf, 0xa6, 0xfa, 0x6a, 0xf2, 0x4b, 0xb8, 0x7b,
	0xe2, 0x0c, 0x87, 0xcc, 0xd3, 0x55, 0x16, 0x84, 0xca, 0x27, 0x37, 0xaa, 0x5c, 0x58, 0x21, 0x15,
	0x2f, 0x6a, 0x22, 0x5f, 0x40, 0x61, 0xe8, 0x04, 0xf6, 0x85, 0xcb, 0xcc, 0xe2, 0x4e, 0x66, 0x77,
	0xed, 0xe0, 0xe1, 0x92, 0xe8, 0x1d, 0xba, 0xfe, 0xe0, 0x95, 0x08, 0x5e, 0x24, 0x4c, 0x9e, 0x41,
	0x9e, 0x79, 0x62, 0x59, 0xe9, 0x16, 0xcb, 0x94, 0x2c, 0x79, 0x0f, 0xe0, 0xd8, 0x1e, 0xb0, 0xf0,
	0xd8, 0x61, 0xee, 0xd0, 0x04, 0x71, 0xf2, 0x1a, 0x27, 0x9e, 0x6f, 0x3a, 0x63, 0x27, 0x34, 0xcb,
	0x22, 0xa6, 0x1a, 0x87, 0xfc, 0x3f, 0xac, 0x0a, 0xea, 0xd0, 0xf7, 0x5d, 0x71, 0xe2, 0x2b, 0x3b,
	0xa9, 0xdd, 0x22, 0x4d, 0x32, 0xc9, 0x16, 0xe4, 0x03, 0x9f, 0x87, 0x87, 0xd7, 0xe6, 0xaa, 0xc0,
	0x8c, 0xa2, 0x88, 0x09, 0x85, 0xa6, 0x1d, 0x36, 0x7d, 0x6f, 0x64, 0xae, 0x89, 0x89, 0x88, 0x24,
	0xdb, 0x50, 0xac, 0x39, 0x41, 0x68, 0x7b, 0x03, 0x66, 0xae, 0x8b, 0xa9, 0x98, 0x26, 0x1b, 0x90,
	0x1b, 0x3b, 0xde, 0xcb, 0x37, 0xa6, 0xb1, 0x93, 0xda, 0x4d, 0xd3, 0xec, 0xd8, 0xf1, 0x5e, 0x44,
	0xcc, 0x6b, 0xf3, 0x6e, 0xcc, 0x3c, 0x17, 0x4c, 0xfb, 0xcd, 0xcb, 0x37, 0x26, 0x51, 0x4c, 0xfb,
	0xcd, 0x8b, 0x88, 0x79, 0x6d, 0x6e, 0xc4, 0xcc, 0x73, 0xc4, 0xd2, 0xa5, 0x08, 0xc1, 0xa6, 0x04,
	0xbf, 0x20, 0xc8, 0x23, 0x28, 0x8c, 0x98, 0x2f, 0xfc, 0xba, 0x27, 0x90, 0x4c, 0xb4, 0xa0, 0xd6,
	0xe5, 0x0c, 0x8d, 0x44, 0xc8, 0x2e, 0xac, 0x8b, 0x83, 0xa4, 0xec, 0xd2, 0xf1, 0x18, 0x0a, 0x99,
	0x5b, 0xc2, 0xf4, 0x79, 0x36, 0xd9, 0x81, 0x72, 0x20, 0xe0, 0x51, 0xbd, 0x44, 0xf0, 0xdc, 0x17,
	0x52, 0x3a, 0x8b, 0xfc, 0x18, 0xc0, 0x09, 0xd9, 0x58, 0x66, 0x84, 0x69, 0x8a, 0xcd, 0x1f, 0x68,
	0x9b, 0x37, 0xe2, 0x49, 0x61, 0x83, 0x26, 0xbc, 0x7d, 0x06, 0xc6, 0x3c, 0xce, 0x88, 0x01, 0x99,
	0x57, 0x2c, 0xca, 0x58, 0x1c, 0x92, 0x47, 0x51, 0xb6, 0x63, 0x8a, 0x96, 0x0f, 0xb6, 0x34, 0xdd,
	0x5a, 0x51, 0x50, 0x55, 0xe0, 0x27, 0xe9, 0x2f, 0x53, 0xdb, 0xbf, 0x80, 0xad, 0xe5, 0x28, 0xfe,
	0x6f, 0x68, 0xaf, 0xfc, 0x33, 0x0d, 0xab, 0x35, 0x16, 0xda, 0x8e, 0x1b, 0xd5, 0x99, 0x35, 0x48,
	0x3b, 0x43, 0xa5, 0x34, 0xed, 0x0c, 0x71, 0x97, 0xb1, 0x1b, 0x0a, 0x8d, 0x45, 0x8a, 0x43, 0xf2,
	0x39, 0xe4, 0x2f, 0x65, 0x80, 0x32, 0xb7, 0xa9, 0x33, 0x4a, 0x18, 0xb1, 0x35, 0x76, 0xc3, 0x23,
	0x7f, 0xea, 0x45, 0xa5, 0x23, 0xa6, 0xc9, 0x47, 0xb0, 0x36, 0x76, 0x43, 0x3d, 0xb3, 0x73, 0xc2,
	0x80, 0x39, 0x2e, 0xd6, 0xa7, 0xb1, 0x1b, 0x4a, 0xe2, 0x39, 0xbb, 0x36, 0xf3, 0x42, 0x2a, 0xc1,
	0xc3, 0xdc, 0x08, 0xf4, 0x22, 0x60, 0x16, 0x84, 0x50, 0x92, 0x89, 0x58, 0xe0, 0x2c, 0x98, 0xba,
	0x61, 0xc3, 0x1b, 0xb2, 0x37, 0x66, 0x51, 0x18, 0xa4, 0xb3, 0xc8, 0x43, 0x28, 0x0d, 0x7c, 0xef,
	0x35, 0xe3, 0x68, 0x4e, 0x49, 0xe8, 0x98, 0x31, 0xc8, 0x27, 0x90, 0x77, 0x86, 0x02, 0xa2, 0x20,
	0x82, 0x70, 0x57, 0x47, 0xc9, 0x50, 0x3a, 0x2e, 0x05, 0x2a, 0x7f, 0x4e, 0x01, 0x1c, 0x72, 0x66,
	0x0f, 0x8f, 0xf8, 0x74, 0x7c, 0x81, 0x95, 0xf2, 0x8a, 0xb3, 0x4b, 0x15, 0x62, 0x31, 0xc6, 0x8c,
	0x1c, 0x3a, 0xc1, 0xc4, 0xb5, 0xaf, 0x45, 0xa0, 0x4b, 0x34, 0x22, 0x67, 0x19, 0x92, 0x91, 0x65,
	0x5f, 0x66, 0xc8, 0xc7, 0xb0, 0xee, 0xfa, 0x03, 0xdb, 0x75, 0x02, 0x36, 0x7c, 0x29, 0xe7, 0xb3,
	0x32, 0x60, 0x31, 0x5b, 0x16, 0x92, 0xf8, 0x76, 0x91, 0xf1, 0x94, 0x04, 0xb9, 0x0f, 0x05, 0x27,
	0x78, 0xe9, 0xda, 0x41, 0x28, 0x22, 0x58, 0xa4, 0x79, 0x27, 0x68, 0xda, 0x41, 0x58, 0xb9, 0x80,
	0xb5, 0x53, 0x7b, 0xe4, 0x78, 0x76, 0xe8, 0xf8, 0x5e, 0xd3, 0xf1, 0x5e, 0xcd, 0xaa, 0x7d, 0x4a,
	0xaf, 0xf6, 0xdb, 0x50, 0x74, 0x02, 0x9c, 0x67, 0x43, 0x85, 0x8c, 0x98, 0xc6, 0xda, 0x85, 0xd5,
	0xbf, 0x3d, 0x1d, 0x5f, 0x30, 0xae, 0x6e, 0x10, 0x8d, 0x53, 0x79, 0x05, 0xe5, 0xee, 0x80, 0xfb,
	0xae, 0x7b, 0x6a, 0x8f, 0x18, 0x47, 0x55, 0x81, 0x20, 0x1b, 0x35, 0x15, 0x92, 0x98, 0xc6, 0x02,
	0x36, 0x98, 0xf2, 0xc0, 0xe7, 0x62, 0x93, 0x1c, 0x55, 0x14, 0x1a, 0x15, 0xfa, 0xa1, 0xed, 0x0a,
	0xed, 0x19, 0x2a, 0x09, 0x0c, 0x2c, 0xf7, 0xbf, 0x0b, 0x14, 0xb8, 0xc4, 0xb8, 0xf2, 0x7d, 0x1a,
	0x60, 0xe6, 0xd1, 0x0d, 0xde, 0x44, 0x0b, 0xd3, 0xb3, 0x85, 0x68, 0x96, 0x37, 0x1d, 0x1f, 0xfb,
	0x53, 0x6f, 0xa8, 0x7c, 0x88, 0x69, 0x3c, 0xad, 0x2b, 0x3b, 0x68, 0xb3, 0x37, 0x12, 0xc8, 0x45,
	0x1a, 0x91, 0x62, 0x15, 0x7b, 0x13, 0x9e, 0xce, 0x6e, 0xc2, 0x98, 0x46, 0xc4, 0x5d, 0xd9, 0xc1,
	0x29, 0x67, 0xaf, 0x1d, 0x7f, 0x1a, 0xa8, 0xc0, 0xeb, 0x2c, 0x44, 0xf7, 0x44, 0x8d, 0x85, 0x86,
	0x82, 0xbc, 0x7d, 0x75, 0x1e, 0x6a, 0x19, 0x4c, 0x39, 0x67, 0x9e, 0xdc, 0x44, 0xe1, 0x56, 0x63,
	0x91, 0x27, 0x90, 0x73, 0x1d, 0xef, 0x55, 0x20, 0x2e, 0xa4, 0x72, 0xa2, 0x7c, 0x25, 0xcf, 0x96,
	0x4a, 0xb9, 0x0a, 0x87, 0x9c, 0xc8, 0x31, 0xe5, 0xf3, 0xa5, 0xf0, 0x39, 0x15, 0xfb, 0x2c, 0x68,
	0x11, 0x72, 0xc6, 0xc7, 0x81, 0xc2, 0xa7, 0x24, 0xc8, 0x8f, 0xa0, 0x7c, 0x11, 0x23, 0x3b, 0x30,
	0x33, 0x62, 0xc7, 0x7b, 0xda, 0x8e, 0x33, 0xdc, 0x53, 0x5d, 0xb2, 0xf2, 0xf7, 0x14, 0xe4, 0xc4,
	0x65, 0x85, 0xc1, 0xf7, 0xec, 0x31, 0x8b, 0xd2, 0x01, 0xc7, 0x08, 0x21, 0x27, 0xe8, 0x32, 0x97,
	0x0d, 0xc2, 0x18, 0x60, 0x1a, 0x07, 0xd7, 0x38, 0xfb, 0x5f, 0x7a, 0x2a, 0x27, 0xc4, 0x78, 0x86,
	0x09, 0xd5, 0x96, 0x48, 0x4c, 0xec, 0x40, 0x79, 0xec, 0x04, 0x81, 0xe3, 0x8d, 0x6a, 0xfe, 0x20,
	0x50, 0x67, 0xa2, 0xb3, 0x30, 0xcd, 0xfd, 0xf0, 0x8a, 0x71, 0x31, 0x9f, 0x17, 0xf3, 0x33, 0x06,
	0xf9, 0x24, 0x0a, 0xa6, 0xec, 0x34, 0x36, 0xf4, 0x8a, 0x6a, 0x0f, 0x98, 0x1e, 0xc6, 0xdf, 0xa5,
	0xa0, 0x18, 0xf1, 0xb0, 0x6a, 0x4e, 0xb9, 0x1b, 0xd5, 0xe6, 0x29, 0x77, 0x7f, 0xd0, 0xa7, 0x38,
	0x53, 0x33, 0x7a, 0xa6, 0x6e, 0x42, 0x6e, 0xa0, 0x55, 0x4c, 0x49, 0x60, 0x89, 0x53, 0xf5, 0xa1,
	0x1b, 0x72, 0xc7, 0x1b, 0xa9, 0xec, 0x4e, 0x32, 0x2b, 0x5f, 0xc3, 0xbd, 0xa8, 0x1b, 0xc2, 0xaa,
	0xf6, 0x33, 0x6e, 0x4f, 0x26, 0x8c, 0x9f, 0x3d, 0x25, 0xfb, 0x90, 0x97, 0x85, 0x4e, 0xd8, 0x97,
	0x84, 0x88, 0xbe, 0xe2, 0xec, 0x29, 0x55, 0x82, 0x95, 0x7f, 0xa7, 0x60, 0x2d, 0x39, 0x45, 0x3e,
	0xd2, 0x1b, 0xd2, 0xf2, 0x81, 0xa1, 0x29, 0x91, 0x17, 0xaf, 0x6a, 0x51, 0x0f, 0xa0, 0xc0, 0x55,
	0x25, 0x96, 0xd7, 0x92, 0x79, 0x53, 0xbb, 0x46, 0x23, 0x41, 0xf2, 0xb9, 0xa8, 0x21, 0x0a, 0xab,
	0x22, 0x22, 0x49, 0x58, 0xcd, 0x80, 0x4c, 0x35, 0x41, 0xf2, 0x18, 0x72, 0x78, 0x23, 0x63, 0x09,
	0xc8, 0xcc, 0x6d, 0x74, 0xac, 0x46, 0x75, 0x6e, 0x4f, 0xae, 0xa8, 0x14, 0x23, 0xbb, 0x90, 0xbf,
	0x44, 0x10, 0x22, 0x30, 0x32, 0x73, 0x3e, 0x08, 0x74, 0x52, 0x35, 0x5f, 0xf1, 0x60, 0x4d, 0x16,
	0xad, 0xd8, 0xfd, 0x47, 0x90, 0xc3, 0xa2, 0xc6, 0x95, 0xfb, 0xfa, 0x5d, 0xab, 0x95, 0x37, 0x2a,
	0x85, 0x66, 0x96, 0xe5, 0x6e, 0x65, 0x59, 0xe5, 0x63, 0x58, 0x6f, 0xb1, 0xd0, 0x1e, 0xda, 0xa1,
	0x2d, 0x0a, 0xf9, 0xd9, 0xfe, 0xec, 0x26, 0x48, 0x69, 0xbd, 0x52, 0xe5, 0x1f, 0x29, 0x58, 0x8b,
	0x24, 0xb1, 0x3b, 0x39, 0xdb, 0x27, 0xf7, 0x20, 0x3f, 0xf4, 0x07, 0x2f, 0xe3, 0x5b, 0x3c, 0x37,
	0xf4, 0x07, 0x8d, 0x21, 0x79, 0x00, 0x45, 0x64, 0x87, 0xd1, 0x03, 0x01, 0x2f, 0x19, 0x7f, 0x20,
	0x5a, 0xa8, 0xaf, 0x20, 0x2f, 0xb4, 0x45, 0x19, 0xfc, 0xa1, 0x66, 0x5e, 0x52, 0xf9, 0x63, 0x61,
	0x4d, 0x20, 0xdb, 0x68, 0xb5, 0x68, 0xbb, 0x8f, 0x2f, 0x9a, 0x98, 0xbd, 0xa4, 0x2f, 0xf9, 0x2c,
	0xd9, 0x97, 0x6c, 0x2f, 0x51, 0xaf, 0xbc, 0xd4, 0x7b, 0x93, 0x1b, 0xf0, 0xbb, 0x7f, 0x7b, 0xfc,
	0xee, 0xc7, 0xf8, 0xfd, 0xdb, 0x3c, 0x7e, 0xf7, 0x6f, 0x8d, 0xdf, 0x24, 0x16, 0xd3, 0xb7, 0xc5,
	0xe2, 0x93, 0xe8, 0xc4, 0x33, 0x0b, 0x65, 0x38, 0x19, 0xd2, 0x45, 0x30, 0x66, 0x7f, 0x00, 0x8c,
	0x5f, 0xc1, 0x4a, 0xd4, 0xb3, 0xa1, 0x2f, 0xe4, 0x53, 0xc8, 0xa2, 0x8a, 0x25, 0xd1, 0x98, 0xdb,
	0x49, 0x88, 0x55, 0xfe, 0x9a, 0x82, 0xad, 0x08, 0x74, 0x71, 0x4c, 0x44, 0xd7, 0x46, 0x9e, 0xcd,
	0x72, 0x35, 0xb5, 0x70, 0x54, 0xd1, 0x9a, 0x85, 0x6c, 0x7d, 0x08, 0x25, 0x8f, 0xf7, 0xb8, 0x33,
	0x71, 0x59, 0x74, 0x89, 0xce, 0x18, 0xf1, 0xcb, 0x30, 0xa3, 0xbd, 0x0c, 0xf7, 0x61, 0xf6, 0x20,
	0x56, 0xee, 0x6e, 0x2c, 0xdb, 0x49, 0x7b, 0x36, 0xff, 0x49, 0xb3, 0xba, 0x3f, 0x19, 0xda, 0x21,
	0x8b, 0xad, 0xae, 0xc0, 0xca, 0x08, 0x93, 0x27, 0xe8, 0x86, 0x3e, 0x67, 0xd1, 0xdd, 0x95, 0xe0,
	0xa1, 0x15, 0xc1, 0x84, 0x0d, 0x14, 0xf2, 0xc5, 0x18, 0xed, 0xbe, 0xb2, 0x03, 0x8b, 0x73, 0x9f,
	0x07, 0xc2, 0xbc, 0x22, 0x9d, 0x31, 0xc8, 0x67, 0x90, 0x67, 0x72, 0xea, 0xe6, 0x6a, 0x22, 0x44,
	0xa9, 0x92, 0xab, 0xac, 0xc3, 0x6a, 0x62, 0x02, 0xab, 0xe6, 0xfa, 0x5c, 0xd4, 0xb0, 0x79, 0x08,
	0xa6, 0x17, 0xbf, 0x62, 0x83, 0x50, 0x65, 0x48, 0x44, 0xa2, 0x39, 0x13, 0xce, 0x86, 0xce, 0xc0,
	0x0e, 0xa3, 0x0c, 0x9d, 0x31, 0xb0, 0x17, 0xf2, 0xe5, 0x32, 0x79, 0x41, 0x28, 0x2a, 0x0e, 0x6f,
	0x56, 0x0b, 0xef, 0x36, 0x14, 0x5d, 0xdb, 0x1b, 0x4d, 0xa3, 0x36, 0xa4, 0x44, 0x63, 0x1a, 0xcb,
	0x88, 0xcf, 0x47, 0x8d, 0x9a, 0xea, 0x9d, 0x25, 0x81, 0x5c, 0x11, 0x2e, 0xd5, 0x2c, 0x4b, 0x22,
	0x0e, 0x5a, 0x51, 0x0b, 0x1a, 0x81, 0x2c, 0x1b, 0x5c, 0xf9, 0xaa, 0x23, 0x16, 0x63, 0xb4, 0xcd,
	0xf5, 0x87, 0xd8, 0x90, 0x83, 0xb4, 0x4d, 0x52, 0x95, 0x3f, 0xa6, 0x67, 0x11, 0x11, 0xe5, 0x8d,
	0x7c, 0x08, 0xd9, 0x31, 0x0b, 0x6d, 0x85, 0x2e, 0xbd, 0x69, 0x3e, 0x61, 0xf6, 0x90, 0x71, 0x2a,
	0xa6, 0xd1, 0x01, 0x86, 0xb5, 0xa4, 0x4f, 0x1b, 0x2a, 0x12, 0x31, 0x8d, 0x97, 0x1f, 0x36, 0x09,
	0x43, 0xa1, 0x10, 0x05, 0x64, 0x3c, 0x92, 0x4c, 0xcc, 0x5a, 0xce, 0x06, 0x3e, 0x97, 0x3d, 0x7a,
	0x56, 0xf4, 0xe8, 0xf7, 0x12, 0x0f, 0x95, 0x68, 0x92, 0x6a, 0x82, 0x49, 0x60, 0xe6, 0x6e, 0x03,
	0x4c, 0xbc, 0xdf, 0x82, 0xe9, 0x78, 0x6c, 0xf3, 0x6b, 0xf5, 0x85, 0xc3, 0x4c, 0xbe, 0x87, 0xa6,
	0x6e, 0xd8, 0x95, 0xf3, 0x34, 0x12, 0xac, 0xfc, 0x36, 0x0d, 0xab, 0x89, 0x29, 0xd1, 0xbe, 0x38,
	0xa1, 0x1b, 0xf5, 0x41, 0x92, 0x10, 0x87, 0xf5, 0x9d, 0xc7, 0x78, 0xd4, 0x75, 0x09, 0x02, 0xf1,
	0x8e, 0x49, 0x1d, 0xb0, 0xb0, 0x27, 0x96, 0xc8, 0x00, 0x24, 0x78, 0x08, 0xa6, 0xf0, 0x6a, 0x3a,
	0xbe, 0xf0, 0x6c, 0xc7, 0x55, 0x6f, 0x83, 0x19, 0x03, 0xdb, 0x22, 0xd7, 0xf6, 0x86, 0x8e, 0x37,
	0x3a, 0x9d, 0x61, 0x44, 0x67, 0x21, 0x4c, 0x5d, 0xf5, 0x8d, 0x40, 0x02, 0x25, 0x22, 0x11, 0x00,
	0x98, 0x7d, 0x0a, 0x29, 0x62, 0x8c, 0xfa, 0x86, 0x2c, 0x18, 0x70, 0x67, 0x22, 0x8a, 0xa4, 0xc4,
	0x8b, 0xce, 0xd2, 0x61, 0x5f, 0x4a, 0xc0, 0xbe, 0xf2, 0xfb, 0x14, 0xe4, 0xe5, 0xe1, 0xcf, 0xb0,
	0x99, 0xd2, 0xb1, 0xb9, 0x2c, 0x75, 0xb7, 0xa1, 0x88, 0x5d, 0x71, 0x10, 0xb5, 0x07, 0x39, 0x1a,
	0xd3, 0xa8, 0xe5, 0x6a, 0x7a, 0xd1, 0xa8, 0x29, 0xb7, 0x25, 0x81, 0x5a, 0x42, 0x7b, 0x24, 0x0f,
	0xb5, 0x44, 0xc5, 0x58, 0x3c, 0xbb, 0xe4, 0x15, 0x18, 0x39, 0xa9, 0xc8, 0xca, 0x5f, 0xd2, 0x50,
	0x8c, 0x0e, 0xfb, 0xb6, 0xa0, 0xd5, 0x5c, 0x2c, 0xbc, 0x25, 0xb3, 0x8b, 0xf3, 0x99, 0x1d, 0x7f,
	0x96, 0x68, 0xda, 0x17, 0xcc, 0x55, 0xe1, 0xd1, 0x59, 0x5a, 0xee, 0x43, 0x22, 0xf7, 0xf5, 0x3c,
	0x2f, 0xcf, 0xe5, 0xf9, 0x36, 0x14, 0x11, 0x10, 0xf1, 0xd7, 0xa1, 0x12, 0x8d, 0x69, 0xd4, 0x17,
	0x8a, 0xea, 0x1c, 0x7d, 0x18, 0x92, 0xd4, 0x62, 0x6a, 0xad, 0x2d, 0x4b, 0xad, 0x59, 0xb6, 0xaf,
	0x27, 0xb2, 0xfd, 0x0f, 0x45, 0x58, 0x89, 0xb3, 0x9d, 0x79, 0xfb, 0xff, 0xd3, 0xe3, 0xd4, 0x82,
	0x9d, 0x4b, 0x06, 0xbb, 0x02, 0x2b, 0x6a, 0x78, 0xe4, 0xda, 0x41, 0x20, 0x92, 0xb2, 0x44, 0x13,
	0xbc, 0xe4, 0x81, 0x14, 0x7e, 0xe0, 0x40, 0x8a, 0x6f, 0x3b, 0x90, 0x52, 0xe2, 0x40, 0x3e, 0x07,
	0x90, 0x23, 0xed, 0xcb, 0x80, 0x5e, 0x75, 0x3a, 0xf1, 0x24, 0xd5, 0x04, 0xdf, 0x7a, 0x8e, 0x8f,
	0xe0, 0xae, 0x94, 0x3c, 0xf2, 0xbd, 0x90, 0x79, 0xa1, 0x76, 0xa0, 0x8b, 0x13, 0xe4, 0x99, 0x76,
	0xea, 0xab, 0x62, 0x7b, 0x73, 0x61, 0xfb, 0x17, 0xdd, 0x9a, 0xb0, 0x20, 0x81, 0x87, 0x17, 0xdd,
	0x1a, 0xb5, 0xbf, 0x53, 0x07, 0xae, 0x28, 0xc4, 0xc3, 0xcc, 0x4a, 0x9c, 0x7e, 0x57, 0xe2, 0x21,
	0xc1, 0x5c, 0x44, 0xcd, 0xfa, 0x0d, 0xa8, 0x51, 0x98, 0x33, 0x12, 0x98, 0xdb, 0x84, 0x9c, 0xcb,
	0x5e, 0x33, 0x57, 0x7c, 0x41, 0xcc, 0x51, 0x49, 0x90, 0x5d, 0x58, 0xe7, 0xec, 0x92, 0x71, 0xce,
	0x78, 0x57, 0x1d, 0x33, 0x91, 0x1f, 0xf5, 0xe6, 0xd8, 0x18, 0x9f, 0x88, 0x75, 0x1a, 0x1f, 0xe9,
	0x86, 0x8c, 0xcf, 0xc2, 0x04, 0xf9, 0x0c, 0x36, 0x62, 0x05, 0xda, 0x11, 0x6f, 0x0a, 0xf9, 0x65,
	0x53, 0xe4, 0x00, 0x36, 0xe7, 0xb6, 0x94, 0xb0, 0xba, 0x27, 0x60, 0xb5, 0x74, 0x4e, 0x2f, 0x9e,
	0x5b, 0xcb, 0x8b, 0xe7, 0x7d, 0xad, 0x78, 0x3e, 0x84, 0x92, 0x68, 0x67, 0x6c, 0x6f, 0xc4, 0xc4,
	0x37, 0xc7, 0x12, 0x9d, 0x31, 0x50, 0x97, 0xe3, 0x85, 0x0c, 0x5f, 0x1a, 0x0f, 0x44, 0x84, 0x22,
	0x12, 0x81, 0xae, 0x86, 0x72, 0xe9, 0xb6, 0x6c, 0x7b, 0x74, 0x1e, 0xf9, 0x29, 0x3c, 0x88, 0x2c,
	0xa4, 0x2c, 0xf0, 0xa7, 0x7c, 0xc0, 0xba, 0x3e, 0x0f, 0x3b, 0x7c, 0xc8, 0xb8, 0xf9, 0x8e, 0x58,
	0x70, 0xb3, 0x40, 0x5c, 0x33, 0x1f, 0x2e, 0xaf, 0x99, 0xef, 0x25, 0x5f, 0x11, 0xb3, 0xba, 0xf0,
	0xbe, 0x5e, 0x17, 0xf6, 0x38, 0x90, 0xc5, 0xcf, 0x82, 0xa4, 0x08, 0xd9, 0xaf, 0xbb, 0x9d, 0xb6,
	0x71, 0x87, 0xac, 0x40, 0xf1, 0x94, 0x76, 0x7a, 0x9d, 0xc3, 0xfe, 0xb1, 0x91, 0x22, 0x05, 0xc8,
	0xbc, 0x68, 0x35, 0x8d, 0x34, 0x29, 0x41, 0x0e, 0x05, 0x4e, 0x8d, 0x0c, 0xf2, 0x9e, 0xb7, 0x9a,
	0x46, 0x96, 0xac, 0x01, 0xd4, 0xad, 0xce, 0x51, 0xb3, 0xdf, 0xed, 0x59, 0xd4, 0xc8, 0x91, 0x32,
	0x14, 0xea, 0x56, 0x47, 0xe8, 0xc9, 0x13, 0x80, 0x7c, 0xdd, 0x12, 0x5a, 0x0a, 0x7b, 0x0d, 0x58,
	0x4b, 0x7e, 0xab, 0x45, 0xd1, 0x6e, 0xbf, 0xd5, 0xaa, 0xd2, 0x73, 0xe3, 0x0e, 0xb9, 0x0b, 0xab,
	0xc7, 0xb4, 0x5a, 0x6f, 0x59, 0xed, 0x5e, 0x9d, 0x56, 0x4f, 0x4f, 0x8c, 0x94, 0x50, 0x45, 0x3b,
	0xfd, 0x53, 0xab, 0x66, 0xa4, 0x51, 0x15, 0x2a, 0x6d, 0xd6, 0x8c, 0xcc, 0xde, 0x37, 0x70, 0x77,
	0xe1, 0x43, 0x3e, 0x1a, 0xf7, 0x4d, 0xdf, 0x12, 0xba, 0x4a, 0x90, 0x6b, 0xf4, 0xac, 0x56, 0xd7,
	0x48, 0xe1, 0xb2, 0xe3, 0xea, 0x91, 0xd5, 0xeb, 0x4a, 0x15, 0xcd, 0xea, 0x79, 0xa7, 0xdf, 0x33,
	0x32, 0x68, 0xf6, 0x69, 0xb5, 0xde, 0x68, 0x57, 0x7b, 0x8d, 0x4e, 0xdb, 0xc8, 0xee, 0x7d, 0x0a,
	0x05, 0xf5, 0x19, 0x1b, 0xc3, 0x70, 0x78, 0xd8, 0x79, 0x61, 0xdc, 0x51, 0xbe, 0x1c, 0x37, 0x9a,
	0x3d, 0x69, 0x4d, 0xe4, 0x65, 0x7a, 0xef, 0x53, 0xc8, 0xcb, 0x4f, 0x8a, 0xb8, 0xd7, 0x49, 0xbf,
	0xd6, 0xa8, 0x19, 0x77, 0x70, 0x61, 0xa3, 0x76, 0xd4, 0x30, 0x52, 0xa8, 0xbd, 0x5d, 0x6d, 0x59,
	0x35, 0xe9, 0x49, 0x7a, 0xef, 0x63, 0x80, 0x59, 0x9d, 0xc1, 0xe8, 0x52, 0xab, 0xdb, 0xe9, 0xd3,
	0x23, 0x4b, 0x6e, 0xd2, 0x6c, 0xf4, 0x2c, 0x5a, 0x6d, 0x1a, 0xa9, 0xbd, 0xdf, 0x64, 0x61, 0x35,
	0x51, 0x12, 0xd0, 0xe8, 0x6e, 0x8f, 0x36, 0xda, 0x75, 0x29, 0x7a, 0xd8, 0xe9, 0x34, 0xad, 0x6a,
	0x5b, 0xda, 0x53, 0xb3, 0x8e, 0x1a, 0xad, 0xaa, 0x3a, 0x99, 0xe3, 0x66, 0xa7, 0x8a, 0x9e, 0x01,
	0xe4, 0x6b, 0x9d, 0xfe, 0x61, 0xd3, 0x32, 0xb2, 0xb8, 0x53, 0xad, 0xda, 0xb3, 0x7a, 0x8d, 0x96,
	0x65, 0xe4, 0xd0, 0x3e, 0x31, 0xca, 0xe3, 0x08, 0xf9, 0x46, 0x41, 0x1c, 0xdf, 0xb9, 0x55, 0xa5,
	0xad, 0x4e, 0xbb, 0x77, 0x62, 0x14, 0x51, 0x91, 0xa0, 0x8d, 0x12, 0x59, 0x85, 0x52, 0x5d, 0xb0,
	0x6b, 0xd5, 0x73, 0x03, 0x70, 0x4d, 0x1d, 0x47, 0x65, 0x71, 0xaa, 0x52, 0x7e, 0x05, 0x85, 0x4e,
	0xac, 0x17, 0x87, 0x8d, 0x36, 0x9e, 0xe2, 0x2a, 0x31, 0x60, 0xe5, 0xb0, 0xda, 0xb5, 0xbe, 0x78,
	0xa6, 0x38, 0x6b, 0x28, 0x5c, 0x6d, 0x9f, 0xf7, 0x69, 0xc3, 0x58, 0x27, 0x9b, 0x60, 0xb4, 0x3b,
	0xb4, 0x55, 0x6d, 0x36, 0x7e, 0x6e, 0xd5, 0x94, 0x57, 0x06, 0x6e, 0xd9, 0xeb, 0x3c, 0xb7, 0xda,
	0xc6, 0x5d, 0xb4, 0xb7, 0x59, 0x6d, 0xd7, 0xfb, 0xd5, 0xba, 0x65, 0x10, 0xf4, 0xb0, 0xdd, 0x92,
	0x53, 0x1b, 0xb8, 0x3d, 0x86, 0xd4, 0xd8, 0x44, 0x8d, 0xed, 0x23, 0x31, 0xbe, 0x87, 0x22, 0x8d,
	0x76, 0xcf, 0xaa, 0x5b, 0xd4, 0xd8, 0x22, 0x5b, 0x40, 0xda, 0x9d, 0xf6, 0x69, 0xa7, 0xdb, 0xe8,
	0x35, 0xce, 0xac, 0x88, 0x7f, 0x9f, 0x6c, 0xc0, 0x7a, 0xdb, 0xaa, 0x57, 0x75, 0xa6, 0x89, 0xfa,
	0x9a, 0x9d, 0x76, 0xdd, 0x78, 0x80, 0x50, 0x6e, 0xb4, 0x7b, 0xc6, 0x36, 0x1a, 0xd2, 0x3d, 0xe9,
	0xd0, 0x9e, 0xf1, 0x8e, 0xc0, 0xc0, 0x79, 0xcf, 0x32, 0x1e, 0x2a, 0xa5, 0xf3, 0xeb, 0xdf, 0x45,
	0x4f, 0xfb, 0xed, 0x6e, 0xa3, 0xde, 0xb6, 0x6a, 0x42, 0xcf, 0x7b, 0x64, 0x1d, 0xca, 0x11, 0x07,
	0xf5, 0xbd, 0x8f, 0x90, 0x8e, 0x18, 0x52, 0xef, 0x8e, 0xbe, 0x4a, 0xe8, 0xff, 0x00, 0x8d, 0x9b,
	0xb7, 0xb8, 0xb2, 0xd7, 0x04, 0x98, 0x75, 0xc3, 0x22, 0x0e, 0x55, 0xda, 0x3b, 0xb1, 0x10, 0x93,
	0x88, 0x87, 0xa3, 0x13, 0xab, 0x55, 0x95, 0x30, 0x3b, 0xeb, 0x1c, 0x55, 0x0f, 0xfb, 0x4d, 0x8c,
	0xb5, 0x00, 0xb8, 0x82, 0x55, 0x06, 0x9d, 0x39, 0xaa, 0x1e, 0x9d, 0x58, 0x46, 0xf6, 0xe0, 0x7b,
	0xed, 0xcd, 0xd3, 0x65, 0xfc, 0xb5, 0x33, 0x60, 0xa4, 0x0e, 0x79, 0x59, 0x52, 0xc9, 0x5b, 0xde,
	0x93, 0xdb, 0x1f, 0x2c, 0x99, 0x9b, 0x7b, 0x9f, 0x5a, 0x90, 0x97, 0x6f, 0x3f, 0x72, 0xe3, 0x17,
	0x94, 0xa5, 0x6a, 0x92, 0x0f, 0xc6, 0x8b, 0xbc, 0xf8, 0x29, 0xfb, 0xf4, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xc1, 0x12, 0x81, 0x5a, 0xb0, 0x1d, 0x00, 0x00,
}
