// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hub3/fragments/fragments.proto

/*
Package fragments is a generated protocol buffer package.

It is generated from these files:
	hub3/fragments/fragments.proto

It has these top-level messages:
	FragmentResponse
	FragmentRequest
	Fragment
*/
package fragments

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ObjectType int32

const (
	ObjectType_RESOURCE ObjectType = 0
	ObjectType_LITERAL  ObjectType = 1
)

var ObjectType_name = map[int32]string{
	0: "RESOURCE",
	1: "LITERAL",
}
var ObjectType_value = map[string]int32{
	"RESOURCE": 0,
	"LITERAL":  1,
}

func (x ObjectType) String() string {
	return proto.EnumName(ObjectType_name, int32(x))
}
func (ObjectType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ObjectXSDType int32

const (
	ObjectXSDType_STRING             ObjectXSDType = 0
	ObjectXSDType_BOOLEAN            ObjectXSDType = 1
	ObjectXSDType_DECIMAL            ObjectXSDType = 2
	ObjectXSDType_FLOAT              ObjectXSDType = 3
	ObjectXSDType_DOUBLE             ObjectXSDType = 4
	ObjectXSDType_DATETIME           ObjectXSDType = 5
	ObjectXSDType_TIME               ObjectXSDType = 6
	ObjectXSDType_DATE               ObjectXSDType = 7
	ObjectXSDType_GYEARMONTH         ObjectXSDType = 8
	ObjectXSDType_GYEAR              ObjectXSDType = 9
	ObjectXSDType_GMONTHDAY          ObjectXSDType = 10
	ObjectXSDType_GDAY               ObjectXSDType = 11
	ObjectXSDType_GMONTH             ObjectXSDType = 12
	ObjectXSDType_HEXBINARY          ObjectXSDType = 13
	ObjectXSDType_BASE64BINARY       ObjectXSDType = 14
	ObjectXSDType_ANYURI             ObjectXSDType = 15
	ObjectXSDType_NORMALIZEDSTRING   ObjectXSDType = 16
	ObjectXSDType_TOKEN              ObjectXSDType = 17
	ObjectXSDType_LANGUAGE           ObjectXSDType = 18
	ObjectXSDType_NMTOKEN            ObjectXSDType = 19
	ObjectXSDType_NAME               ObjectXSDType = 20
	ObjectXSDType_NCNAME             ObjectXSDType = 21
	ObjectXSDType_INTEGER            ObjectXSDType = 22
	ObjectXSDType_NONPOSITIVEINTEGER ObjectXSDType = 23
	ObjectXSDType_NEGATIVEINTEGER    ObjectXSDType = 24
	ObjectXSDType_LONG               ObjectXSDType = 25
	ObjectXSDType_INT                ObjectXSDType = 26
	ObjectXSDType_SHORT              ObjectXSDType = 27
	ObjectXSDType_BYTE               ObjectXSDType = 28
	ObjectXSDType_NONNEGATIVEINTEGER ObjectXSDType = 29
	ObjectXSDType_UNSIGNEDLONG       ObjectXSDType = 30
	ObjectXSDType_UNSIGNEDINT        ObjectXSDType = 31
	ObjectXSDType_UNSIGNEDSHORT      ObjectXSDType = 32
	ObjectXSDType_UNSIGNEDBYTE       ObjectXSDType = 33
	ObjectXSDType_POSITIVEINTEGER    ObjectXSDType = 34
)

var ObjectXSDType_name = map[int32]string{
	0:  "STRING",
	1:  "BOOLEAN",
	2:  "DECIMAL",
	3:  "FLOAT",
	4:  "DOUBLE",
	5:  "DATETIME",
	6:  "TIME",
	7:  "DATE",
	8:  "GYEARMONTH",
	9:  "GYEAR",
	10: "GMONTHDAY",
	11: "GDAY",
	12: "GMONTH",
	13: "HEXBINARY",
	14: "BASE64BINARY",
	15: "ANYURI",
	16: "NORMALIZEDSTRING",
	17: "TOKEN",
	18: "LANGUAGE",
	19: "NMTOKEN",
	20: "NAME",
	21: "NCNAME",
	22: "INTEGER",
	23: "NONPOSITIVEINTEGER",
	24: "NEGATIVEINTEGER",
	25: "LONG",
	26: "INT",
	27: "SHORT",
	28: "BYTE",
	29: "NONNEGATIVEINTEGER",
	30: "UNSIGNEDLONG",
	31: "UNSIGNEDINT",
	32: "UNSIGNEDSHORT",
	33: "UNSIGNEDBYTE",
	34: "POSITIVEINTEGER",
}
var ObjectXSDType_value = map[string]int32{
	"STRING":             0,
	"BOOLEAN":            1,
	"DECIMAL":            2,
	"FLOAT":              3,
	"DOUBLE":             4,
	"DATETIME":           5,
	"TIME":               6,
	"DATE":               7,
	"GYEARMONTH":         8,
	"GYEAR":              9,
	"GMONTHDAY":          10,
	"GDAY":               11,
	"GMONTH":             12,
	"HEXBINARY":          13,
	"BASE64BINARY":       14,
	"ANYURI":             15,
	"NORMALIZEDSTRING":   16,
	"TOKEN":              17,
	"LANGUAGE":           18,
	"NMTOKEN":            19,
	"NAME":               20,
	"NCNAME":             21,
	"INTEGER":            22,
	"NONPOSITIVEINTEGER": 23,
	"NEGATIVEINTEGER":    24,
	"LONG":               25,
	"INT":                26,
	"SHORT":              27,
	"BYTE":               28,
	"NONNEGATIVEINTEGER": 29,
	"UNSIGNEDLONG":       30,
	"UNSIGNEDINT":        31,
	"UNSIGNEDSHORT":      32,
	"UNSIGNEDBYTE":       33,
	"POSITIVEINTEGER":    34,
}

func (x ObjectXSDType) String() string {
	return proto.EnumName(ObjectXSDType_name, int32(x))
}
func (ObjectXSDType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type FragmentResponse struct {
	Request   *FragmentRequest `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	NrTriples int32            `protobuf:"varint,2,opt,name=nrTriples" json:"nrTriples,omitempty"`
	Page      int32            `protobuf:"varint,3,opt,name=page" json:"page,omitempty"`
	Fragments []*Fragment      `protobuf:"bytes,4,rep,name=fragments" json:"fragments,omitempty"`
}

func (m *FragmentResponse) Reset()                    { *m = FragmentResponse{} }
func (m *FragmentResponse) String() string            { return proto.CompactTextString(m) }
func (*FragmentResponse) ProtoMessage()               {}
func (*FragmentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FragmentResponse) GetRequest() *FragmentRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *FragmentResponse) GetNrTriples() int32 {
	if m != nil {
		return m.NrTriples
	}
	return 0
}

func (m *FragmentResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *FragmentResponse) GetFragments() []*Fragment {
	if m != nil {
		return m.Fragments
	}
	return nil
}

type FragmentRequest struct {
	Subject   string `protobuf:"bytes,1,opt,name=subject" json:"subject,omitempty"`
	Predicate string `protobuf:"bytes,2,opt,name=predicate" json:"predicate,omitempty"`
	Object    string `protobuf:"bytes,3,opt,name=object" json:"object,omitempty"`
	Page      int32  `protobuf:"varint,4,opt,name=page" json:"page,omitempty"`
	Language  string `protobuf:"bytes,5,opt,name=language" json:"language,omitempty"`
	OrgId     string `protobuf:"bytes,6,opt,name=orgId" json:"orgId,omitempty"`
}

func (m *FragmentRequest) Reset()                    { *m = FragmentRequest{} }
func (m *FragmentRequest) String() string            { return proto.CompactTextString(m) }
func (*FragmentRequest) ProtoMessage()               {}
func (*FragmentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FragmentRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *FragmentRequest) GetPredicate() string {
	if m != nil {
		return m.Predicate
	}
	return ""
}

func (m *FragmentRequest) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *FragmentRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *FragmentRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *FragmentRequest) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

type Fragment struct {
	Spec          string        `protobuf:"bytes,1,opt,name=spec" json:"spec,omitempty"`
	Revision      int32         `protobuf:"varint,2,opt,name=revision" json:"revision,omitempty"`
	NamedGraphURI string        `protobuf:"bytes,3,opt,name=NamedGraphURI" json:"NamedGraphURI,omitempty"`
	Subject       string        `protobuf:"bytes,4,opt,name=subject" json:"subject,omitempty"`
	Predicate     string        `protobuf:"bytes,5,opt,name=predicate" json:"predicate,omitempty"`
	Object        string        `protobuf:"bytes,6,opt,name=object" json:"object,omitempty"`
	Language      string        `protobuf:"bytes,7,opt,name=language" json:"language,omitempty"`
	ObjectType    ObjectType    `protobuf:"varint,8,opt,name=objectType,enum=fragments.ObjectType" json:"objectType,omitempty"`
	DataType      ObjectXSDType `protobuf:"varint,9,opt,name=dataType,enum=fragments.ObjectXSDType" json:"dataType,omitempty"`
	OrgID         string        `protobuf:"bytes,10,opt,name=orgID" json:"orgID,omitempty"`
	Triple        string        `protobuf:"bytes,11,opt,name=triple" json:"triple,omitempty"`
	XsdRaw        string        `protobuf:"bytes,12,opt,name=xsdRaw" json:"xsdRaw,omitempty"`
	ObjectTypeRaw string        `protobuf:"bytes,13,opt,name=objectTypeRaw" json:"objectTypeRaw,omitempty"`
}

func (m *Fragment) Reset()                    { *m = Fragment{} }
func (m *Fragment) String() string            { return proto.CompactTextString(m) }
func (*Fragment) ProtoMessage()               {}
func (*Fragment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Fragment) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

func (m *Fragment) GetRevision() int32 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *Fragment) GetNamedGraphURI() string {
	if m != nil {
		return m.NamedGraphURI
	}
	return ""
}

func (m *Fragment) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Fragment) GetPredicate() string {
	if m != nil {
		return m.Predicate
	}
	return ""
}

func (m *Fragment) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *Fragment) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Fragment) GetObjectType() ObjectType {
	if m != nil {
		return m.ObjectType
	}
	return ObjectType_RESOURCE
}

func (m *Fragment) GetDataType() ObjectXSDType {
	if m != nil {
		return m.DataType
	}
	return ObjectXSDType_STRING
}

func (m *Fragment) GetOrgID() string {
	if m != nil {
		return m.OrgID
	}
	return ""
}

func (m *Fragment) GetTriple() string {
	if m != nil {
		return m.Triple
	}
	return ""
}

func (m *Fragment) GetXsdRaw() string {
	if m != nil {
		return m.XsdRaw
	}
	return ""
}

func (m *Fragment) GetObjectTypeRaw() string {
	if m != nil {
		return m.ObjectTypeRaw
	}
	return ""
}

func init() {
	proto.RegisterType((*FragmentResponse)(nil), "fragments.FragmentResponse")
	proto.RegisterType((*FragmentRequest)(nil), "fragments.FragmentRequest")
	proto.RegisterType((*Fragment)(nil), "fragments.Fragment")
	proto.RegisterEnum("fragments.ObjectType", ObjectType_name, ObjectType_value)
	proto.RegisterEnum("fragments.ObjectXSDType", ObjectXSDType_name, ObjectXSDType_value)
}

func init() { proto.RegisterFile("hub3/fragments/fragments.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 732 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x5d, 0x73, 0xe2, 0x36,
	0x14, 0xad, 0xc3, 0xa7, 0x2f, 0x10, 0x14, 0xe5, 0xa3, 0x2e, 0x49, 0x53, 0x9a, 0xe9, 0x4c, 0x99,
	0x3c, 0xa4, 0x53, 0x92, 0xf6, 0x5d, 0xc4, 0x8a, 0xe3, 0xa9, 0x91, 0x3b, 0xb2, 0xe9, 0x84, 0xbe,
	0x39, 0xa0, 0x12, 0x3a, 0x09, 0x78, 0x6d, 0xc8, 0xee, 0xbe, 0xef, 0x5f, 0xd9, 0xd9, 0xa7, 0xfd,
	0x8f, 0x3b, 0x92, 0x0d, 0x36, 0x6c, 0x36, 0x6f, 0xf7, 0x9c, 0x7b, 0xee, 0xd1, 0xb9, 0xb2, 0x47,
	0x70, 0xfa, 0xb0, 0xbc, 0xbf, 0xfc, 0xed, 0xbf, 0x28, 0x98, 0x3c, 0x89, 0xd9, 0x22, 0xce, 0xaa,
	0x8b, 0x30, 0x9a, 0x2f, 0xe6, 0x58, 0x5f, 0x13, 0x67, 0x9f, 0x35, 0x40, 0x37, 0x29, 0xe2, 0x22,
	0x0e, 0xe7, 0xb3, 0x58, 0xe0, 0x2b, 0xa8, 0x44, 0xe2, 0xcd, 0x52, 0xc4, 0x0b, 0x43, 0x6b, 0x6b,
	0x9d, 0x5a, 0xb7, 0x75, 0x91, 0x59, 0x64, 0x6a, 0xa5, 0xe0, 0x2b, 0x29, 0x3e, 0x01, 0x7d, 0x16,
	0xf9, 0xd1, 0x34, 0x7c, 0x14, 0xb1, 0xb1, 0xd3, 0xd6, 0x3a, 0x25, 0x9e, 0x11, 0x18, 0x43, 0x31,
	0x0c, 0x26, 0xc2, 0x28, 0xa8, 0x86, 0xaa, 0xf1, 0xef, 0x90, 0x25, 0x31, 0x8a, 0xed, 0x42, 0xa7,
	0xd6, 0xdd, 0x7f, 0xe9, 0xa4, 0x5c, 0xde, 0x4f, 0x1a, 0x34, 0xb7, 0x12, 0x60, 0x03, 0x2a, 0xf1,
	0xf2, 0xfe, 0x7f, 0x31, 0x4a, 0xe2, 0xea, 0x7c, 0x05, 0x65, 0xa4, 0x30, 0x12, 0xe3, 0xe9, 0x28,
	0x58, 0x08, 0x15, 0x49, 0xe7, 0x19, 0x81, 0x8f, 0xa0, 0x3c, 0x4f, 0xc6, 0x0a, 0xaa, 0x95, 0xa2,
	0x75, 0xd4, 0x62, 0x2e, 0x6a, 0x0b, 0xaa, 0x8f, 0xc1, 0x6c, 0xb2, 0x94, 0x7c, 0x49, 0xa9, 0xd7,
	0x18, 0x1f, 0x40, 0x69, 0x1e, 0x4d, 0xec, 0xb1, 0x51, 0x56, 0x8d, 0x04, 0x9c, 0x7d, 0x2c, 0x40,
	0x75, 0x95, 0x54, 0x5a, 0xc6, 0xa1, 0x18, 0xa5, 0xf9, 0x54, 0x2d, 0x2d, 0x23, 0xf1, 0x3c, 0x8d,
	0xa7, 0xf3, 0x59, 0x7a, 0x5d, 0x6b, 0x8c, 0x7f, 0x81, 0x06, 0x0b, 0x9e, 0xc4, 0xd8, 0x8a, 0x82,
	0xf0, 0x61, 0xc0, 0xed, 0x34, 0xe1, 0x26, 0x99, 0x5f, 0xbc, 0xf8, 0xca, 0xe2, 0xa5, 0x6f, 0x2f,
	0x5e, 0xde, 0x58, 0x3c, 0xbf, 0x64, 0x65, 0x6b, 0xc9, 0x3f, 0x00, 0x12, 0x95, 0xff, 0x3e, 0x14,
	0x46, 0xb5, 0xad, 0x75, 0x76, 0xbb, 0x87, 0xb9, 0x8f, 0xe5, 0xae, 0x9b, 0x3c, 0x27, 0xc4, 0x57,
	0x50, 0x1d, 0x07, 0x8b, 0x40, 0x0d, 0xe9, 0x6a, 0xc8, 0xf8, 0x6a, 0xe8, 0xce, 0x33, 0xd5, 0xdc,
	0x5a, 0xb9, 0xba, 0x51, 0xd3, 0x80, 0xec, 0x46, 0x4d, 0x19, 0x7b, 0xa1, 0xfe, 0x26, 0xa3, 0x96,
	0xc4, 0x4e, 0x90, 0xe4, 0xdf, 0xc5, 0x63, 0x1e, 0xbc, 0x35, 0xea, 0x09, 0x9f, 0x20, 0x79, 0x89,
	0x59, 0x12, 0xd9, 0x6e, 0x24, 0x97, 0xb8, 0x41, 0x9e, 0xff, 0x0a, 0x90, 0x65, 0xc7, 0x75, 0xa8,
	0x72, 0xea, 0xb9, 0x03, 0x7e, 0x4d, 0xd1, 0x77, 0xb8, 0x06, 0x15, 0xc7, 0xf6, 0x29, 0x27, 0x0e,
	0xd2, 0xce, 0x3f, 0x14, 0xa1, 0xb1, 0x11, 0x18, 0x03, 0x94, 0x3d, 0x9f, 0xdb, 0xcc, 0x4a, 0xa4,
	0x3d, 0xd7, 0x75, 0x28, 0x61, 0x48, 0x93, 0xc0, 0xa4, 0xd7, 0x76, 0x9f, 0x38, 0x68, 0x07, 0xeb,
	0x50, 0xba, 0x71, 0x5c, 0xe2, 0xa3, 0x82, 0x1c, 0x30, 0xdd, 0x41, 0xcf, 0xa1, 0xa8, 0x28, 0x4f,
	0x32, 0x89, 0x4f, 0x7d, 0xbb, 0x4f, 0x51, 0x09, 0x57, 0xa1, 0xa8, 0xaa, 0xb2, 0xac, 0x24, 0x8f,
	0x2a, 0x78, 0x17, 0xc0, 0x1a, 0x52, 0xc2, 0xfb, 0x2e, 0xf3, 0x6f, 0x51, 0x55, 0x1a, 0x29, 0x8c,
	0x74, 0xdc, 0x00, 0xdd, 0x52, 0xb4, 0x49, 0x86, 0x08, 0xe4, 0x8c, 0x25, 0xab, 0x9a, 0x3c, 0x21,
	0x69, 0xa0, 0xba, 0x14, 0xdd, 0xd2, 0xbb, 0x9e, 0xcd, 0x08, 0x1f, 0xa2, 0x06, 0x46, 0x50, 0xef,
	0x11, 0x8f, 0xfe, 0x79, 0x95, 0x32, 0xbb, 0x52, 0x4c, 0xd8, 0x70, 0xc0, 0x6d, 0xd4, 0xc4, 0x07,
	0x80, 0x98, 0xcb, 0xfb, 0xc4, 0xb1, 0xff, 0xa5, 0x66, 0xba, 0x15, 0x92, 0x47, 0xfa, 0xee, 0x5f,
	0x94, 0xa1, 0x3d, 0x99, 0xd7, 0x21, 0xcc, 0x1a, 0x10, 0x8b, 0x22, 0x2c, 0x37, 0x64, 0xfd, 0xa4,
	0xb5, 0x2f, 0x8f, 0x67, 0xa4, 0x4f, 0xd1, 0x81, 0x74, 0x64, 0xd7, 0xaa, 0x3e, 0x94, 0x12, 0x9b,
	0xf9, 0xd4, 0xa2, 0x1c, 0x1d, 0xe1, 0x23, 0xc0, 0xcc, 0x65, 0x7f, 0xbb, 0x9e, 0xed, 0xdb, 0xff,
	0xd0, 0x15, 0xff, 0x3d, 0xde, 0x87, 0x26, 0xa3, 0x16, 0xc9, 0x93, 0x86, 0xf4, 0x73, 0x5c, 0x66,
	0xa1, 0x1f, 0x70, 0x05, 0x0a, 0x36, 0xf3, 0x51, 0x4b, 0x06, 0xf1, 0x6e, 0x5d, 0xee, 0xa3, 0x63,
	0xd9, 0xed, 0x0d, 0x7d, 0x8a, 0x4e, 0x52, 0xd3, 0xed, 0xf9, 0x1f, 0xe5, 0xa6, 0x03, 0xe6, 0xd9,
	0x16, 0xa3, 0xa6, 0xf2, 0x39, 0xc5, 0x4d, 0xa8, 0xad, 0x18, 0xe9, 0xf7, 0x13, 0xde, 0x83, 0xc6,
	0x8a, 0x48, 0x7c, 0xdb, 0xf9, 0x29, 0xe5, 0xff, 0xb3, 0x0c, 0xb7, 0x9d, 0xf8, 0xac, 0xeb, 0x67,
	0x0f, 0x90, 0x27, 0xa2, 0xe7, 0xe9, 0x48, 0x60, 0x02, 0x65, 0x4f, 0x04, 0xd1, 0xe8, 0x01, 0xbf,
	0xf2, 0x50, 0xb6, 0x8e, 0x5f, 0xec, 0x25, 0x4f, 0xee, 0x7d, 0x59, 0xbd, 0xcc, 0x97, 0x5f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x2e, 0xc6, 0x8c, 0x1d, 0xbb, 0x05, 0x00, 0x00,
}
