#%RAML 1.0 Trait
usage: Apply this to any method that can be filterable
queryParameters:
  qf:
    description: |
      Filter the results by `ResourceEntry.value`. These are exact string matches. So there is not tokenization on these fields when used as a filter.

      Any type of QueryFilter can have an `[]` suffix appended to it. Some browsers or applications require this to have multiple query Parameters.
    required: false
  qf.id:
    required: false
    description: |
      Filter the results by `ResourceEntry.@id`. This can be used to filter on RDF object resources links.
    example: qf.id=edm_rights:https://rightsstatements.org/vocab/InC/1.0/
  qf.exist:
    required: false
    description: |
      Filter the results if a `ResourceEntry.searchLabel` exists
    example: qf.exist=dc_subject
    #qf.dateRange:
    #required: false
