#%RAML 1.0 Trait

usage: Apply this to any method that can be sorted
queryParameters:
  sortBy:
    description: |
      Sort result by `Meta` subfields, `ResourceEntry.searchLabel` and `ResourceEntry.tags`. 

      The default search field is the revelancy score returned by the search-engine.

      Only the first queryParam is selected, and others are ignored.
    type: string
    required: false
    default: _score
    example:
      - sortBy=meta.spec
      - sortBy=dc_creator
      - sortBy=tags.identifier
  sortOrder:
    description: Setting the sort order
    enum: [desc, asc]
    default: desc
    required: false
  sortAsc:
    description: shortcut for sorting ascending
    type: boolean
    default: false
    required: false
