#%RAML 1.0 Library

usage: Common traits for the HTTP API

traits:
  contentCacheable: !include content-cacheable.raml
  facetable: !include facetable.raml
  filterable: !include filterable.raml
  orderable: !include orderable.raml
  pageable: !include pageable.raml
  partial: !include partial.raml
  searchable: !include searchable.raml
  sortable: !include sortable.raml
