#%RAML 1.0 Library

usage: |
  Common traits for the HTTP API

traits:
  searchable: !include searchable.raml
  facetable: !include facetable.raml
  itemFormat: !include item.format.raml
  orderable: !include orderable.raml
  pageable: !include pageable.raml
  filterable: !include filterable.raml
  # ------
  contentCacheable: !include content-cacheable.raml
  partial: !include partial.raml
