#%RAML 1.0
---
title: Hub3 (Ikuzo) API 1
description: This is .
version: v1

baseUri:
  value: http://{environment}.{subdomain}.delving.io/{version}
  (rediractable): true

baseUriParameters:
  environment:
    type: string
    enum: [  "dev", "test", "acpt", "prod"]
  subdomain:
    description: subdomain of API
    default: api

protocols: [ HTTPS ]
mediaType: [ application/json ]

documentation:
  - title: Getting Started
    content: |
      This is a getting started guide for the World Music API.
  - title: Legal
    content: See http://legal.musicapi.com

uses:
  traits: !include modules/traits/traits.lib.raml
  anno: !include modules/annotationTypes/annotations.lib.raml
  shapes: !include modules/dataTypes/shapes.lib.raml
  resources: !include modules/resourceTypes/resource-types.lib.raml

(info):
  license: Apache2


/api:
  /search:
    /v2:
      get:
        description: RDF search API indexed resource graphs
        responses:
          200:


/orgs:
  displayName: Organizations
  type:
    collection:
      request-type: shapes.NewOrganizationData
      response-type: shapes.OrganizationData
      response-example:
        id: demo
        baseUrl: "https://demo.example.com"
  /{orgID}:
    type:
      member:
        get-response-type: shapes.OrganizationData
        get-response-example:
          id: demo
          baseUrl: "https://demo.example.com"
    uriParameters:
      orgID: string
    /datasets:
      get:
      put:
        is: [secured]
      /{datasetID}:
        get:
        put:
          is: [secured]
        delete:
          is: [secured]
        /stats:
          get:
        /tasks:
          get:
    /search:
      /v1:
        is: [ orderable, pageable ]
        get:
        /{hubID}:
          get:
      /v2:
        is: [ orderable, pageable ]
        get:
        /{hubID}:
          get:
    /tasks:
      description: api for long running tasks
      get:
        description: list active tasks
      /{taskID}:
        get:
          description: get information for specific task
        delete:
          description: cancel running task
    /archives:
      description: this can also be accessed via ead
      put:
        is: [secured]
      /search:
        description: search through all archives. 
        get:
        /{archiveID}:
          description: search in single archive
          get:
      /{archiveID}:
        /download:
          description: download the source EAD XML
          get:
        /description:
          description: search through the description of the API
        /inventories:
          description: search through the inventory entries of a single archive.
          get:
          /{inventoryID}:
            description:
        /stats:
         description: statistics view on archival tree for the clevels
         get:
        /mets:
          description: 
          get:
    /index:
      description: index RDF data
      post:
        is: [secured]
      /bulk:
        description: endpoint for Narthex to index in the line-delimited BulkAction format
        post:
          is: [secured]
    /oaipmh:
      description: OAI-PMH endpoint
      get:
    /data:
      description: Linked Open Data endpoint for RDF format
      get:
    /resource:
      description: Linked Open Data resolver. When 'Content-Type' header is a supported RDF format redirect to /data otherwise redirect to /page view for HTML representation
    /page:
      description: HTML presentation of RDF Resource
    /resolver:
      description: Linked Open Data resolver that doesn't do the content negotiation but returns the RDF when the item is in the RDF store. This is useful for front-end libraries that proxy as Linked Open Data Resolvers
    /sparql:
      description: 



      

