// Code generated by "stringer -type=HexPosition"; DO NOT EDIT.

package hextuples

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Subject-0]
	_ = x[Predicate-1]
	_ = x[Value-2]
	_ = x[DataType-3]
	_ = x[Language-4]
	_ = x[Graph-5]
}

const _HexPosition_name = "SubjectPredicateValueDataTypeLanguageGraph"

var _HexPosition_index = [...]uint8{0, 7, 16, 21, 29, 37, 42}

func (i HexPosition) String() string {
	if i < 0 || i >= HexPosition(len(_HexPosition_index)-1) {
		return "HexPosition(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HexPosition_name[_HexPosition_index[i]:_HexPosition_index[i+1]]
}
