// Code generated by "stringer -type=hexPosition"; DO NOT EDIT.

package hextuples

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[subject-0]
	_ = x[predicate-1]
	_ = x[value-2]
	_ = x[dataType-3]
	_ = x[language-4]
	_ = x[graph-5]
}

const _hexPosition_name = "subjectpredicatevaluedataTypelanguagegraph"

var _hexPosition_index = [...]uint8{0, 7, 16, 21, 29, 37, 42}

func (i hexPosition) String() string {
	if i < 0 || i >= hexPosition(len(_hexPosition_index)-1) {
		return "hexPosition(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _hexPosition_name[_hexPosition_index[i]:_hexPosition_index[i+1]]
}
